In [ ]:
import sys
sys.path.append('../')

In [2]:
from src.config import DB_CONFIG, TREANSACTION_CODE
from src.model.get_client_T24 import GetClientT24
from src.controller.transaction_router import TransactionRouter

In [3]:
get_client_T24 = GetClientT24(DB_CONFIG)
#transaction_router = TransactionRouter(TREANSACTION_CODE, DB_CONFIG)

In [4]:
get_client_T24.get_PPH('c75c3mz65', 'LEGAL_ID')

2025-12-30 16:19:21,600 - INFO - Starting to retrieve PPH data for customer ID c75c3mz65
2025-12-30 16:19:21,779 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = '' THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                UPPER(LEGAL_ID) = 'C75C3MZ65'

2025-12-30 16:19:21,782 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = '' THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                UPPER(LEGAL_ID) = 'C75C3MZ65'

Connection established successfully.

            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = '' THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                UPPER(LEGAL_ID) = 'C75C3MZ65'

2025-12-30 16:19:26,784 - WARNING - Failed to execute query after 1 attempts
2025-12-30 16:19:26,788 - WARNING - No PPH data found for customer ID c75c3mz65

Connection closed.

Empty DataFrame
Columns: []
Index: []

In [4]:
account_number = '5820061625500'
print(get_client_T24.account_status_lookup(account_number)) # True -> Active Account

account_correspondences, account_details, customer_id, account_type, account_rp = get_client_T24.get_client(account_number)

2026-01-07 09:36:34,383 - INFO - Executing account status lookup for account: 5820061625500
2026-01-07 09:36:34,399 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820061625500'

2026-01-07 09:36:34,401 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820061625500'

2026-01-07 09:36:34,402 - INFO - Account 5820061625500 is IS_ACTIVE
2026-01-07 09:36:34,414 - INFO - Executing account status lookup for account: 5820061625500
2026-01-07 09:36:34,419 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820061625500'

2026-01-07 09:36:34,420 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820061625500'

2026-01-07 09:36:34,422 - INFO - Account 5820061625500 is IS_ACTIVE
2026-01-07 09:36:34,434 - INFO - Executing query to retrieve account information for account number: 5820061625500

Connection established successfully.
Connection closed.
True
Connection established successfully.
Connection closed.
Connection established successfully.

2026-01-07 09:36:36,115 - INFO - Successfully executed query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    --EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.WORKING_BALANCE AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        --WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE
                    LEFT(ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER, 1) IN ('5', '6')
					AND CAST(LEFT(ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER, 3) AS INT) BETWEEN 500 AND 599
					AND ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820061625500'

2026-01-07 09:36:36,119 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    --EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.WORKING_BALANCE AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        --WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE
                    LEFT(ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER, 1) IN ('5', '6')
					AND CAST(LEFT(ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER, 3) AS INT) BETWEEN 500 AND 599
					AND ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820061625500'

2026-01-07 09:36:36,123 - INFO - Successfully retrieved account information for account number: 5820061625500
2026-01-07 09:36:36,136 - INFO - Executing query to retrieve arrangement information for arrangement id : AA230319C6RV

Connection closed.
Connection established successfully.

2026-01-07 09:36:36,460 - INFO - Successfully executed query:
        SELECT
            LEFT(RECID, CHARINDEX('-', RECID) - 1) AS ARRANGEMENT_ID,
            CUSTOMER_3,
            CUSTOMER_ROLE_4,
            L_ACCT_TYPE
        FROM [MISDW].[GO_AML].[T24_FATB_AA_ARR_CUSTOMER]
        WHERE
            LEFT(RECID, CHARINDEX('-', RECID) - 1) = 'AA230319C6RV'

2026-01-07 09:36:36,464 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            LEFT(RECID, CHARINDEX('-', RECID) - 1) AS ARRANGEMENT_ID,
            CUSTOMER_3,
            CUSTOMER_ROLE_4,
            L_ACCT_TYPE
        FROM [MISDW].[GO_AML].[T24_FATB_AA_ARR_CUSTOMER]
        WHERE
            LEFT(RECID, CHARINDEX('-', RECID) - 1) = 'AA230319C6RV'

2026-01-07 09:36:36,467 - INFO - Successfully retrieved account information for arrangement id : AA230319C6RV
2026-01-07 09:36:36,801 - INFO - Starting to retrieve PPH data for customer ID 61625
2026-01-07 09:36:36,879 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = '' THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '61625'

2026-01-07 09:36:36,883 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = '' THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '61625'

2026-01-07 09:36:36,885 - INFO - Retrieved PPH data successfully for customer ID 61625
2026-01-07 09:36:36,895 - INFO - Executing query to retrieve mandates information for account mandate id : None
2026-01-07 09:36:36,910 - INFO - Successfully executed query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = 'None'

2026-01-07 09:36:36,912 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = 'None'

Connection closed.
  ARRANGEMENT_ID CUSTOMER_ID CUSTOMER_ROLE L_ACCT_TYPE
0   AA230319C6RV       61625         OWNER           3
The DataFrame has only one record, and CUSTOMER_ROLE is OWNER.
Connection established successfully.
Connection closed.
Connection established successfully.

2026-01-07 09:36:41,914 - WARNING - Failed to execute query after 1 attempts
2026-01-07 09:36:41,915 - WARNING - No data found for account mandate id : None

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER     FIRST_NAME LAST_NAME  \
0           PPH       61625      M  MOHAMED SADEK   SNOUSSI

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1996-09-22T00:00:00  TN - TORKI            CIN  09860144             TN

   ... NATIONALITY RESIDENCE ADDRESS_TYPE          ADDRESS       TOWN CITY  \
0  ...          TN        TN            1  TORKI GROMBALIA  GROMBALIA  N.A

    ZIP COUNTRY_CODE                                         OCCUPATION  \
0  8030           TN  Cadres de directions des services administrati...

  ROLE_ACCOUNT
0        TICPT

[1 rows x 22 columns]
==================
+++++++++++++++

In [5]:
account_rp

,CUSTOMER_TYPE,CUSTOMER_ID,GENDER,FIRST_NAME,LAST_NAME,BIRTHDATE,BIRTH_PLACE,NATIONALITY,RESIDENCE,ADDRESS_TYPE,ADDRESS,TOWN,CITY,ZIP,COUNTRY_CODE,OCCUPATION,ROLE_ACCOUNT,IDENTIFICATIONS_ID_SECTION,ACCOUNT_TYPE
0,PPH,61625,M,MOHAMED SADEK,SNOUSSI,1996-09-22T00:00:00,TN - TORKI,TN,TN,1,TORKI GROMBALIA,GROMBALIA,N.A,8030,TN,Cadres de directions des services administrati...,TICPT,<identification><type>B</type><number>09860144...,CST

In [4]:
account_number = '5830764564504'# cj'5850386089520'
print(get_client_T24.account_status_lookup(account_number)) # True -> Active Account

account_correspondences_2, account_details_2, customer_id_2, account_type_2, account_rp_2 = get_client_T24.get_client(account_number)

2026-01-07 10:21:22,993 - INFO - Executing account status lookup for account: 5830764564504
2026-01-07 10:21:23,015 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5830764564504'

2026-01-07 10:21:23,017 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5830764564504'

2026-01-07 10:21:23,020 - INFO - Account 5830764564504 is IS_ACTIVE
2026-01-07 10:21:23,034 - INFO - Executing account status lookup for account: 5830764564504
2026-01-07 10:21:23,040 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5830764564504'

2026-01-07 10:21:23,041 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5830764564504'

2026-01-07 10:21:23,043 - INFO - Account 5830764564504 is IS_ACTIVE
2026-01-07 10:21:23,056 - INFO - Executing query to retrieve account information for account number: 5830764564504

Connection established successfully.
Connection closed.
True
Connection established successfully.
Connection closed.
Connection established successfully.

2026-01-07 10:21:24,796 - INFO - Successfully executed query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    --EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.WORKING_BALANCE AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        --WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE
                    LEFT(ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER, 1) IN ('5', '6')
					AND CAST(LEFT(ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER, 3) AS INT) BETWEEN 500 AND 599
					AND ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5830764564504'

2026-01-07 10:21:24,800 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    --EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.WORKING_BALANCE AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        --WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE
                    LEFT(ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER, 1) IN ('5', '6')
					AND CAST(LEFT(ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER, 3) AS INT) BETWEEN 500 AND 599
					AND ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5830764564504'

2026-01-07 10:21:24,804 - INFO - Successfully retrieved account information for account number: 5830764564504
2026-01-07 10:21:24,822 - INFO - Starting to retrieve PM data for customer ID 764564
2026-01-07 10:21:24,884 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PM
            SELECT
                NAME_1 AS NAME,
                'N.A' AS LEGAL_FORM_DESC_ATB,
                L_FORM_JURID AS LEGAL_FORM_CODE_ATB,
                FJ.code_goAML AS LEGAL_FORM_CODE_goAML,
                INDUSTRY.DESCRIPTION AS BUSINESS_DESC,
                CASE
                    WHEN CUSTOMER.L_SIT_JUR = 2 THEN 'A'
                    ELSE 'I'
                END AS ENTITY_STATUS,
                '2' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COUNTRY AS INCORPORATION_COUNTRY_CODE,
                CASE
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, BIRTH_INCORP_DATE))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, BIRTH_INCORP_DATE))), 23) + 'T00:00:00'
                    ELSE 'N.A'
                END AS INCORPORATION_DATE,
                'MF' AS ENTITY_IDENTIFIER_TYPE,
                CUSTOMER.LEGAL_ID AS ENTITY_IDENTIFIER_ID,
                CUSTOMER.COUNTRY AS ENTITY_ISSUE_COUNTRY
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
            LEFT JOIN [MISDW].[GO_AML].[FORME_JURIDIQUE] AS FJ ON FORMAT(CAST(FJ.ID_FORMJ AS INT), '00') = FORMAT(CAST(CUSTOMER.L_FORM_JURID AS INT), '00')
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_INDUSTRY] AS INDUSTRY ON RIGHT(REPLICATE('0', 4) + INDUSTRY.INDUSTRY_CODE, 4) = RIGHT(REPLICATE('0', 4) + CUSTOMER.INDUSTRY, 4)
            WHERE CUSTOMER_CODE = '764564'

2026-01-07 10:21:24,887 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PM
            SELECT
                NAME_1 AS NAME,
                'N.A' AS LEGAL_FORM_DESC_ATB,
                L_FORM_JURID AS LEGAL_FORM_CODE_ATB,
                FJ.code_goAML AS LEGAL_FORM_CODE_goAML,
                INDUSTRY.DESCRIPTION AS BUSINESS_DESC,
                CASE
                    WHEN CUSTOMER.L_SIT_JUR = 2 THEN 'A'
                    ELSE 'I'
                END AS ENTITY_STATUS,
                '2' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COUNTRY AS INCORPORATION_COUNTRY_CODE,
                CASE
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, BIRTH_INCORP_DATE))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, BIRTH_INCORP_DATE))), 23) + 'T00:00:00'
                    ELSE 'N.A'
                END AS INCORPORATION_DATE,
                'MF' AS ENTITY_IDENTIFIER_TYPE,
                CUSTOMER.LEGAL_ID AS ENTITY_IDENTIFIER_ID,
                CUSTOMER.COUNTRY AS ENTITY_ISSUE_COUNTRY
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
            LEFT JOIN [MISDW].[GO_AML].[FORME_JURIDIQUE] AS FJ ON FORMAT(CAST(FJ.ID_FORMJ AS INT), '00') = FORMAT(CAST(CUSTOMER.L_FORM_JURID AS INT), '00')
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_INDUSTRY] AS INDUSTRY ON RIGHT(REPLICATE('0', 4) + INDUSTRY.INDUSTRY_CODE, 4) = RIGHT(REPLICATE('0', 4) + CUSTOMER.INDUSTRY, 4)
            WHERE CUSTOMER_CODE = '764564'

2026-01-07 10:21:24,890 - INFO - Retrieved PM data successfully for customer ID 764564
2026-01-07 10:21:24,918 - INFO - Executing query to retrieve related third party information for customer id : 764564

Connection closed.
Connection established successfully.
Connection closed.
Connection established successfully.

2026-01-07 10:21:25,041 - INFO - Successfully executed query:
        SELECT
            RELATION_CUSTOMER.CUSTOMER,
            RELATION_CUSTOMER.OF_CUSTOMER_2,
            RELATION_CUSTOMER.IS_RELATION_1,
            CUSTOMER_ROLE.ROLE_14
        FROM [MISDW].[GO_AML].[T24_FBNK_RELATION_CUSTOMER] AS RELATION_CUSTOMER
        LEFT JOIN [MISDW].[GO_AML].[T24_FBNK_CUSTOMER_ROLE] AS CUSTOMER_ROLE ON RELATION_CUSTOMER.CUSTOMER = CUSTOMER_ROLE.RECID
        WHERE RELATION_CUSTOMER.CUSTOMER = '764564'

2026-01-07 10:21:25,043 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            RELATION_CUSTOMER.CUSTOMER,
            RELATION_CUSTOMER.OF_CUSTOMER_2,
            RELATION_CUSTOMER.IS_RELATION_1,
            CUSTOMER_ROLE.ROLE_14
        FROM [MISDW].[GO_AML].[T24_FBNK_RELATION_CUSTOMER] AS RELATION_CUSTOMER
        LEFT JOIN [MISDW].[GO_AML].[T24_FBNK_CUSTOMER_ROLE] AS CUSTOMER_ROLE ON RELATION_CUSTOMER.CUSTOMER = CUSTOMER_ROLE.RECID
        WHERE RELATION_CUSTOMER.CUSTOMER = '764564'

2026-01-07 10:21:25,047 - INFO - Successfully retrieved related third party information for customer id : 764564
2026-01-07 10:21:25,065 - INFO - Starting to retrieve PM-related person details based on Level 1 results.
2026-01-07 10:21:25,073 - INFO - Processing row for RELATED_PERSON_ID 116344 with RELATED_PERSON_ROLE 90
2026-01-07 10:21:25,133 - INFO - Successfully executed query:
                SELECT
                    CUSTOMER_CODE AS CUSTOMER_ID,
                	L_NATURE_CLIENT AS CUSTOMER_TYPE,
                    CASE
                        WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                        WHEN GENDER = 'MALE' THEN 'M'
                        WHEN GENDER = 'FEMALE' THEN 'F'
                    END AS GENDER,
                    GIVEN_NAMES AS FIRST_NAME,
                    FAMILY_NAME AS LAST_NAME,
                    CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                    CASE
					    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					        NULLIF(COUNTRY, ''),
					        NULLIF(CUST_BIRTH_COUNTRY, ''),
					        NULLIF(L_PLACE_OF_BIRT, '')
					    )
					END AS BIRTH_PLACE,
                    LEGAL_DOC_NAME,
                    LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                    LEGAL_ISS_AUTH, --Pays d'émission du passeport
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                    NATIONALITY,
                    RESIDENCE,
                    '1' AS ADDRESS_TYPE,
                    COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                    COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                    COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                    COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
	                --CASE
					--    WHEN COALESCE(COUNTRY, '') = ''
					--         AND COALESCE(TOWN_COUNTRY, '') = ''
					--         AND COALESCE(ADDRESS_ITEM1, '') = ''
					--         AND COALESCE(ADDRESS_ITEM2, '') = ''
					--         AND COALESCE(STREET, '') = ''
					--         AND COALESCE(ADDRESS, '') = ''
					--        THEN 'N.A'
					--    ELSE CONCAT_WS(' - ',
					--         NULLIF(COUNTRY, ''),
					--         NULLIF(TOWN_COUNTRY, ''),
					--         NULLIF(ADDRESS_ITEM1, ''),
					--         NULLIF(ADDRESS_ITEM2, ''),
					--         NULLIF(STREET, ''),
					--         NULLIF(ADDRESS, ''))
					--END AS ADDRESS,
                    COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                	COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION,
                    '309' AS RELATED_PERSON_RELATION_CODE_ATB,
                    '90' AS RELATED_PERSON_ROLE_CODE_ATB,
                    'CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML' AS ROLE_ENTITY -- relation with the entity
                    --'MAND' AS ROLE_ACCOUNT -- Relation to the account
                --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS CUSTOMER
                FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
                LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
                WHERE
                    CUSTOMER.CUSTOMER_CODE = '116344'

2026-01-07 10:21:25,134 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
                    CUSTOMER_CODE AS CUSTOMER_ID,
                	L_NATURE_CLIENT AS CUSTOMER_TYPE,
                    CASE
                        WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                        WHEN GENDER = 'MALE' THEN 'M'
                        WHEN GENDER = 'FEMALE' THEN 'F'
                    END AS GENDER,
                    GIVEN_NAMES AS FIRST_NAME,
                    FAMILY_NAME AS LAST_NAME,
                    CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                    CASE
					    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					        NULLIF(COUNTRY, ''),
					        NULLIF(CUST_BIRTH_COUNTRY, ''),
					        NULLIF(L_PLACE_OF_BIRT, '')
					    )
					END AS BIRTH_PLACE,
                    LEGAL_DOC_NAME,
                    LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                    LEGAL_ISS_AUTH, --Pays d'émission du passeport
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                    NATIONALITY,
                    RESIDENCE,
                    '1' AS ADDRESS_TYPE,
                    COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                    COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                    COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                    COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
	                --CASE
					--    WHEN COALESCE(COUNTRY, '') = ''
					--         AND COALESCE(TOWN_COUNTRY, '') = ''
					--         AND COALESCE(ADDRESS_ITEM1, '') = ''
					--         AND COALESCE(ADDRESS_ITEM2, '') = ''
					--         AND COALESCE(STREET, '') = ''
					--         AND COALESCE(ADDRESS, '') = ''
					--        THEN 'N.A'
					--    ELSE CONCAT_WS(' - ',
					--         NULLIF(COUNTRY, ''),
					--         NULLIF(TOWN_COUNTRY, ''),
					--         NULLIF(ADDRESS_ITEM1, ''),
					--         NULLIF(ADDRESS_ITEM2, ''),
					--         NULLIF(STREET, ''),
					--         NULLIF(ADDRESS, ''))
					--END AS ADDRESS,
                    COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                	COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION,
                    '309' AS RELATED_PERSON_RELATION_CODE_ATB,
                    '90' AS RELATED_PERSON_ROLE_CODE_ATB,
                    'CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML' AS ROLE_ENTITY -- relation with the entity
                    --'MAND' AS ROLE_ACCOUNT -- Relation to the account
                --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS CUSTOMER
                FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
                LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
                WHERE
                    CUSTOMER.CUSTOMER_CODE = '116344'

2026-01-07 10:21:25,136 - INFO - Data retrieved successfully for RELATED_PERSON_ID 116344
2026-01-07 10:21:25,137 - INFO - Processing row for RELATED_PERSON_ID 116344 with RELATED_PERSON_ROLE 90
2026-01-07 10:21:25,194 - INFO - Successfully executed query:
                SELECT
                    CUSTOMER_CODE AS CUSTOMER_ID,
                	L_NATURE_CLIENT AS CUSTOMER_TYPE,
                    CASE
                        WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                        WHEN GENDER = 'MALE' THEN 'M'
                        WHEN GENDER = 'FEMALE' THEN 'F'
                    END AS GENDER,
                    GIVEN_NAMES AS FIRST_NAME,
                    FAMILY_NAME AS LAST_NAME,
                    CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                    CASE
					    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					        NULLIF(COUNTRY, ''),
					        NULLIF(CUST_BIRTH_COUNTRY, ''),
					        NULLIF(L_PLACE_OF_BIRT, '')
					    )
					END AS BIRTH_PLACE,
                    LEGAL_DOC_NAME,
                    LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                    LEGAL_ISS_AUTH, --Pays d'émission du passeport
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                    NATIONALITY,
                    RESIDENCE,
                    '1' AS ADDRESS_TYPE,
                    COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                    COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                    COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                    COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
	                --CASE
					--    WHEN COALESCE(COUNTRY, '') = ''
					--         AND COALESCE(TOWN_COUNTRY, '') = ''
					--         AND COALESCE(ADDRESS_ITEM1, '') = ''
					--         AND COALESCE(ADDRESS_ITEM2, '') = ''
					--         AND COALESCE(STREET, '') = ''
					--         AND COALESCE(ADDRESS, '') = ''
					--        THEN 'N.A'
					--    ELSE CONCAT_WS(' - ',
					--         NULLIF(COUNTRY, ''),
					--         NULLIF(TOWN_COUNTRY, ''),
					--         NULLIF(ADDRESS_ITEM1, ''),
					--         NULLIF(ADDRESS_ITEM2, ''),
					--         NULLIF(STREET, ''),
					--         NULLIF(ADDRESS, ''))
					--END AS ADDRESS,
                    COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                	COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION,
                    '307' AS RELATED_PERSON_RELATION_CODE_ATB,
                    '90' AS RELATED_PERSON_ROLE_CODE_ATB,
                    'CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML' AS ROLE_ENTITY -- relation with the entity
                    --'MAND' AS ROLE_ACCOUNT -- Relation to the account
                --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS CUSTOMER
                FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
                LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
                WHERE
                    CUSTOMER.CUSTOMER_CODE = '116344'

2026-01-07 10:21:25,196 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
                    CUSTOMER_CODE AS CUSTOMER_ID,
                	L_NATURE_CLIENT AS CUSTOMER_TYPE,
                    CASE
                        WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                        WHEN GENDER = 'MALE' THEN 'M'
                        WHEN GENDER = 'FEMALE' THEN 'F'
                    END AS GENDER,
                    GIVEN_NAMES AS FIRST_NAME,
                    FAMILY_NAME AS LAST_NAME,
                    CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                    CASE
					    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					        NULLIF(COUNTRY, ''),
					        NULLIF(CUST_BIRTH_COUNTRY, ''),
					        NULLIF(L_PLACE_OF_BIRT, '')
					    )
					END AS BIRTH_PLACE,
                    LEGAL_DOC_NAME,
                    LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                    LEGAL_ISS_AUTH, --Pays d'émission du passeport
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                    NATIONALITY,
                    RESIDENCE,
                    '1' AS ADDRESS_TYPE,
                    COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                    COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                    COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                    COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
	                --CASE
					--    WHEN COALESCE(COUNTRY, '') = ''
					--         AND COALESCE(TOWN_COUNTRY, '') = ''
					--         AND COALESCE(ADDRESS_ITEM1, '') = ''
					--         AND COALESCE(ADDRESS_ITEM2, '') = ''
					--         AND COALESCE(STREET, '') = ''
					--         AND COALESCE(ADDRESS, '') = ''
					--        THEN 'N.A'
					--    ELSE CONCAT_WS(' - ',
					--         NULLIF(COUNTRY, ''),
					--         NULLIF(TOWN_COUNTRY, ''),
					--         NULLIF(ADDRESS_ITEM1, ''),
					--         NULLIF(ADDRESS_ITEM2, ''),
					--         NULLIF(STREET, ''),
					--         NULLIF(ADDRESS, ''))
					--END AS ADDRESS,
                    COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                	COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION,
                    '307' AS RELATED_PERSON_RELATION_CODE_ATB,
                    '90' AS RELATED_PERSON_ROLE_CODE_ATB,
                    'CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML' AS ROLE_ENTITY -- relation with the entity
                    --'MAND' AS ROLE_ACCOUNT -- Relation to the account
                --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS CUSTOMER
                FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
                LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
                WHERE
                    CUSTOMER.CUSTOMER_CODE = '116344'

2026-01-07 10:21:25,199 - INFO - Data retrieved successfully for RELATED_PERSON_ID 116344
2026-01-07 10:21:25,200 - INFO - Processing row for RELATED_PERSON_ID 43977 with RELATED_PERSON_ROLE 90

Connection closed.
********************************
df_related_third_party_processed
    PM_ID RELATED_PERSON_ID RELATED_PERSON_RELATION RELATED_PERSON_ROLE
0  764564            116344                     309                  90
1  764564            116344                     307                  90
2  764564             43977                     309                  90
********************************
Connection established successfully.
===== in get_PM_related_persons_l2 =====
RELATED_PERSON_RELATION --- RELATED_PERSON_ROLE
309 90
===== in get_PM_related_persons_l2 =====
RELATED_PERSON_RELATION --- RELATED_PERSON_ROLE
307 90
===== in get_PM_related_persons_l2 =====
RELATED_PERSON_RELATION --- RELATED_PERSON_ROLE
309 90

2026-01-07 10:21:25,259 - INFO - Successfully executed query:
                SELECT
                    CUSTOMER_CODE AS CUSTOMER_ID,
                	L_NATURE_CLIENT AS CUSTOMER_TYPE,
                    CASE
                        WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                        WHEN GENDER = 'MALE' THEN 'M'
                        WHEN GENDER = 'FEMALE' THEN 'F'
                    END AS GENDER,
                    GIVEN_NAMES AS FIRST_NAME,
                    FAMILY_NAME AS LAST_NAME,
                    CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                    CASE
					    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					        NULLIF(COUNTRY, ''),
					        NULLIF(CUST_BIRTH_COUNTRY, ''),
					        NULLIF(L_PLACE_OF_BIRT, '')
					    )
					END AS BIRTH_PLACE,
                    LEGAL_DOC_NAME,
                    LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                    LEGAL_ISS_AUTH, --Pays d'émission du passeport
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                    NATIONALITY,
                    RESIDENCE,
                    '1' AS ADDRESS_TYPE,
                    COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                    COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                    COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                    COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
	                --CASE
					--    WHEN COALESCE(COUNTRY, '') = ''
					--         AND COALESCE(TOWN_COUNTRY, '') = ''
					--         AND COALESCE(ADDRESS_ITEM1, '') = ''
					--         AND COALESCE(ADDRESS_ITEM2, '') = ''
					--         AND COALESCE(STREET, '') = ''
					--         AND COALESCE(ADDRESS, '') = ''
					--        THEN 'N.A'
					--    ELSE CONCAT_WS(' - ',
					--         NULLIF(COUNTRY, ''),
					--         NULLIF(TOWN_COUNTRY, ''),
					--         NULLIF(ADDRESS_ITEM1, ''),
					--         NULLIF(ADDRESS_ITEM2, ''),
					--         NULLIF(STREET, ''),
					--         NULLIF(ADDRESS, ''))
					--END AS ADDRESS,
                    COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                	COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION,
                    '309' AS RELATED_PERSON_RELATION_CODE_ATB,
                    '90' AS RELATED_PERSON_ROLE_CODE_ATB,
                    'CUSTOMER_ID : 43977 N.A - ROLE_CODE_goAML' AS ROLE_ENTITY -- relation with the entity
                    --'MAND' AS ROLE_ACCOUNT -- Relation to the account
                --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS CUSTOMER
                FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
                LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
                WHERE
                    CUSTOMER.CUSTOMER_CODE = '43977'

2026-01-07 10:21:25,262 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
                    CUSTOMER_CODE AS CUSTOMER_ID,
                	L_NATURE_CLIENT AS CUSTOMER_TYPE,
                    CASE
                        WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                        WHEN GENDER = 'MALE' THEN 'M'
                        WHEN GENDER = 'FEMALE' THEN 'F'
                    END AS GENDER,
                    GIVEN_NAMES AS FIRST_NAME,
                    FAMILY_NAME AS LAST_NAME,
                    CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                    CASE
					    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					        NULLIF(COUNTRY, ''),
					        NULLIF(CUST_BIRTH_COUNTRY, ''),
					        NULLIF(L_PLACE_OF_BIRT, '')
					    )
					END AS BIRTH_PLACE,
                    LEGAL_DOC_NAME,
                    LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                    LEGAL_ISS_AUTH, --Pays d'émission du passeport
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                    NATIONALITY,
                    RESIDENCE,
                    '1' AS ADDRESS_TYPE,
                    COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                    COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                    COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                    COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
	                --CASE
					--    WHEN COALESCE(COUNTRY, '') = ''
					--         AND COALESCE(TOWN_COUNTRY, '') = ''
					--         AND COALESCE(ADDRESS_ITEM1, '') = ''
					--         AND COALESCE(ADDRESS_ITEM2, '') = ''
					--         AND COALESCE(STREET, '') = ''
					--         AND COALESCE(ADDRESS, '') = ''
					--        THEN 'N.A'
					--    ELSE CONCAT_WS(' - ',
					--         NULLIF(COUNTRY, ''),
					--         NULLIF(TOWN_COUNTRY, ''),
					--         NULLIF(ADDRESS_ITEM1, ''),
					--         NULLIF(ADDRESS_ITEM2, ''),
					--         NULLIF(STREET, ''),
					--         NULLIF(ADDRESS, ''))
					--END AS ADDRESS,
                    COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                	COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION,
                    '309' AS RELATED_PERSON_RELATION_CODE_ATB,
                    '90' AS RELATED_PERSON_ROLE_CODE_ATB,
                    'CUSTOMER_ID : 43977 N.A - ROLE_CODE_goAML' AS ROLE_ENTITY -- relation with the entity
                    --'MAND' AS ROLE_ACCOUNT -- Relation to the account
                --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS CUSTOMER
                FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
                LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
                WHERE
                    CUSTOMER.CUSTOMER_CODE = '43977'

2026-01-07 10:21:25,266 - INFO - Data retrieved successfully for RELATED_PERSON_ID 43977
2026-01-07 10:21:25,267 - INFO - Finished processing all rows for PM-related person details.
2026-01-07 10:21:25,289 - INFO - Executing query to retrieve mandates information for account mandate id : 764564.20230921-1
2026-01-07 10:21:25,317 - INFO - Successfully executed query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = '764564.20230921-1'

2026-01-07 10:21:25,318 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = '764564.20230921-1'

2026-01-07 10:21:25,319 - INFO - Successfully retrieved mandates information for account mandate id : 764564.20230921-1
2026-01-07 10:21:25,332 - INFO - Starting to retrieve PPH data for customer ID 82041
2026-01-07 10:21:25,396 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = '' THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '82041'

2026-01-07 10:21:25,399 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = '' THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '82041'

2026-01-07 10:21:25,402 - INFO - Retrieved PPH data successfully for customer ID 82041

Connection closed.
phase 1
  CUSTOMER_ID CUSTOMER_TYPE GENDER FIRST_NAME   LAST_NAME  \
1      116344           PPH      M   SOUFIENE  BEN HSSINE

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
1  1966-03-11T00:00:00          TN            CIN  03593300             TN

   ... ADDRESS                TOWN        CITY   ZIP COUNTRY_CODE  \
1  ...  BP 454  DJERBA.HOUMET.SOUK  4180 JERBA  4180           TN

                  OCCUPATION RELATED_PERSON_RELATION_CODE_ATB  \
1  Autres employes de bureau                              307

  RELATED_PERSON_ROLE_CODE_ATB                                 ROLE_ENTITY  \
1                           90  CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML

  ROLE_ACCOUNT
1         MAND

[1 rows x 25 columns]
Connection established successfully.
Connection closed.
************ filtered_df_mandates_processed ****************
          MANDATE_ID SIGNATORY_GROUP CUSTOMER_ID START_DATE   END_DATE
0  764564.20230921-1       764564.02       82041 2023-09-21 2100-12-31
1  764564.20230921-1       764564.02       82043 2023-09-21 2100-12-31
Connection established successfully.
Connection closed.
phase 2
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME LAST_NAME            BIRTHDATE  \
0          TRPP       82041      M  ABDELAZIZ  HALLOUMI  1966-01-03T00:00:00

  BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  ... RESIDENCE  \
0          TN            CIN  03594679             TN  ...        TN

  ADDRESS_TYPE       ADDRESS                TOWN CITY   ZIP COUNTRY_CODE  \
0            1  EL MAY JERBA  DJERBA.HOUMET.SOUK  N.A  4180           TN

                 OCCUPATION RELATED_PERSON_ROLE_CODE_ATB ROLE_ENTITY
0  Directeurs d'entreprises                   SIGNATAIRE          RL

[1 rows x 23 columns]
phase 3
df_related_third_party_signatory_g.columns
Index(['CUSTOMER_TYPE', 'CUSTOMER_ID', 'GENDER', 'FIRST_NAME', 'LAST_NAME',
       'BIRTHDATE', 'BIRTH_PLACE', 'LEGAL_DOC_NAME', 'LEGAL_ID',
       'LEGAL_ISS_AUTH', 'LEGAL_ISS_DATE', 'LEGAL_EXP_DATE', 'NATIONALITY',
       'RESIDENCE', 'ADDRESS_TYPE', 'ADDRESS', 'TOWN', 'CITY', 'ZIP',
       'COUNTRY_CODE', 'OCCUPATION', 'RELATED_PERSON_ROLE_CODE_ATB',
       'ROLE_ENTITY'],
      dtype='object')
df_pm_related_persons_details.columns
Index(['CUSTOMER_ID', 'CUSTOMER_TYPE', 'GENDER', 'FIRST_NAME', 'LAST_NAME',
       'BIRTHDATE', 'BIRTH_PLACE', 'LEGAL_DOC_NAME', 'LEGAL_ID',
       'LEGAL_ISS_AUTH', 'LEGAL_ISS_DATE', 'LEGAL_EXP_DATE', 'NATIONALITY',
       'RESIDENCE', 'ADDRESS_TYPE', 'ADDRESS', 'TOWN', 'CITY', 'ZIP',
       'COUNTRY_CODE', 'OCCUPATION', 'RELATED_PERSON_RELATION_CODE_ATB',
       'RELATED_PERSON_ROLE_CODE_ATB', 'ROLE_ENTITY', 'ROLE_ACCOUNT',
       'SOURCE'],
      dtype='object')
phase 4 - concat
df_pm_related_persons_details.columns
Index(['CUSTOMER_ID', 'CUSTOMER_TYPE', 'GENDER', 'FIRST_NAME', 'LAST_NAME',
       'BIRTHDATE', 'BIRTH_PLACE', 'LEGAL_DOC_NAME', 'LEGAL_ID',
       'LEGAL_ISS_AUTH', 'LEGAL_ISS_DATE', 'LEGAL_EXP_DATE', 'NATIONALITY',
       'RESIDENCE', 'ADDRESS_TYPE', 'ADDRESS', 'TOWN', 'CITY', 'ZIP',
       'COUNTRY_CODE', 'OCCUPATION', 'RELATED_PERSON_RELATION_CODE_ATB',
       'RELATED_PERSON_ROLE_CODE_ATB', 'ROLE_ENTITY', 'ROLE_ACCOUNT',
       'SOURCE'],
      dtype='object')
  CUSTOMER_ID CUSTOMER_TYPE GENDER FIRST_NAME   LAST_NAME  \
0      116344           PPH      M   SOUFIENE  BEN HSSINE
1       82041          TRPP      M  ABDELAZIZ    HALLOUMI

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1966-03-11T00:00:00          TN            CIN  03593300             TN
1  1966-01-03T00:00:00          TN            CIN  03594679             TN

   ...                TOWN        CITY   ZIP COUNTRY_CODE  \
0  ...  DJERBA.HOUMET.SOUK  4180 JERBA  4180           TN
1  ...  DJERBA.HOUMET.SOUK         N.A  4180           TN

                  OCCUPATION RELATED_PERSON_RELATION_CODE_ATB  \
0  Autres employes de bureau                              307
1   Directeurs d'entreprises                              NaN

  RELATED_PERSON_ROLE_CODE_ATB                                 ROLE_ENTITY  \
0                           90  CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML
1                   SIGNATAIRE                                          RL

  ROLE_ACCOUNT SOURCE
0         MAND   TIER
1          NaN    SIG

[2 rows x 26 columns]
********************************
BEFORE - df_pm_related_persons_details
(2, 26)
  CUSTOMER_ID CUSTOMER_TYPE GENDER FIRST_NAME   LAST_NAME  \
0      116344           PPH      M   SOUFIENE  BEN HSSINE
1       82041          TRPP      M  ABDELAZIZ    HALLOUMI

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1966-03-11T00:00:00          TN            CIN  03593300             TN
1  1966-01-03T00:00:00          TN            CIN  03594679             TN

   ...                TOWN        CITY   ZIP COUNTRY_CODE  \
0  ...  DJERBA.HOUMET.SOUK  4180 JERBA  4180           TN
1  ...  DJERBA.HOUMET.SOUK         N.A  4180           TN

                  OCCUPATION RELATED_PERSON_RELATION_CODE_ATB  \
0  Autres employes de bureau                              307
1   Directeurs d'entreprises                              NaN

  RELATED_PERSON_ROLE_CODE_ATB                                 ROLE_ENTITY  \
0                           90  CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML
1                   SIGNATAIRE                                          RL

  ROLE_ACCOUNT SOURCE
0         MAND   TIER
1          NaN    SIG

[2 rows x 26 columns]
********************************
======= fct aggregate_legal_id_section ===========
  CUSTOMER_ID CUSTOMER_TYPE GENDER FIRST_NAME   LAST_NAME  \
0      116344           PPH      M   SOUFIENE  BEN HSSINE
1       82041          TRPP      M  ABDELAZIZ    HALLOUMI

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1966-03-11T00:00:00          TN            CIN  03593300             TN
1  1966-01-03T00:00:00          TN            CIN  03594679             TN

   ...        CITY   ZIP COUNTRY_CODE                 OCCUPATION  \
0  ...  4180 JERBA  4180           TN  Autres employes de bureau
1  ...         N.A  4180           TN   Directeurs d'entreprises

  RELATED_PERSON_RELATION_CODE_ATB RELATED_PERSON_ROLE_CODE_ATB  \
0                              307                           90
1                              NaN                   SIGNATAIRE

                                  ROLE_ENTITY ROLE_ACCOUNT SOURCE ACCOUNT_TYPE
0  CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML         MAND   TIER          CPM
1                                          RL          NaN    SIG          CPM

[2 rows x 27 columns]
==================
********************************
AFTER - df_pm_related_persons_details
(2, 23)
  CUSTOMER_ID CUSTOMER_TYPE GENDER FIRST_NAME   LAST_NAME  \
0      116344           PPH      M   SOUFIENE  BEN HSSINE
1       82041          TRPP      M  ABDELAZIZ    HALLOUMI

             BIRTHDATE BIRTH_PLACE NATIONALITY RESIDENCE ADDRESS_TYPE  ...  \
0  1966-03-11T00:00:00          TN          TN        TN            1  ...
1  1966-01-03T00:00:00          TN          TN        TN            1  ...

    ZIP COUNTRY_CODE                 OCCUPATION  \
0  4180           TN  Autres employes de bureau
1  4180           TN   Directeurs d'entreprises

  RELATED_PERSON_RELATION_CODE_ATB RELATED_PERSON_ROLE_CODE_ATB  \
0                              307                           90
1                              N.A                   SIGNATAIRE

                                  ROLE_ENTITY ROLE_ACCOUNT SOURCE  \
0  CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML         MAND   TIER
1                                          RL         MAND    SIG

  ACCOUNT_TYPE                         IDENTIFICATIONS_ID_SECTION
0          CPM  <identification><type>B</type><number>03593300...
1          CPM  <identification><type>B</type><number>03594679...

[2 rows x 23 columns]
********************************
======== 123 ========
Index(['CUSTOMER_ID', 'CUSTOMER_TYPE', 'GENDER', 'FIRST_NAME', 'LAST_NAME',
       'BIRTHDATE', 'BIRTH_PLACE', 'NATIONALITY', 'RESIDENCE', 'ADDRESS_TYPE',
       'ADDRESS', 'TOWN', 'CITY', 'ZIP', 'COUNTRY_CODE', 'OCCUPATION',
       'RELATED_PERSON_RELATION_CODE_ATB', 'RELATED_PERSON_ROLE_CODE_ATB',
       'ROLE_ENTITY', 'ROLE_ACCOUNT', 'SOURCE', 'ACCOUNT_TYPE',
       'IDENTIFICATIONS_ID_SECTION'],
      dtype='object')
  CUSTOMER_ID CUSTOMER_TYPE GENDER FIRST_NAME   LAST_NAME  \
0      116344           PPH      M   SOUFIENE  BEN HSSINE

             BIRTHDATE BIRTH_PLACE NATIONALITY RESIDENCE ADDRESS_TYPE  ...  \
0  1966-03-11T00:00:00          TN          TN        TN            1  ...

    ZIP COUNTRY_CODE                 OCCUPATION  \
0  4180           TN  Autres employes de bureau

  RELATED_PERSON_RELATION_CODE_ATB RELATED_PERSON_ROLE_CODE_ATB  \
0                              307                           90

                                  ROLE_ENTITY ROLE_ACCOUNT SOURCE  \
0  CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML         MAND   TIER

  ACCOUNT_TYPE                         IDENTIFICATIONS_ID_SECTION
0          CPM  <identification><type>B</type><number>03593300...

[1 rows x 23 columns]
+++++++++++++++

In [7]:
account_rp_2

,CUSTOMER_ID,CUSTOMER_TYPE,GENDER,FIRST_NAME,LAST_NAME,BIRTHDATE,BIRTH_PLACE,NATIONALITY,RESIDENCE,ADDRESS_TYPE,...,ZIP,COUNTRY_CODE,OCCUPATION,RELATED_PERSON_RELATION_CODE_ATB,RELATED_PERSON_ROLE_CODE_ATB,ROLE_ENTITY,ROLE_ACCOUNT,SOURCE,ACCOUNT_TYPE,IDENTIFICATIONS_ID_SECTION
0,116344,PPH,M,SOUFIENE,BEN HSSINE,1966-03-11T00:00:00,TN,TN,TN,1,...,4180,TN,Autres employes de bureau,307,90,CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML,MAND,TIER,CPM,<identification><type>B</type><number>03593300...
1,82041,TRPP,M,ABDELAZIZ,HALLOUMI,1966-01-03T00:00:00,TN,TN,TN,1,...,4180,TN,Directeurs d'entreprises,N.A,SIGNATAIRE,RL,MAND,SIG,CPM,<identification><type>B</type><number>03594679...

In [11]:
account_rp_2[account_rp_2['RELATED_PERSON_ROLE_CODE_ATB'] == 'SIGNATAIRE'].iloc[0]

CUSTOMER_ID                                                                     82041
CUSTOMER_TYPE                                                                    TRPP
GENDER                                                                              M
FIRST_NAME                                                                  ABDELAZIZ
LAST_NAME                                                                    HALLOUMI
BIRTHDATE                                                         1966-01-03T00:00:00
BIRTH_PLACE                                                                        TN
NATIONALITY                                                                        TN
RESIDENCE                                                                          TN
ADDRESS_TYPE                                                                        1
ADDRESS                                                                  EL MAY JERBA
TOWN                                                               DJERBA.HOUMET.SOUK
CITY                                                                              N.A
ZIP                                                                              4180
COUNTRY_CODE                                                                       TN
OCCUPATION                                                   Directeurs d'entreprises
RELATED_PERSON_RELATION_CODE_ATB                                                  N.A
RELATED_PERSON_ROLE_CODE_ATB                                               SIGNATAIRE
ROLE_ENTITY                                                                        RL
ROLE_ACCOUNT                                                                     MAND
SOURCE                                                                            SIG
ACCOUNT_TYPE                                                                      CPM
IDENTIFICATIONS_ID_SECTION          <identification><type>B</type><number>03594679...
Name: 1, dtype: object

In [6]:
account = {
    'account_number': account_number,
    'account_correspondences': account_correspondences,
    'account_detail': account_details,
    'customer_id': customer_id,
    'account_type': account_type,
    'account_rp': account_rp
}

In [7]:
transaction_router.get_transactions(account, 2025)

2025-12-30 10:37:27,546 - INFO - Starting to retrieve accountant's transactions for account: 5820061625500, year: 2025

Connection established successfully.

2025-12-30 10:39:44,661 - INFO - Successfully executed query:
            SELECT
                'EQ' AS ACCOUNTANT_SOURCE,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE,
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                ROUND((EQ_ACCOUNTANT.SAAMA * CURRENCIES.C8SPT) ,3) / CURRENCIES.C8PWD AS TRANSACTION_AMOUNT_LCY,
                'NA' AS TRANSACTION_AMOUNT_FCY,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            -- cours de change
            LEFT JOIN [MISDW].[HIST].[EQA_CURRENCIES_2024] AS CURRENCIES ON CURRENCIES.C8CCY = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5820061625500'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2025'

2025-12-30 10:39:44,702 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                'EQ' AS ACCOUNTANT_SOURCE,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE,
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                ROUND((EQ_ACCOUNTANT.SAAMA * CURRENCIES.C8SPT) ,3) / CURRENCIES.C8PWD AS TRANSACTION_AMOUNT_LCY,
                'NA' AS TRANSACTION_AMOUNT_FCY,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            -- cours de change
            LEFT JOIN [MISDW].[HIST].[EQA_CURRENCIES_2024] AS CURRENCIES ON CURRENCIES.C8CCY = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5820061625500'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2025'

2025-12-30 10:39:44,705 - INFO - Query executed successfully. Accountant's transactions retrieved for the account.
2025-12-30 10:39:44,706 - INFO - Closing database connection.
2025-12-30 10:39:44,714 - INFO - Returning cleaned DataFrame.
2025-12-30 10:39:44,714 - INFO - Starting to retrieve T24 accountant's transactions for account: 2010284298, year: 2025

Connection closed.
Connection established successfully.

2025-12-30 10:41:17,667 - INFO - Successfully executed query:
            SELECT
                'T24' AS ACCOUNTANT_SOURCE,
                T24_ACCOUNTANT.SYSTEM_ID AS APP_SOURCE_CODE,
                T24_ACCOUNTANT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                --EQ_T24.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
                'NA' AS EQ_ACCOUNT,
                --EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                'NA' AS ORACLE_ACCOUNT,
                T24_ACCOUNTANT.TRANS_REFERENCE AS TRANSACTION_REF,
                'NA' AS TRANSACTION_SEQ,
                T24_ACCOUNTANT.VALUE_DATE AS TRANSACTION_DATE,
                T24_ACCOUNTANT.SYSTEM_DATE_TIME AS TRANSACTION_DATE_TS,
                T24_ACCOUNTANT.CURRENCY AS TRANSACTION_CURRENCY,
                'NA' AS TRANSACTION_AMOUNT,
                T24_ACCOUNTANT.AMOUNT_LCY AS TRANSACTION_AMOUNT_LCY,
                T24_ACCOUNTANT.AMOUNT_FCY AS TRANSACTION_AMOUNT_FCY,
                T24_ACCOUNTANT.TRANSACTION_CODE AS TRANSACTION_CODE_ATB,
                'NA' AS TRANSACTION_DESC_ATB
            FROM [MISDW].[TRG].[T24_FATB_STMT_ENTRY_2024] AS T24_ACCOUNTANT
            --INNER JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24 ON EQ_T24.GLOBUS_ACCT_NUMBER = T24_ACCOUNTANT.ACCOUNT_NUMBER
            --INNER JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            WHERE
                T24_ACCOUNTANT.ACCOUNT_NUMBER = '2010284298'
                AND SUBSTRING(T24_ACCOUNTANT.VALUE_DATE, 1, 4) = '2025'

2025-12-30 10:41:29,160 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                'T24' AS ACCOUNTANT_SOURCE,
                T24_ACCOUNTANT.SYSTEM_ID AS APP_SOURCE_CODE,
                T24_ACCOUNTANT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                --EQ_T24.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
                'NA' AS EQ_ACCOUNT,
                --EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                'NA' AS ORACLE_ACCOUNT,
                T24_ACCOUNTANT.TRANS_REFERENCE AS TRANSACTION_REF,
                'NA' AS TRANSACTION_SEQ,
                T24_ACCOUNTANT.VALUE_DATE AS TRANSACTION_DATE,
                T24_ACCOUNTANT.SYSTEM_DATE_TIME AS TRANSACTION_DATE_TS,
                T24_ACCOUNTANT.CURRENCY AS TRANSACTION_CURRENCY,
                'NA' AS TRANSACTION_AMOUNT,
                T24_ACCOUNTANT.AMOUNT_LCY AS TRANSACTION_AMOUNT_LCY,
                T24_ACCOUNTANT.AMOUNT_FCY AS TRANSACTION_AMOUNT_FCY,
                T24_ACCOUNTANT.TRANSACTION_CODE AS TRANSACTION_CODE_ATB,
                'NA' AS TRANSACTION_DESC_ATB
            FROM [MISDW].[TRG].[T24_FATB_STMT_ENTRY_2024] AS T24_ACCOUNTANT
            --INNER JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24 ON EQ_T24.GLOBUS_ACCT_NUMBER = T24_ACCOUNTANT.ACCOUNT_NUMBER
            --INNER JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            WHERE
                T24_ACCOUNTANT.ACCOUNT_NUMBER = '2010284298'
                AND SUBSTRING(T24_ACCOUNTANT.VALUE_DATE, 1, 4) = '2025'

2025-12-30 10:41:29,160 - INFO - Query executed successfully. T24 accountant's transactions retrieved for the account.
2025-12-30 10:41:29,176 - INFO - Closing database connection.
2025-12-30 10:41:29,184 - INFO - Returning cleaned DataFrame.

Connection closed.

In [42]:
transaction_router.t24_accountant.accountant_transactions

,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_AMOUNT_LCY,TRANSACTION_AMOUNT_FCY,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB
0,T24,FT,2010284298,NA,NA,FT250700MSK89GKF,NA,20250311,20250311102704119,TND,NA,-280.000,None,8427,NA
1,T24,FT,2010284298,NA,NA,FT250700MSK89GKF,NA,20250311,20250311102742158,TND,NA,280,None,8427,NA
2,T24,FT,2010284298,NA,NA,FT252550PJCXJWYR,NA,20250912,20250912161940144,TND,NA,-100.000,None,8427,NA
3,T24,FT,2010284298,NA,NA,FT2507314N2KN6KS,NA,20250314,20250314131438919,TND,NA,4634.111,None,8544,NA
4,T24,FT,2010284298,NA,NA,FT250700XHL3BQGC,NA,20250311,20250311103411821,TND,NA,-300.000,None,8427,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,T24,FT,2010284298,NA,NA,FT252830WSGW2Z25,NA,20251010,20251010170330524,TND,NA,-54.234,None,8439,NA
195,T24,FT,2010284298,NA,NA,FT2525501T4DGCPF,NA,20250912,20250912161853667,TND,NA,-100.000,None,8427,NA
196,T24,FT,2010284298,NA,NA,FT252690CGVZX7YJ,NA,20250926,20250926173841708,TND,NA,2739.113,None,8512,NA
197,T24,FT,2010284298,NA,NA,FT252810JN50656F,NA,20251008,20251008133129981,TND,NA,-200.000,None,8427,NA
198,T24,FT,2010284298,NA,NA,FT253560XH6L3B3L,NA,20251222,20251221104758057,TND,NA,-600.000,None,8439,NA

In [7]:
transaction_router.eq_accountant.accountant_transactions

Empty DataFrame
Columns: []
Index: []

In [40]:
transaction_router.unified_accountant[
    transaction_router.unified_accountant['ACCOUNTANT_SOURCE'] == 'EQ'
]

Empty DataFrame
Columns: [ACCOUNTANT_SOURCE, APP_SOURCE_CODE, T24_ACCOUNT, EQ_ACCOUNT, ORACLE_ACCOUNT, TRANSACTION_REF, TRANSACTION_SEQ, TRANSACTION_DATE, TRANSACTION_DATE_TS, TRANSACTION_CURRENCY, TRANSACTION_AMOUNT, TRANSACTION_AMOUNT_LCY, TRANSACTION_AMOUNT_FCY, TRANSACTION_CODE_ATB, TRANSACTION_DESC_ATB]
Index: []

In [9]:
accountant = transaction_router.unified_accountant.copy()
trx_code = transaction_router.transaction_code.copy()

In [22]:
accountant.dtypes

ACCOUNTANT_SOURCE         object
APP_SOURCE_CODE           object
T24_ACCOUNT               object
EQ_ACCOUNT                object
ORACLE_ACCOUNT            object
TRANSACTION_REF           object
TRANSACTION_SEQ           object
TRANSACTION_DATE          object
TRANSACTION_DATE_TS       object
TRANSACTION_CURRENCY      object
TRANSACTION_AMOUNT        object
TRANSACTION_AMOUNT_LCY    object
TRANSACTION_AMOUNT_FCY    object
TRANSACTION_CODE_ATB      object
TRANSACTION_DESC_ATB      object
dtype: object

In [23]:
trx_code.dtypes

ACCOUNTANT_SOURCE           object
APP_SOURCE_CODE             object
TRANSACTION_CODE_ATB        object
TRANSACTION_DESC_ATB        object
APP_SOURCE                  object
OP_TYPE                     object
Categorie_de_transaction    object
TRANSACTION_CODE_GOAML      object
TRANSACTION_DESC_GOAML      object
FUND_CODE_1                 object
FUND_CODE_2                 object
IS_INTERFACE                object
IS_MANUELLE                 object
dtype: object

In [14]:
trx_code.duplicated(
    subset=['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB']
).any()

True

In [18]:
trx_code[trx_code.duplicated(subset=['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB'], keep=False)]

,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,IS_INTERFACE,IS_MANUELLE
1257,EQ,AABS5,410,Branch Settle - Due From,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1424,EQ,AABS5,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1438,EQ,AABS2,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2676,EQ,AABS5,410,Branch Settle - Due From,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2916,EQ,AABS5,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2940,EQ,AABS2,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
trx_code.groupby(['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB']).size().reset_index(name='cnt').query('cnt != 1')

    ACCOUNTANT_SOURCE APP_SOURCE_CODE TRANSACTION_CODE_ATB  cnt
506                EQ           AABS2                  910    2
511                EQ           AABS5                  410    2
512                EQ           AABS5                  910    2

In [27]:
trx_code[
    ['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB']
].isna().sum()

ACCOUNTANT_SOURCE        0
APP_SOURCE_CODE         14
TRANSACTION_CODE_ATB     0
dtype: int64

In [29]:
trx_code.describe()

,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,IS_INTERFACE,IS_MANUELLE
count,4027,4013,4027,4026,659,629,615,180,161,180,180,401,7
unique,2,566,738,431,10,13,3,18,17,3,3,2,1
top,EQ,TT,510,Credit,Teller,Caisse,code affectant directement le compte client (d...,B108,Paiement par cartes électroniques locales,A,A,N,Y
freq,3765,262,283,297,378,411,302,20,20,117,94,285,7