In [1]:
import sys
sys.path.append('../')

In [2]:
from src.config import DB_CONFIG, TREANSACTION_CODE

In [3]:
from src.model.get_client_T24 import GetClientT24

In [4]:
get_client_T24 = GetClientT24(DB_CONFIG)

In [5]:
account_number = '5812273189500'
print(get_client_T24.account_status_lookup(account_number)) # True -> Active Account

account_correspondences, account_details, customer_id, account_type, account_rp = get_client_T24.get_client(account_number)

2025-04-28 13:18:47,542 - INFO - Executing account status lookup for account: 5812273189500

Connection established successfully.

2025-04-28 13:18:47,763 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5812273189500'

2025-04-28 13:18:47,764 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5812273189500'

2025-04-28 13:18:47,765 - INFO - Account 5812273189500 is IS_ACTIVE
2025-04-28 13:18:47,867 - INFO - Executing account status lookup for account: 5812273189500
2025-04-28 13:18:47,996 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5812273189500'

2025-04-28 13:18:47,997 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5812273189500'

2025-04-28 13:18:47,999 - INFO - Account 5812273189500 is IS_ACTIVE

Connection closed.
True
Connection established successfully.

2025-04-28 13:18:48,155 - INFO - Executing query to retrieve account information for account number: 5812273189500

Connection closed.
Connection established successfully.

2025-04-28 13:18:51,344 - INFO - Successfully executed query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5812273189500'

2025-04-28 13:18:51,346 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5812273189500'

2025-04-28 13:18:51,351 - INFO - Successfully retrieved account information for account number: 5812273189500
2025-04-28 13:18:51,645 - INFO - Executing query to retrieve arrangement information for arrangement id : AA22101SFS0P

Connection closed.
Connection established successfully.

2025-04-28 13:18:53,115 - INFO - Successfully executed query:
        SELECT
            LEFT(RECID, CHARINDEX('-', RECID) - 1) AS ARRANGEMENT_ID,
            CUSTOMER_3,
            CUSTOMER_ROLE_4,
            L_ACCT_TYPE
        FROM [MISDW].[GO_AML].[T24_FATB_AA_ARR_CUSTOMER]
        WHERE
            LEFT(RECID, CHARINDEX('-', RECID) - 1) = 'AA22101SFS0P'

2025-04-28 13:18:53,117 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            LEFT(RECID, CHARINDEX('-', RECID) - 1) AS ARRANGEMENT_ID,
            CUSTOMER_3,
            CUSTOMER_ROLE_4,
            L_ACCT_TYPE
        FROM [MISDW].[GO_AML].[T24_FATB_AA_ARR_CUSTOMER]
        WHERE
            LEFT(RECID, CHARINDEX('-', RECID) - 1) = 'AA22101SFS0P'

2025-04-28 13:18:53,119 - INFO - Successfully retrieved account information for arrangement id : AA22101SFS0P
2025-04-28 13:18:53,156 - INFO - Starting to retrieve PPH data for customer ID 273189

Connection closed.
  ARRANGEMENT_ID CUSTOMER_ID CUSTOMER_ROLE L_ACCT_TYPE
0   AA22101SFS0P      273189         OWNER           3
The DataFrame has only one record, and CUSTOMER_ROLE is OWNER.
Connection established successfully.

2025-04-28 13:18:53,449 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '273189'

2025-04-28 13:18:53,452 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '273189'

2025-04-28 13:18:53,457 - INFO - Retrieved PPH data successfully for customer ID 273189
2025-04-28 13:18:53,503 - INFO - Executing query to retrieve mandates information for account mandate id : None
2025-04-28 13:18:53,616 - INFO - Successfully executed query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = 'None'

2025-04-28 13:18:53,618 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = 'None'

Connection closed.
Connection established successfully.

2025-04-28 13:18:58,621 - WARNING - Failed to execute query after 1 attempts
2025-04-28 13:18:58,624 - WARNING - No data found for account mandate id : None

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME   LAST_NAME  \
0           PPH      273189      M      LOTFI  BEN FARHAT

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1969-11-14T00:00:00  TN - Tunis            CIN  05146654             TN

        LEGAL_ISS_DATE LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  2011-04-20T00:00:00           None          TN        TN            1

    ZIP                                            ADDRESS COUNTRY_CODE  \
0  2066  TN - TUNIS - EL.KABARIA - BLOC B6 APPRT 145 RE...           TN

                                   OCCUPATION ROLE_ACCOUNT
0  Dirigeants et gerants non classes ailleurs        TICPT
==================
+++++++++++++++

In [6]:
account = {
    'account_number': account_number,
    'account_correspondences': account_correspondences,
    'account_detail': account_details,
    'customer_id': customer_id,
    'account_type': account_type,
    'account_rp': account_rp
}

In [7]:
from src.controller.transaction_router import TransactionRouter

In [8]:
transaction_router = TransactionRouter(TREANSACTION_CODE, DB_CONFIG)

2025-04-28 13:19:27,768 - INFO - Transaction codes loaded successfully.
2025-04-28 13:19:27,770 - INFO - EQAccountant initialized with logging enabled: True

Index(['APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB', 'TRANSACTION_DESC_ATB',
       'APP_SOURCE', 'OP_TYPE', 'Categorie_de_transaction',
       'TRANSACTION_CODE_GOAML', 'TRANSACTION_DESC_GOAML', 'FUND_CODE_1',
       'FUND_CODE_2', '_merge'],
      dtype='object')

In [9]:
year = '2023'
transaction_router.clear_cash()
transaction_router.get_transactions(account, year)

2025-04-28 13:19:34,685 - INFO - Starting to retrieve accountant's transactions for account: 5812273189500, year: 2023

Connection established successfully.

2025-04-28 13:19:37,279 - INFO - Successfully executed query:
            SELECT
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5812273189500'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2023'

2025-04-28 13:21:53,740 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5812273189500'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2023'

2025-04-28 13:21:53,750 - INFO - Query executed successfully. Accountant's transactions retrieved for the account.
2025-04-28 13:21:53,752 - INFO - Closing database connection.
2025-04-28 13:21:53,777 - INFO - Returning cleaned DataFrame.
2025-04-28 13:21:53,838 - INFO - Starting cashier's transactions retrieval for account: 5812273189500, year: 2023
2025-04-28 13:21:53,844 - INFO - Executing query for account: 5812273189500, year: 2023

Connection closed.
============*********==============
Index(['T24_ACCOUNT', 'EQ_ACCOUNT', 'ORACLE_ACCOUNT', 'TRANSACTION_REF',
       'TRANSACTION_SEQ', 'TRANSACTION_DATE', 'TRANSACTION_DATE_TS',
       'TRANSACTION_CURRENCY', 'TRANSACTION_AMOUNT', 'TRANSACTION_CODE_ATB',
       'TRANSACTION_DESC_ATB_ACC', 'APP_SOURCE_CODE', 'TRANSACTION_DESC_ATB_F',
       'APP_SOURCE', 'OP_TYPE', 'Categorie_de_transaction',
       'TRANSACTION_DESC_GOAML', 'TRANSACTION_CODE_GOAML', 'FUND_CODE_1',
       'FUND_CODE_2'],
      dtype='object')
===============================
Fetch Cashier Trx
(177, 20)
(177, 20)
===============================
Connection established successfully.

2025-04-28 13:22:18,953 - INFO - Successfully executed query:
        SELECT
            TRIM(CAST(CASHIER.PWABX AS VARCHAR) + CAST(CASHIER.PWANX AS VARCHAR) + CAST(CASHIER.PWASX AS VARCHAR)) AS EQ_ACCOUNT,
            TRIM(CAST(CASHIER.PWDRFX AS VARCHAR)) AS TRANSACTION_REF,
            TRIM(CAST(CASHIER.PWDATEX AS VARCHAR)) AS TRANSACTION_DATE,

            CASHIER.PWCCYX AS CURRENCY_CODE_1,
            FORMAT(CASHIER.PWAMTX / POWER(10, CURRENCY_1.NO_OF_DECIMALS), '0.##################') AS FOREIGN_AMOUNT_1,
            'TN' AS COUNTRY_1,

            CASE
                WHEN CASHIER.PWCCY2X IS NULL OR LTRIM(RTRIM(CASHIER.PWCCY2X)) = '' THEN CASHIER.PWCCYX
                ELSE CASHIER.PWCCY2X
            END AS CURRENCY_CODE_2,
            CASE
            	WHEN CASHIER.PWAMT2X IS NOT NULL AND CASHIER.PWAMT2X <> 0 THEN FORMAT(CASHIER.PWAMT2X / POWER(10,
	            	CASE
	            		WHEN CURRENCY_2.NO_OF_DECIMALS IS NOT NULL AND CURRENCY_2.NO_OF_DECIMALS <> '' THEN CURRENCY_2.NO_OF_DECIMALS
	            		ELSE CURRENCY_1.NO_OF_DECIMALS
	            	END
            	), '0.##################')
            	ELSE FORMAT(CASHIER.PWAMTX / POWER(10, CURRENCY_1.NO_OF_DECIMALS), '0.##################')
            END AS FOREIGN_AMOUNT_2,
            'TN' AS COUNTRY_2,

            CASE
                WHEN CASHIER.PWCCYX = 'TND' THEN FORMAT(CASHIER.PWAMTX / POWER(10, CURRENCY_1.NO_OF_DECIMALS), '0.##################')
				WHEN CASHIER.PWCCY2X = 'TND' THEN FORMAT(CASHIER.PWAMT2X / POWER(10, CURRENCY_1.NO_OF_DECIMALS), '0.##################')
                ELSE FORMAT(CASHIER.PWAMTX / POWER(10, CURRENCY_1.NO_OF_DECIMALS) * CURRENCY_1.MID_REVAL_RATE, '0.##################')
            END AS AMOUNT_LOCAL,

            '30' + '/' + TRIM(CASHIER.PWDRFX) + '/' + '20' + SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 2, 2) + ' ' +
            SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 4, 2) + ' ' + SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 6, 2) + 'T00:00:00' AS TRANSACTION_NUMBER,
            '20' + SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 2, 2) + '-' +
            SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 4, 2) + '-' + SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 6, 2) + 'T00:00:00' AS DATE_TRANSACTION,
            BRANCH.NAME AS TRANSACTION_LOCATION,
            'C' AS TRANSACTION_STATUS_CODE,
            CASE
                WHEN TRIM(CASHIER.PWNRX) + TRIM(CASHIER.PWNR2X) + TRIM(CASHIER.PWNR3X) = '' THEN 'N.A'
                ELSE TRIM(CASHIER.PWNRX) + TRIM(CASHIER.PWNR2X) + TRIM(CASHIER.PWNR3X)
            END AS NAR,

            'Cashier' AS SOURCE

        FROM [MISDW].[HIST].[EQA_CASHIER] AS CASHIER
        LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY_1 ON CURRENCY_1.CURRENCY_CODE = CASHIER.PWCCYX
        LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY_2 ON CURRENCY_2.CURRENCY_CODE = CASHIER.PWCCY2X
        LEFT JOIN [MISDW].[TRG].[T24_F_DEPT_ACCT_OFFICER] AS BRANCH ON BRANCH.ACCOUNT_OFFICER = CASHIER.PWBBNX
        WHERE
            TRIM(CAST(CASHIER.PWABX AS VARCHAR) + CAST(CASHIER.PWANX AS VARCHAR) + CAST(CASHIER.PWASX AS VARCHAR)) = '5812273189500'
            AND '20' + SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 2, 2) = '2023'

2025-04-28 13:22:18,958 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            TRIM(CAST(CASHIER.PWABX AS VARCHAR) + CAST(CASHIER.PWANX AS VARCHAR) + CAST(CASHIER.PWASX AS VARCHAR)) AS EQ_ACCOUNT,
            TRIM(CAST(CASHIER.PWDRFX AS VARCHAR)) AS TRANSACTION_REF,
            TRIM(CAST(CASHIER.PWDATEX AS VARCHAR)) AS TRANSACTION_DATE,

            CASHIER.PWCCYX AS CURRENCY_CODE_1,
            FORMAT(CASHIER.PWAMTX / POWER(10, CURRENCY_1.NO_OF_DECIMALS), '0.##################') AS FOREIGN_AMOUNT_1,
            'TN' AS COUNTRY_1,

            CASE
                WHEN CASHIER.PWCCY2X IS NULL OR LTRIM(RTRIM(CASHIER.PWCCY2X)) = '' THEN CASHIER.PWCCYX
                ELSE CASHIER.PWCCY2X
            END AS CURRENCY_CODE_2,
            CASE
            	WHEN CASHIER.PWAMT2X IS NOT NULL AND CASHIER.PWAMT2X <> 0 THEN FORMAT(CASHIER.PWAMT2X / POWER(10,
	            	CASE
	            		WHEN CURRENCY_2.NO_OF_DECIMALS IS NOT NULL AND CURRENCY_2.NO_OF_DECIMALS <> '' THEN CURRENCY_2.NO_OF_DECIMALS
	            		ELSE CURRENCY_1.NO_OF_DECIMALS
	            	END
            	), '0.##################')
            	ELSE FORMAT(CASHIER.PWAMTX / POWER(10, CURRENCY_1.NO_OF_DECIMALS), '0.##################')
            END AS FOREIGN_AMOUNT_2,
            'TN' AS COUNTRY_2,

            CASE
                WHEN CASHIER.PWCCYX = 'TND' THEN FORMAT(CASHIER.PWAMTX / POWER(10, CURRENCY_1.NO_OF_DECIMALS), '0.##################')
				WHEN CASHIER.PWCCY2X = 'TND' THEN FORMAT(CASHIER.PWAMT2X / POWER(10, CURRENCY_1.NO_OF_DECIMALS), '0.##################')
                ELSE FORMAT(CASHIER.PWAMTX / POWER(10, CURRENCY_1.NO_OF_DECIMALS) * CURRENCY_1.MID_REVAL_RATE, '0.##################')
            END AS AMOUNT_LOCAL,

            '30' + '/' + TRIM(CASHIER.PWDRFX) + '/' + '20' + SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 2, 2) + ' ' +
            SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 4, 2) + ' ' + SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 6, 2) + 'T00:00:00' AS TRANSACTION_NUMBER,
            '20' + SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 2, 2) + '-' +
            SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 4, 2) + '-' + SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 6, 2) + 'T00:00:00' AS DATE_TRANSACTION,
            BRANCH.NAME AS TRANSACTION_LOCATION,
            'C' AS TRANSACTION_STATUS_CODE,
            CASE
                WHEN TRIM(CASHIER.PWNRX) + TRIM(CASHIER.PWNR2X) + TRIM(CASHIER.PWNR3X) = '' THEN 'N.A'
                ELSE TRIM(CASHIER.PWNRX) + TRIM(CASHIER.PWNR2X) + TRIM(CASHIER.PWNR3X)
            END AS NAR,

            'Cashier' AS SOURCE

        FROM [MISDW].[HIST].[EQA_CASHIER] AS CASHIER
        LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY_1 ON CURRENCY_1.CURRENCY_CODE = CASHIER.PWCCYX
        LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY_2 ON CURRENCY_2.CURRENCY_CODE = CASHIER.PWCCY2X
        LEFT JOIN [MISDW].[TRG].[T24_F_DEPT_ACCT_OFFICER] AS BRANCH ON BRANCH.ACCOUNT_OFFICER = CASHIER.PWBBNX
        WHERE
            TRIM(CAST(CASHIER.PWABX AS VARCHAR) + CAST(CASHIER.PWANX AS VARCHAR) + CAST(CASHIER.PWASX AS VARCHAR)) = '5812273189500'
            AND '20' + SUBSTRING(CONVERT(VARCHAR, CASHIER.PWDATEX), 2, 2) = '2023'

2025-04-28 13:22:23,961 - WARNING - Failed to execute query after 1 attempts
2025-04-28 13:22:23,964 - WARNING - No cashier's transactions data found for the account: 5812273189500, year: 2023
2025-04-28 13:22:23,980 - INFO - Database connection closed.
2025-04-28 13:22:23,982 - INFO - Cleaning and returning the retrieved DataFrame.
2025-04-28 13:22:23,994 - INFO - Starting Teller's transactions retrieval for account: 2002611131, year: 2023
2025-04-28 13:22:24,001 - INFO - Executing query with max_attempts: 1

Connection closed.
===============================
Fetch Teller Trx
(12, 20)
(12, 20)
===============================
Connection established successfully.

2025-04-28 13:22:51,551 - INFO - Successfully executed query:
            SELECT
                TELLER_HIS.ACCOUNT_2 AS T24_ACCOUNT,
                TELLER_HIS.HISTORY_ID AS TRANSACTION_REF,
                SUBSTRING(TELLER_HIS.VALUE_DATE_1, 3, LEN(TELLER_HIS.VALUE_DATE_1) - 2) AS TRANSACTION_DATE,

                -- Account (currency, amount)
                CASE
                    WHEN TELLER_HIS.CURRENCY_2 = 'TND' OR TELLER_HIS.CURRENCY_2 = 'TDC' THEN 'TND'
                    ELSE TELLER_HIS.CURRENCY_2
                END AS CURRENCY_CODE_1,
                'TN' AS COUNTRY_1,
                CASE
                    WHEN TELLER_HIS.CURRENCY_2 = 'TND' THEN TELLER_HIS.AMOUNT_LOCAL_2
                    WHEN TELLER_HIS.CURRENCY_2 <> 'TND' THEN TELLER_HIS.AMOUNT_FCY_2 --TDC
                END AS FOREIGN_AMOUNT_1,

                TELLER_HIS.L_ORDONATEUR,
                TELLER_HIS.L_TIERS_NUMID,

                TELLER_HIS.CURRENCY_1 AS CURRENCY_CODE_2,
                'TN' AS COUNTRY_2,
                CASE
                    WHEN TELLER_HIS.CURRENCY_1 = 'TND' THEN TELLER_HIS.AMOUNT_LOCAL_1
                    WHEN TELLER_HIS.CURRENCY_1 <> 'TND' THEN TELLER_HIS.AMOUNT_FCY_1
                END AS FOREIGN_AMOUNT_2,

                BRANCH.NAME AS TRANSACTION_LOCATION,
                CASE
                    WHEN TELLER_HIS.VALUE_DATE_1 = 0 OR TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1) IS NULL THEN '30/0000/00 00 0000'
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))) = 1 THEN
                        '30/' + TELLER_HIS.TRANSACTION_NUMBER + '/' +
                        RIGHT('0' + CONVERT(VARCHAR(2), DAY(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))), 23))), 2) + ' ' +
                        RIGHT('0' + CONVERT(VARCHAR(2), MONTH(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))), 23))), 2) + ' ' +
                        CONVERT(VARCHAR(4), YEAR(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))), 23)))
                    ELSE NULL
                END AS TRANSACTION_NUMBER,
                CASE
                    WHEN TELLER_HIS.VALUE_DATE_1 = 0 THEN '0000-00-00T00:00:00'
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))), 23) + 'T00:00:00'
                    ELSE NULL
                END AS DATE_TRANSACTION,
                TELLER_HIS.AMOUNT_LOCAL_2 AS AMOUNT_LOCAL,
                'C' AS TRANSACTION_STATUS_CODE,
                TELLER_HIS.L_TIERS_NOM + ' - ' + TELLER_HIS.L_TIERS_NUMID AS NAR,
                'TELLER_HIS' AS SOURCE
            FROM [MISDW].[TRG].[T24_FATB_TELLER#HIS] AS TELLER_HIS
            LEFT JOIN [MISDW].[TRG].[T24_F_DEPT_ACCT_OFFICER] AS BRANCH ON BRANCH.ACCOUNT_OFFICER = TELLER_HIS.DEPT_CODE
            WHERE
                TELLER_HIS.RECORD_STATUS = 'MAT'
                AND TELLER_HIS.ACCOUNT_2 = '2002611131'
                AND CASE
                        WHEN TELLER_HIS.VALUE_DATE_1 = 0 OR TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1) IS NULL THEN 0
                        ELSE YEAR(CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))))
                    END = '2023'

            UNION

            SELECT
                TELLER_BBE.ACCOUNT_2 AS T24_ACCOUNT,
                TELLER_BBE.HISTORY_ID AS TRANSACTION_REF,
                SUBSTRING(TELLER_BBE.VALUE_DATE_1, 3, LEN(TELLER_BBE.VALUE_DATE_1) - 2) AS TRANSACTION_DATE,


                -- Account (currency, amount)
                CASE
                    WHEN TELLER_BBE.CURRENCY_2 = 'TND' OR TELLER_BBE.CURRENCY_2 = 'TDC' THEN 'TND'
                    ELSE TELLER_BBE.CURRENCY_2
                END AS CURRENCY_CODE_1,
                'TN' AS COUNTRY_1,
                CASE
                    WHEN TELLER_BBE.CURRENCY_2 = 'TND' THEN TELLER_BBE.AMOUNT_LOCAL_2
                    WHEN TELLER_BBE.CURRENCY_2 <> 'TND' THEN TELLER_BBE.AMOUNT_FCY_2 --TDC
                END AS FOREIGN_AMOUNT_1,

                TELLER_BBE.L_ORDONATEUR,
                TELLER_BBE.L_TIERS_NUMID,

                TELLER_BBE.CURRENCY_1 AS CURRENCY_CODE_2,
                'TN' AS COUNTRY_2,
                CASE
                    WHEN TELLER_BBE.CURRENCY_1 = 'TND' THEN TELLER_BBE.AMOUNT_LOCAL_1
                    WHEN TELLER_BBE.CURRENCY_1 <> 'TND' THEN TELLER_BBE.AMOUNT_FCY_1
                END AS FOREIGN_AMOUNT_2,

                BRANCH.NAME AS TRANSACTION_LOCATION,
                CASE
                    WHEN TELLER_BBE.VALUE_DATE_1 = 0 OR TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1) IS NULL THEN '30/0000/00 00 0000'
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))) = 1 THEN
                        '30/' + TELLER_BBE.TRANSACTION_NUMBER + '/' +
                        RIGHT('0' + CONVERT(VARCHAR(2), DAY(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))), 23))), 2) + ' ' +
                        RIGHT('0' + CONVERT(VARCHAR(2), MONTH(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))), 23))), 2) + ' ' +
                        CONVERT(VARCHAR(4), YEAR(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))), 23)))
                    ELSE NULL
                END AS TRANSACTION_NUMBER,
                CASE
                    WHEN TELLER_BBE.VALUE_DATE_1 = 0 THEN '0000-00-00T00:00:00'
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))), 23) + 'T00:00:00'
                    ELSE NULL
                END AS DATE_TRANSACTION,
                TELLER_BBE.AMOUNT_LOCAL_2 AS AMOUNT_LOCAL,
                'C' AS TRANSACTION_STATUS_CODE,
                TELLER_BBE.L_TIERS_NOM + ' - ' + TELLER_BBE.L_TIERS_NUMID AS NAR,
                'TELLER_BBE' AS SOURCE
            FROM [MISDW].[TRG].[T24_FATB_TELLER_BBE] AS TELLER_BBE
            LEFT JOIN [MISDW].[TRG].[T24_F_DEPT_ACCT_OFFICER] AS BRANCH ON BRANCH.ACCOUNT_OFFICER = TELLER_BBE.DEPT_CODE
            WHERE
                TELLER_BBE.RECORD_STATUS = 'MAT'
                AND TELLER_BBE.ACCOUNT_2 = '2002611131'
                AND CASE
                        WHEN TELLER_BBE.VALUE_DATE_1 = 0 OR TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1) IS NULL THEN 0
                        ELSE YEAR(CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))))
                    END = '2023'

2025-04-28 13:22:51,553 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                TELLER_HIS.ACCOUNT_2 AS T24_ACCOUNT,
                TELLER_HIS.HISTORY_ID AS TRANSACTION_REF,
                SUBSTRING(TELLER_HIS.VALUE_DATE_1, 3, LEN(TELLER_HIS.VALUE_DATE_1) - 2) AS TRANSACTION_DATE,

                -- Account (currency, amount)
                CASE
                    WHEN TELLER_HIS.CURRENCY_2 = 'TND' OR TELLER_HIS.CURRENCY_2 = 'TDC' THEN 'TND'
                    ELSE TELLER_HIS.CURRENCY_2
                END AS CURRENCY_CODE_1,
                'TN' AS COUNTRY_1,
                CASE
                    WHEN TELLER_HIS.CURRENCY_2 = 'TND' THEN TELLER_HIS.AMOUNT_LOCAL_2
                    WHEN TELLER_HIS.CURRENCY_2 <> 'TND' THEN TELLER_HIS.AMOUNT_FCY_2 --TDC
                END AS FOREIGN_AMOUNT_1,

                TELLER_HIS.L_ORDONATEUR,
                TELLER_HIS.L_TIERS_NUMID,

                TELLER_HIS.CURRENCY_1 AS CURRENCY_CODE_2,
                'TN' AS COUNTRY_2,
                CASE
                    WHEN TELLER_HIS.CURRENCY_1 = 'TND' THEN TELLER_HIS.AMOUNT_LOCAL_1
                    WHEN TELLER_HIS.CURRENCY_1 <> 'TND' THEN TELLER_HIS.AMOUNT_FCY_1
                END AS FOREIGN_AMOUNT_2,

                BRANCH.NAME AS TRANSACTION_LOCATION,
                CASE
                    WHEN TELLER_HIS.VALUE_DATE_1 = 0 OR TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1) IS NULL THEN '30/0000/00 00 0000'
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))) = 1 THEN
                        '30/' + TELLER_HIS.TRANSACTION_NUMBER + '/' +
                        RIGHT('0' + CONVERT(VARCHAR(2), DAY(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))), 23))), 2) + ' ' +
                        RIGHT('0' + CONVERT(VARCHAR(2), MONTH(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))), 23))), 2) + ' ' +
                        CONVERT(VARCHAR(4), YEAR(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))), 23)))
                    ELSE NULL
                END AS TRANSACTION_NUMBER,
                CASE
                    WHEN TELLER_HIS.VALUE_DATE_1 = 0 THEN '0000-00-00T00:00:00'
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))), 23) + 'T00:00:00'
                    ELSE NULL
                END AS DATE_TRANSACTION,
                TELLER_HIS.AMOUNT_LOCAL_2 AS AMOUNT_LOCAL,
                'C' AS TRANSACTION_STATUS_CODE,
                TELLER_HIS.L_TIERS_NOM + ' - ' + TELLER_HIS.L_TIERS_NUMID AS NAR,
                'TELLER_HIS' AS SOURCE
            FROM [MISDW].[TRG].[T24_FATB_TELLER#HIS] AS TELLER_HIS
            LEFT JOIN [MISDW].[TRG].[T24_F_DEPT_ACCT_OFFICER] AS BRANCH ON BRANCH.ACCOUNT_OFFICER = TELLER_HIS.DEPT_CODE
            WHERE
                TELLER_HIS.RECORD_STATUS = 'MAT'
                AND TELLER_HIS.ACCOUNT_2 = '2002611131'
                AND CASE
                        WHEN TELLER_HIS.VALUE_DATE_1 = 0 OR TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1) IS NULL THEN 0
                        ELSE YEAR(CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_HIS.VALUE_DATE_1))))
                    END = '2023'

            UNION

            SELECT
                TELLER_BBE.ACCOUNT_2 AS T24_ACCOUNT,
                TELLER_BBE.HISTORY_ID AS TRANSACTION_REF,
                SUBSTRING(TELLER_BBE.VALUE_DATE_1, 3, LEN(TELLER_BBE.VALUE_DATE_1) - 2) AS TRANSACTION_DATE,


                -- Account (currency, amount)
                CASE
                    WHEN TELLER_BBE.CURRENCY_2 = 'TND' OR TELLER_BBE.CURRENCY_2 = 'TDC' THEN 'TND'
                    ELSE TELLER_BBE.CURRENCY_2
                END AS CURRENCY_CODE_1,
                'TN' AS COUNTRY_1,
                CASE
                    WHEN TELLER_BBE.CURRENCY_2 = 'TND' THEN TELLER_BBE.AMOUNT_LOCAL_2
                    WHEN TELLER_BBE.CURRENCY_2 <> 'TND' THEN TELLER_BBE.AMOUNT_FCY_2 --TDC
                END AS FOREIGN_AMOUNT_1,

                TELLER_BBE.L_ORDONATEUR,
                TELLER_BBE.L_TIERS_NUMID,

                TELLER_BBE.CURRENCY_1 AS CURRENCY_CODE_2,
                'TN' AS COUNTRY_2,
                CASE
                    WHEN TELLER_BBE.CURRENCY_1 = 'TND' THEN TELLER_BBE.AMOUNT_LOCAL_1
                    WHEN TELLER_BBE.CURRENCY_1 <> 'TND' THEN TELLER_BBE.AMOUNT_FCY_1
                END AS FOREIGN_AMOUNT_2,

                BRANCH.NAME AS TRANSACTION_LOCATION,
                CASE
                    WHEN TELLER_BBE.VALUE_DATE_1 = 0 OR TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1) IS NULL THEN '30/0000/00 00 0000'
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))) = 1 THEN
                        '30/' + TELLER_BBE.TRANSACTION_NUMBER + '/' +
                        RIGHT('0' + CONVERT(VARCHAR(2), DAY(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))), 23))), 2) + ' ' +
                        RIGHT('0' + CONVERT(VARCHAR(2), MONTH(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))), 23))), 2) + ' ' +
                        CONVERT(VARCHAR(4), YEAR(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))), 23)))
                    ELSE NULL
                END AS TRANSACTION_NUMBER,
                CASE
                    WHEN TELLER_BBE.VALUE_DATE_1 = 0 THEN '0000-00-00T00:00:00'
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))), 23) + 'T00:00:00'
                    ELSE NULL
                END AS DATE_TRANSACTION,
                TELLER_BBE.AMOUNT_LOCAL_2 AS AMOUNT_LOCAL,
                'C' AS TRANSACTION_STATUS_CODE,
                TELLER_BBE.L_TIERS_NOM + ' - ' + TELLER_BBE.L_TIERS_NUMID AS NAR,
                'TELLER_BBE' AS SOURCE
            FROM [MISDW].[TRG].[T24_FATB_TELLER_BBE] AS TELLER_BBE
            LEFT JOIN [MISDW].[TRG].[T24_F_DEPT_ACCT_OFFICER] AS BRANCH ON BRANCH.ACCOUNT_OFFICER = TELLER_BBE.DEPT_CODE
            WHERE
                TELLER_BBE.RECORD_STATUS = 'MAT'
                AND TELLER_BBE.ACCOUNT_2 = '2002611131'
                AND CASE
                        WHEN TELLER_BBE.VALUE_DATE_1 = 0 OR TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1) IS NULL THEN 0
                        ELSE YEAR(CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TELLER_BBE.VALUE_DATE_1))))
                    END = '2023'

2025-04-28 13:22:51,560 - INFO - Query executed successfully; Teller's transactions data retrieved for the account.
2025-04-28 13:22:51,561 - INFO - Closing database connection.
2025-04-28 13:22:51,570 - INFO - Returning cleaned DataFrame.

Connection closed.
--------------- Teller TRX processing ---------------
(12, 37)
  T24_ACCOUNT     EQ_ACCOUNT ORACLE_ACCOUNT TRANSACTION_REF TRANSACTION_SEQ  \
0  2002611131  5812273189500  0891110000737    TT23345ZGG4M             120
1  2002611131  5812273189500  0891110000737    TT23346J1TZC              44

  TRANSACTION_DATE TRANSACTION_DATE_TS TRANSACTION_CURRENCY  \
0           231211    2023-12-11 11.15                  TND
1           231212    2023-12-12 09.24                  TND

  TRANSACTION_AMOUNT TRANSACTION_CODE_ATB  ... COUNTRY_2 FOREIGN_AMOUNT_2  \
0  150000.0000000000                  556  ...        TN       150000.000
1    4000.0000000000                  556  ...        TN         4000.000

  TRANSACTION_LOCATION            TRANSACTION_NUMBER     DATE_TRANSACTION  \
0      Agence Ibn Sina  30/TT23345ZGG4M;1/11 12 2023  2023-12-11T00:00:00
1      Agence Ibn Sina  30/TT23346J1TZC;1/12 12 2023  2023-12-12T00:00:00

  AMOUNT_LOCAL TRANSACTION_STATUS_CODE   NAR      SOURCE _merge
0   150000.000                       C  None  TELLER_HIS   both
1     4000.000                       C  None  TELLER_HIS   both

[2 rows x 37 columns]

  0%|          | 0/12 [00:00<?, ?it/s]2025-04-28 13:22:51,677 - INFO - Starting to retrieve PPH data for customer ID 07017001

============ Teller - Model ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23345ZGG4M
TRANSACTION_SEQ                                                           120
TRANSACTION_DATE                                                       231211
TRANSACTION_DATE_TS                                          2023-12-11 11.15
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                          150000.0000000000
TRANSACTION_CODE_ATB                                                      556
TRANSACTION_DESC_ATB_ACC                                     Vers Especes MAg
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Vers Especes MAg
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B114
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                   150000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                            None
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                   150000.000
TRANSACTION_LOCATION                                          Agence Ibn Sina
TRANSACTION_NUMBER                               30/TT23345ZGG4M;1/11 12 2023
DATE_TRANSACTION                                          2023-12-11T00:00:00
AMOUNT_LOCAL                                                       150000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                                      None
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 0, dtype: object
====================================
====================================
============ XML ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23345ZGG4M
TRANSACTION_SEQ                                                           120
TRANSACTION_DATE                                                       231211
TRANSACTION_DATE_TS                                          2023-12-11 11.15
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                          150000.0000000000
TRANSACTION_CODE_ATB                                                      556
TRANSACTION_DESC_ATB_ACC                                     Vers Especes MAg
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Vers Especes MAg
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B114
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                   150000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                            None
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                   150000.000
TRANSACTION_LOCATION                                          Agence Ibn Sina
TRANSACTION_NUMBER                               30/TT23345ZGG4M;1/11 12 2023
DATE_TRANSACTION                                          2023-12-11T00:00:00
AMOUNT_LOCAL                                                       150000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                                      None
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 0, dtype: object
Agence Ibn Sina
====================================
====================================
============ Teller - Model ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23346J1TZC
TRANSACTION_SEQ                                                            44
TRANSACTION_DATE                                                       231212
TRANSACTION_DATE_TS                                          2023-12-12 09.24
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            4000.0000000000
TRANSACTION_CODE_ATB                                                      556
TRANSACTION_DESC_ATB_ACC                                     Vers Especes MAg
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Vers Especes MAg
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B114
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     4000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                            None
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     4000.000
TRANSACTION_LOCATION                                          Agence Ibn Sina
TRANSACTION_NUMBER                               30/TT23346J1TZC;1/12 12 2023
DATE_TRANSACTION                                          2023-12-12T00:00:00
AMOUNT_LOCAL                                                         4000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                                      None
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 1, dtype: object
====================================
====================================
============ XML ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23346J1TZC
TRANSACTION_SEQ                                                            44
TRANSACTION_DATE                                                       231212
TRANSACTION_DATE_TS                                          2023-12-12 09.24
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            4000.0000000000
TRANSACTION_CODE_ATB                                                      556
TRANSACTION_DESC_ATB_ACC                                     Vers Especes MAg
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Vers Especes MAg
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B114
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     4000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                            None
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     4000.000
TRANSACTION_LOCATION                                          Agence Ibn Sina
TRANSACTION_NUMBER                               30/TT23346J1TZC;1/12 12 2023
DATE_TRANSACTION                                          2023-12-12T00:00:00
AMOUNT_LOCAL                                                         4000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                                      None
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 1, dtype: object
Agence Ibn Sina
====================================
====================================
Connection established successfully.

2025-04-28 13:22:52,017 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '07017001'

2025-04-28 13:22:52,019 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '07017001'

2025-04-28 13:22:57,022 - WARNING - Failed to execute query after 1 attempts
2025-04-28 13:22:57,024 - WARNING - No PPH data found for customer ID 07017001
 25%|██▌       | 3/12 [00:05<00:16,  1.80s/it]2025-04-28 13:22:57,039 - INFO - Starting to retrieve PPH data for customer ID 09446747
2025-04-28 13:22:57,141 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '09446747'

2025-04-28 13:22:57,146 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '09446747'

Connection closed.
============ Teller - Model ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23363YBHBF
TRANSACTION_SEQ                                                            90
TRANSACTION_DATE                                                       231229
TRANSACTION_DATE_TS                                          2023-12-29 10.08
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                             800.0000000000
TRANSACTION_CODE_ATB                                                      556
TRANSACTION_DESC_ATB_ACC                                     Vers Especes MAg
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Vers Especes MAg
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B114
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                      800.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                        07017001
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                      800.000
TRANSACTION_LOCATION                                          Agence Ibn Sina
TRANSACTION_NUMBER                               30/TT23363YBHBF;1/29 12 2023
DATE_TRANSACTION                                          2023-12-29T00:00:00
AMOUNT_LOCAL                                                          800.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                 ben saad lotfi - 07017001
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 2, dtype: object
====================================
====================================
============ XML ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23363YBHBF
TRANSACTION_SEQ                                                            90
TRANSACTION_DATE                                                       231229
TRANSACTION_DATE_TS                                          2023-12-29 10.08
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                             800.0000000000
TRANSACTION_CODE_ATB                                                      556
TRANSACTION_DESC_ATB_ACC                                     Vers Especes MAg
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Vers Especes MAg
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B114
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                      800.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                        07017001
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                      800.000
TRANSACTION_LOCATION                                          Agence Ibn Sina
TRANSACTION_NUMBER                               30/TT23363YBHBF;1/29 12 2023
DATE_TRANSACTION                                          2023-12-29T00:00:00
AMOUNT_LOCAL                                                          800.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                 ben saad lotfi - 07017001
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 2, dtype: object
Agence Ibn Sina
====================================
====================================
Connection established successfully.

2025-04-28 13:23:02,149 - WARNING - Failed to execute query after 1 attempts
2025-04-28 13:23:02,151 - WARNING - No PPH data found for customer ID 09446747
 33%|███▎      | 4/12 [00:10<00:22,  2.87s/it]2025-04-28 13:23:02,168 - INFO - Starting to retrieve PPH data for customer ID 04153927
2025-04-28 13:23:02,247 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '04153927'

2025-04-28 13:23:02,251 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '04153927'

Connection closed.
============ Teller - Model ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23327MFKZ9
TRANSACTION_SEQ                                                            86
TRANSACTION_DATE                                                       231123
TRANSACTION_DATE_TS                                          2023-11-23 13.59
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            1000.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     1000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                        09446747
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     1000.000
TRANSACTION_LOCATION                                            Agence El Jem
TRANSACTION_NUMBER                               30/TT23327MFKZ9;1/23 11 2023
DATE_TRANSACTION                                          2023-11-23T00:00:00
AMOUNT_LOCAL                                                         1000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                    habib souga - 09446747
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 3, dtype: object
====================================
====================================
============ XML ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23327MFKZ9
TRANSACTION_SEQ                                                            86
TRANSACTION_DATE                                                       231123
TRANSACTION_DATE_TS                                          2023-11-23 13.59
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            1000.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     1000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                        09446747
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     1000.000
TRANSACTION_LOCATION                                            Agence El Jem
TRANSACTION_NUMBER                               30/TT23327MFKZ9;1/23 11 2023
DATE_TRANSACTION                                          2023-11-23T00:00:00
AMOUNT_LOCAL                                                         1000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                    habib souga - 09446747
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 3, dtype: object
Agence El Jem
====================================
====================================
Connection established successfully.

2025-04-28 13:23:07,256 - WARNING - Failed to execute query after 1 attempts
2025-04-28 13:23:07,257 - WARNING - No PPH data found for customer ID 04153927
 42%|████▏     | 5/12 [00:15<00:25,  3.58s/it]2025-04-28 13:23:07,285 - INFO - Starting to retrieve PPH data for customer ID 01811528
2025-04-28 13:23:07,381 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '01811528'

2025-04-28 13:23:07,384 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '01811528'

Connection closed.
============ Teller - Model ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT233288WD5W
TRANSACTION_SEQ                                                             8
TRANSACTION_DATE                                                       231124
TRANSACTION_DATE_TS                                          2023-11-24 08.44
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            1000.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     1000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                        04153927
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     1000.000
TRANSACTION_LOCATION                                     Agence Hammam Sousse
TRANSACTION_NUMBER                               30/TT233288WD5W;1/24 11 2023
DATE_TRANSACTION                                          2023-11-24T00:00:00
AMOUNT_LOCAL                                                         1000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                             mahbouba ghammoune - 04153927
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 4, dtype: object
====================================
====================================
============ XML ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT233288WD5W
TRANSACTION_SEQ                                                             8
TRANSACTION_DATE                                                       231124
TRANSACTION_DATE_TS                                          2023-11-24 08.44
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            1000.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     1000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                        04153927
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     1000.000
TRANSACTION_LOCATION                                     Agence Hammam Sousse
TRANSACTION_NUMBER                               30/TT233288WD5W;1/24 11 2023
DATE_TRANSACTION                                          2023-11-24T00:00:00
AMOUNT_LOCAL                                                         1000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                             mahbouba ghammoune - 04153927
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 4, dtype: object
Agence Hammam Sousse
====================================
====================================
============ Teller - Model ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23333Q5FH1
TRANSACTION_SEQ                                                            52
TRANSACTION_DATE                                                       231129
TRANSACTION_DATE_TS                                          2023-11-29 13.10
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            1900.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     1900.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                            None
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     1900.000
TRANSACTION_LOCATION                                            Agence El Jem
TRANSACTION_NUMBER                               30/TT23333Q5FH1;1/29 11 2023
DATE_TRANSACTION                                          2023-11-29T00:00:00
AMOUNT_LOCAL                                                         1900.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                                      None
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 5, dtype: object
====================================
====================================
============ XML ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23333Q5FH1
TRANSACTION_SEQ                                                            52
TRANSACTION_DATE                                                       231129
TRANSACTION_DATE_TS                                          2023-11-29 13.10
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            1900.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     1900.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                            None
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     1900.000
TRANSACTION_LOCATION                                            Agence El Jem
TRANSACTION_NUMBER                               30/TT23333Q5FH1;1/29 11 2023
DATE_TRANSACTION                                          2023-11-29T00:00:00
AMOUNT_LOCAL                                                         1900.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                                      None
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 5, dtype: object
Agence El Jem
====================================
====================================
============ Teller - Model ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23338Z853T
TRANSACTION_SEQ                                                           166
TRANSACTION_DATE                                                       231204
TRANSACTION_DATE_TS                                          2023-12-04 17.38
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                             500.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                      500.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                            None
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                      500.000
TRANSACTION_LOCATION                                     Agence Menzel Temime
TRANSACTION_NUMBER                               30/TT23338Z853T;1/04 12 2023
DATE_TRANSACTION                                          2023-12-04T00:00:00
AMOUNT_LOCAL                                                          500.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                                      None
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 6, dtype: object
====================================
====================================
============ XML ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23338Z853T
TRANSACTION_SEQ                                                           166
TRANSACTION_DATE                                                       231204
TRANSACTION_DATE_TS                                          2023-12-04 17.38
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                             500.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                      500.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                            None
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                      500.000
TRANSACTION_LOCATION                                     Agence Menzel Temime
TRANSACTION_NUMBER                               30/TT23338Z853T;1/04 12 2023
DATE_TRANSACTION                                          2023-12-04T00:00:00
AMOUNT_LOCAL                                                          500.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                                      None
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 6, dtype: object
Agence Menzel Temime
====================================
====================================
============ Teller - Model ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT2333900678
TRANSACTION_SEQ                                                           216
TRANSACTION_DATE                                                       231205
TRANSACTION_DATE_TS                                          2023-12-05 15.11
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            2500.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K

2025-04-28 13:23:12,386 - WARNING - Failed to execute query after 1 attempts
2025-04-28 13:23:12,387 - WARNING - No PPH data found for customer ID 01811528
100%|██████████| 12/12 [00:20<00:00,  1.73s/it]

Connection closed.
============ Teller - Model ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23339TS68Q
TRANSACTION_SEQ                                                           156
TRANSACTION_DATE                                                       231205
TRANSACTION_DATE_TS                                          2023-12-05 13.31
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            6000.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     6000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                        01811528
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     6000.000
TRANSACTION_LOCATION                                             Agence Rades
TRANSACTION_NUMBER                               30/TT23339TS68Q;1/05 12 2023
DATE_TRANSACTION                                          2023-12-05T00:00:00
AMOUNT_LOCAL                                                         6000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                  hawari mohsen - 01811528
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 8, dtype: object
====================================
====================================
============ XML ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23339TS68Q
TRANSACTION_SEQ                                                           156
TRANSACTION_DATE                                                       231205
TRANSACTION_DATE_TS                                          2023-12-05 13.31
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            6000.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     6000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                        01811528
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     6000.000
TRANSACTION_LOCATION                                             Agence Rades
TRANSACTION_NUMBER                               30/TT23339TS68Q;1/05 12 2023
DATE_TRANSACTION                                          2023-12-05T00:00:00
AMOUNT_LOCAL                                                         6000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                                  hawari mohsen - 01811528
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 8, dtype: object
Agence Rades
====================================
====================================
============ Teller - Model ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23342NSDGD
TRANSACTION_SEQ                                                           138
TRANSACTION_DATE                                                       231208
TRANSACTION_DATE_TS                                          2023-12-08 12.22
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            6000.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     6000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                        01811528
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     6000.000
TRANSACTION_LOCATION                                             Agence KORBA
TRANSACTION_NUMBER                               30/TT23342NSDGD;1/08 12 2023
DATE_TRANSACTION                                          2023-12-08T00:00:00
AMOUNT_LOCAL                                                         6000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                            mohsen hawari S H A - 01811528
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 9, dtype: object
====================================
====================================
============ XML ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23342NSDGD
TRANSACTION_SEQ                                                           138
TRANSACTION_DATE                                                       231208
TRANSACTION_DATE_TS                                          2023-12-08 12.22
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            6000.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     6000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                        01811528
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     6000.000
TRANSACTION_LOCATION                                             Agence KORBA
TRANSACTION_NUMBER                               30/TT23342NSDGD;1/08 12 2023
DATE_TRANSACTION                                          2023-12-08T00:00:00
AMOUNT_LOCAL                                                         6000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                            mohsen hawari S H A - 01811528
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 9, dtype: object
Agence KORBA
====================================
====================================
============ Teller - Model ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23356KYGFH
TRANSACTION_SEQ                                                            50
TRANSACTION_DATE                                                       231222
TRANSACTION_DATE_TS                                          2023-12-22 10.08
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            3000.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     3000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                        01811528
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     3000.000
TRANSACTION_LOCATION                                             Agence KORBA
TRANSACTION_NUMBER                               30/TT23356KYGFH;1/22 12 2023
DATE_TRANSACTION                                          2023-12-22T00:00:00
AMOUNT_LOCAL                                                         3000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                            mohsen hawari S H A - 01811528
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 10, dtype: object
====================================
====================================
============ XML ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23356KYGFH
TRANSACTION_SEQ                                                            50
TRANSACTION_DATE                                                       231222
TRANSACTION_DATE_TS                                          2023-12-22 10.08
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                            3000.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K
FUND_CODE_2                                                                 A
PARTY_ROLE                                                                  B
CURRENCY_CODE_1                                                           TND
COUNTRY_1                                                                  TN
FOREIGN_AMOUNT_1                                                     3000.000
L_ORDONATEUR                                                             None
L_TIERS_NUMID                                                        01811528
CURRENCY_CODE_2                                                           TND
COUNTRY_2                                                                  TN
FOREIGN_AMOUNT_2                                                     3000.000
TRANSACTION_LOCATION                                             Agence KORBA
TRANSACTION_NUMBER                               30/TT23356KYGFH;1/22 12 2023
DATE_TRANSACTION                                          2023-12-22T00:00:00
AMOUNT_LOCAL                                                         3000.000
TRANSACTION_STATUS_CODE                                                     C
NAR                                            mohsen hawari S H A - 01811528
SOURCE                                                             TELLER_HIS
_merge                                                                   both
Name: 10, dtype: object
Agence KORBA
====================================
====================================
============ Teller - Model ================
====================================
T24_ACCOUNT                                                        2002611131
EQ_ACCOUNT                                                      5812273189500
ORACLE_ACCOUNT                                                  0891110000737
TRANSACTION_REF                                                  TT23363LC1M5
TRANSACTION_SEQ                                                            58
TRANSACTION_DATE                                                       231229
TRANSACTION_DATE_TS                                          2023-12-29 09.30
TRANSACTION_CURRENCY                                                      TND
TRANSACTION_AMOUNT                                             500.0000000000
TRANSACTION_CODE_ATB                                                      561
TRANSACTION_DESC_ATB_ACC                       Versement Especes Autre Agence
APP_SOURCE_CODE                                                         T24TL
TRANSACTION_DESC_ATB_F                    Versement Especes Autre Agence
APP_SOURCE                                                             Teller
OP_TYPE                                                                Caisse
Categorie_de_transaction    code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                                                    NaN
TRANSACTION_CODE_GOAML                                                   B115
FUND_CODE_1                                                                 K

In [13]:
accountant_caisse_cashier = transaction_router.accountant_transactions_with_trx_code.query(
    "OP_TYPE == 'Caisse' and Categorie_de_transaction == 'code affectant directement le compte client (débit/crédit)'"
).copy(deep=True)

In [16]:
accountant_caisse_cashier[['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE']]

        EQ_ACCOUNT TRANSACTION_REF TRANSACTION_DATE
118  5812273189500   1230221000058          1230221
119  5812273189500   1230222000045          1230222
120  5812273189500   1230310000060          1230310
121  5812273189500   1230314000050          1230314
122  5812273189500   1230322000055          1230322
..             ...             ...              ...
404  5812273189500    TT2333900678          1231205
405  5812273189500    TT23339TS68Q          1231205
406  5812273189500    TT23342NSDGD          1231208
407  5812273189500    TT23356KYGFH          1231222
408  5812273189500    TT23363LC1M5          1231229

[189 rows x 3 columns]

In [33]:
transaction_router.caisse.accountant_transactions_with_trx_code_and_cashier[transaction_router.caisse.accountant_transactions_with_trx_code_and_cashier['_merge'] != 'left_only']

Empty DataFrame
Columns: [T24_ACCOUNT, EQ_ACCOUNT, ORACLE_ACCOUNT, TRANSACTION_REF, TRANSACTION_SEQ, TRANSACTION_DATE, TRANSACTION_DATE_TS, TRANSACTION_CURRENCY, TRANSACTION_AMOUNT, TRANSACTION_CODE_ATB, TRANSACTION_DESC_ATB_ACC, APP_SOURCE_CODE, TRANSACTION_DESC_ATB_F, APP_SOURCE, OP_TYPE, Categorie_de_transaction, TRANSACTION_DESC_GOAML, TRANSACTION_CODE_GOAML, FUND_CODE_1, FUND_CODE_2, _merge]
Index: []

[0 rows x 21 columns]

In [18]:
import pandas as pd

In [23]:
accountant_transactions_with_trx_code_and_cashier = pd.merge(
    left=accountant_caisse_cashier,
    right=transaction_router.caisse.accountant_transactions_with_trx_code_of_cashier,
    left_on=['EQ_ACCOUNT', 'TRANSACTION_DATE', 'TRANSACTION_REF'],
    right_on=['EQ_ACCOUNT', 'TRANSACTION_DATE', 'TRANSACTION_REF'],
    how='left',
    indicator='merge_flag'  # <-- use a custom name
).copy(deep=True)

In [25]:
accountant_transactions_with_trx_code_and_cashier[accountant_transactions_with_trx_code_and_cashier['merge_flag'] == 'both']

,T24_ACCOUNT_x,EQ_ACCOUNT,ORACLE_ACCOUNT_x,TRANSACTION_REF,TRANSACTION_SEQ_x,TRANSACTION_DATE,TRANSACTION_DATE_TS_x,TRANSACTION_CURRENCY_x,TRANSACTION_AMOUNT_x,TRANSACTION_CODE_ATB_x,...,TRANSACTION_DESC_ATB_F_y,APP_SOURCE_y,OP_TYPE_y,Categorie_de_transaction_y,TRANSACTION_DESC_GOAML_y,TRANSACTION_CODE_GOAML_y,FUND_CODE_1_y,FUND_CODE_2_y,_merge,merge_flag
0,2002611131,5812273189500,0891110000737,1230221000058,37,1230221,2023-02-21 13.53,TND,-600.0000000000,001,...,Retrait Especes,Cashier,Caisse,code affectant directement le compte client (d...,Retrait espèces,B200,A,K,left_only,both
1,2002611131,5812273189500,0891110000737,1230222000045,41,1230222,2023-02-22 14.47,TND,-900.0000000000,001,...,Retrait Especes,Cashier,Caisse,code affectant directement le compte client (d...,Retrait espèces,B200,A,K,left_only,both
2,2002611131,5812273189500,0891110000737,1230310000060,53,1230310,2023-03-10 11.04,TND,-19000.0000000000,001,...,Retrait Especes,Cashier,Caisse,code affectant directement le compte client (d...,Retrait espèces,B200,A,K,left_only,both
3,2002611131,5812273189500,0891110000737,1230314000050,50,1230314,2023-03-14 14.04,TND,-3000.0000000000,001,...,Retrait Especes,Cashier,Caisse,code affectant directement le compte client (d...,Retrait espèces,B200,A,K,left_only,both
4,2002611131,5812273189500,0891110000737,1230322000055,49,1230322,2023-03-22 16.23,TND,-700.0000000000,001,...,Retrait Especes,Cashier,Caisse,code affectant directement le compte client (d...,Retrait espèces,B200,A,K,left_only,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,2002611131,5812273189500,0891110000737,1231121000058,52,1231121,2023-11-21 14.33,TND,2000.0000000000,701,...,Versement Especes,Cashier,Caisse,code affectant directement le compte client (d...,Versement espèces,B114,K,A,left_only,both
173,2002611131,5812273189500,0891110000737,1231124000080,72,1231124,2023-11-24 14.17,TND,1000.0000000000,701,...,Versement Especes,Cashier,Caisse,code affectant directement le compte client (d...,Versement espèces,B114,K,A,left_only,both
174,2002611131,5812273189500,0891110000737,1231127000080,77,1231127,2023-11-27 15.08,TND,1500.0000000000,701,...,Versement Especes,Cashier,Caisse,code affectant directement le compte client (d...,Versement espèces,B114,K,A,left_only,both
175,2002611131,5812273189500,0891110000737,1231128000065,63,1231128,2023-11-28 15.20,TND,700.0000000000,701,...,Versement Especes,Cashier,Caisse,code affectant directement le compte client (d...,Versement espèces,B114,K,A,left_only,both
176,2002611131,5812273189500,0891110000737,1231130000079,78,1231130,2023-11-30 14.47,TND,1300.0000000000,701,...,Versement Especes,Cashier,Caisse,code affectant directement le compte client (d...,Versement espèces,B114,K,A,left_only,both

In [26]:
accountant_caisse_cashier

,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB_ACC,APP_SOURCE_CODE,TRANSACTION_DESC_ATB_F,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_DESC_GOAML,TRANSACTION_CODE_GOAML,FUND_CODE_1,FUND_CODE_2
118,2002611131,5812273189500,0891110000737,1230221000058,37,1230221,2023-02-21 13.53,TND,-600.0000000000,001,Retrait Especes,@AAA,Retrait Especes,Cashier,Caisse,code affectant directement le compte client (d...,Retrait espèces,B200,A,K
119,2002611131,5812273189500,0891110000737,1230222000045,41,1230222,2023-02-22 14.47,TND,-900.0000000000,001,Retrait Especes,@AAA,Retrait Especes,Cashier,Caisse,code affectant directement le compte client (d...,Retrait espèces,B200,A,K
120,2002611131,5812273189500,0891110000737,1230310000060,53,1230310,2023-03-10 11.04,TND,-19000.0000000000,001,Retrait Especes,@AAA,Retrait Especes,Cashier,Caisse,code affectant directement le compte client (d...,Retrait espèces,B200,A,K
121,2002611131,5812273189500,0891110000737,1230314000050,50,1230314,2023-03-14 14.04,TND,-3000.0000000000,001,Retrait Especes,@AAA,Retrait Especes,Cashier,Caisse,code affectant directement le compte client (d...,Retrait espèces,B200,A,K
122,2002611131,5812273189500,0891110000737,1230322000055,49,1230322,2023-03-22 16.23,TND,-700.0000000000,001,Retrait Especes,@AAA,Retrait Especes,Cashier,Caisse,code affectant directement le compte client (d...,Retrait espèces,B200,A,K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,2002611131,5812273189500,0891110000737,TT2333900678,216,1231205,2023-12-05 15.11,TND,2500.0000000000,561,Versement Especes Autre Agence,T24TL,Versement Especes Autre Agence,Teller,Caisse,code affectant directement le compte client (d...,NaN,B115,K,A
405,2002611131,5812273189500,0891110000737,TT23339TS68Q,156,1231205,2023-12-05 13.31,TND,6000.0000000000,561,Versement Especes Autre Agence,T24TL,Versement Especes Autre Agence,Teller,Caisse,code affectant directement le compte client (d...,NaN,B115,K,A
406,2002611131,5812273189500,0891110000737,TT23342NSDGD,138,1231208,2023-12-08 12.22,TND,6000.0000000000,561,Versement Especes Autre Agence,T24TL,Versement Especes Autre Agence,Teller,Caisse,code affectant directement le compte client (d...,NaN,B115,K,A
407,2002611131,5812273189500,0891110000737,TT23356KYGFH,50,1231222,2023-12-22 10.08,TND,3000.0000000000,561,Versement Especes Autre Agence,T24TL,Versement Especes Autre Agence,Teller,Caisse,code affectant directement le compte client (d...,NaN,B115,K,A
408,2002611131,5812273189500,0891110000737,TT23363LC1M5,58,1231229,2023-12-29 09.30,TND,500.0000000000,561,Versement Especes Autre Agence,T24TL,Versement Especes Autre Agence,Teller,Caisse,code affectant directement le compte client (d...,NaN,B115,K,A