In [1]:
import sys
sys.path.append('../')

In [2]:
from src.config import DB_CONFIG, TREANSACTION_CODE

In [3]:
from src.model.get_client_T24 import GetClientT24

In [4]:
get_client_T24 = GetClientT24(DB_CONFIG)

In [5]:
import pyodbc

In [6]:
account_number = '5820099621500'#'5858714923500'# '5858714923500' - problem
print(get_client_T24.account_status_lookup(account_number)) # True -> Active Account

account_correspondences, account_details, customer_id, account_type, account_rp = get_client_T24.get_client(account_number)

2026-04-22 15:49:05,810 - INFO - Executing account status lookup for account: 5820099621500
2026-04-22 15:49:05,955 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820099621500'

2026-04-22 15:49:05,958 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820099621500'

2026-04-22 15:49:05,960 - INFO - Account 5820099621500 is IS_ACTIVE
2026-04-22 15:49:05,972 - INFO - Executing account status lookup for account: 5820099621500
2026-04-22 15:49:05,979 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820099621500'

2026-04-22 15:49:05,980 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820099621500'

2026-04-22 15:49:05,981 - INFO - Account 5820099621500 is IS_ACTIVE
2026-04-22 15:49:06,000 - INFO - Executing query to retrieve account information for account number: 5820099621500

Connection established successfully.
Connection closed.
True
Connection established successfully.
Connection closed.
Connection established successfully.

2026-04-22 15:49:10,871 - INFO - Successfully executed query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    --EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.WORKING_BALANCE AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        --WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE
                    LEFT(ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER, 1) IN ('5', '6')
					AND CAST(LEFT(ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER, 3) AS INT) BETWEEN 500 AND 599
					AND ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820099621500'

2026-04-22 15:49:10,875 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    --EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.WORKING_BALANCE AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        --WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE
                    LEFT(ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER, 1) IN ('5', '6')
					AND CAST(LEFT(ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER, 3) AS INT) BETWEEN 500 AND 599
					AND ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820099621500'

2026-04-22 15:49:10,880 - INFO - Successfully retrieved account information for account number: 5820099621500
2026-04-22 15:49:10,918 - INFO - Executing query to retrieve arrangement information for arrangement id : AA24173RGC9Q

Connection closed.
Connection established successfully.

2026-04-22 15:49:13,127 - INFO - Successfully executed query:
        SELECT
            LEFT(RECID, CHARINDEX('-', RECID) - 1) AS ARRANGEMENT_ID,
            CUSTOMER_3,
            CUSTOMER_ROLE_4,
            L_ACCT_TYPE
        FROM [MISDW].[GO_AML].[T24_FATB_AA_ARR_CUSTOMER]
        WHERE
            LEFT(RECID, CHARINDEX('-', RECID) - 1) = 'AA24173RGC9Q'

2026-04-22 15:49:13,132 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            LEFT(RECID, CHARINDEX('-', RECID) - 1) AS ARRANGEMENT_ID,
            CUSTOMER_3,
            CUSTOMER_ROLE_4,
            L_ACCT_TYPE
        FROM [MISDW].[GO_AML].[T24_FATB_AA_ARR_CUSTOMER]
        WHERE
            LEFT(RECID, CHARINDEX('-', RECID) - 1) = 'AA24173RGC9Q'

2026-04-22 15:49:13,135 - INFO - Successfully retrieved account information for arrangement id : AA24173RGC9Q
2026-04-22 15:49:13,167 - INFO - Starting to retrieve PPH data for customer ID 99621

Connection closed.
  ARRANGEMENT_ID CUSTOMER_ID CUSTOMER_ROLE L_ACCT_TYPE
0   AA24173RGC9Q       99621         OWNER           3
The DataFrame has only one record, and CUSTOMER_ROLE is OWNER.
Connection established successfully.

2026-04-22 15:49:13,726 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = '' THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '99621'

2026-04-22 15:49:13,730 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = '' THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '99621'

2026-04-22 15:49:13,736 - INFO - Retrieved PPH data successfully for customer ID 99621
2026-04-22 15:49:13,759 - INFO - Executing query to retrieve mandates information for account mandate id : None

Connection closed.
Connection established successfully.

2026-04-22 15:49:14,029 - INFO - Successfully executed query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = 'None'

2026-04-22 15:49:14,035 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = 'None'

2026-04-22 15:49:19,039 - WARNING - Failed to execute query after 1 attempts
2026-04-22 15:49:19,041 - WARNING - No data found for account mandate id : None

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER   FIRST_NAME LAST_NAME  \
0           PPH       99621      M  AHMED AMINE    RIHANI

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  2000-05-08T00:00:00     TN - TN            CIN  14328376             TN

   ... NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  ...          TN        TN            1

                                  ADDRESS    TOWN CITY   ZIP COUNTRY_CODE  \
0  55 RUE AIN GHELAL DAR FADHAL LA SOUKRA  SOUKRA  N.A  2036           TN

                                          OCCUPATION ROLE_ACCOUNT
0  Cadres de directions des services administrati...        TICPT

[1 rows x 22 columns]
==================
+++++++++++++++

In [ ]:
p

In [7]:
account_correspondences

{'T24_ACCOUNT': '2010715221',
 'EQ_ACCOUNT': '5820099621500',
 'ORACLE_ACCOUNT': '0201119832534'}

In [10]:
print(account_details)

        <IB_account>
            <institution_name>ARAB TUNISIAN BANK</institution_name>
            <swift>ATBKTNTT</swift>
            <account>01117143116700037014</account>
            <currency_code>TND</currency_code>
            <account_name>T24 - KHOULOUD BOURAYOU</account_name>
            <personal_account_type>CPTC</personal_account_type>

            <related_persons>
                        <account_related_person>
                <t_person>
                    <gender>F</gender>
                    <first_name>KHOULOUD</first_name>
                    <last_name>BOURAYOU</last_name>
                    <birthdate>1995-08-28T00:00:00</birthdate>
                    <birth_place>TN - TEBOURSOUK</birth_place>
                    <nationality1>TN</nationality1>
                    <residence>TN</residence>
                    <addresses>
                        <address>
                            <address_type>1</address_type>
                            <address>N.A - address - CustomerID: 43515</address>
                            <town>TEBOURSOUK</town>
                            <city>N.A - city - CustomerID: 43515</city>
                            <zip>9040</zip>
                            <country_code>TN</country_code>
                        </address>
                    </addresses>
                    <occupation>Medecins dentistes</occupation>
                    <identifications>
                        <identification><type>B</type><number>14255090</number><issue_date>2022-08-17T00:00:00</issue_date><issue_country>TN</issue_country></identification> <identification><type>D</type><number>1824208DAP000</number><issue_date>2023-05-23T00:00:00</issue_date><issue_country>TN</issue_country></identification>
                    </identifications>
                </t_person>
                <role>TICPT</role>
            </account_related_person>
            </related_persons>
            <opened>2023-05-29T00:00:00</opened>

            <balance>45572.228</balance>
            <date_balance>2026-01-12T09:39:10</date_balance>
            <status_code>A</status_code>
        </IB_account>

In [13]:
customer_id

'469328'

In [14]:
account_rp

,CUSTOMER_ID,CUSTOMER_TYPE,GENDER,FIRST_NAME,LAST_NAME,BIRTHDATE,BIRTH_PLACE,NATIONALITY,RESIDENCE,ADDRESS_TYPE,...,ZIP,COUNTRY_CODE,OCCUPATION,RELATED_PERSON_RELATION_CODE_ATB,RELATED_PERSON_ROLE_CODE_ATB,ROLE_ENTITY,ROLE_ACCOUNT,SOURCE,ACCOUNT_TYPE,IDENTIFICATIONS_ID_SECTION
0,381549,PPH,M,JAMEL,CHAHED,1958-05-08T00:00:00,TN,TN,TN,1,...,4180,TN,Retraites,307,50,CUSTOMER_ID : 381549 N.A - ROLE_CODE_goAML,MAND,TIER,CPM,<identification><type>B</type><number>01353013...
1,381549,PPH,M,JAMEL,CHAHED,1958-05-08T00:00:00,TN,TN,TN,1,...,4180,TN,Retraites,303,50,CUSTOMER_ID : 381549 N.A - ROLE_CODE_goAML,MAND,TIER,CPM,<identification><type>B</type><number>01353013...
2,514539,TRPP,M,SABEUR,BEN CHAABANE,1978-09-08T00:00:00,TN - MEDENINE,TN,US,1,...,BP 72,TN,Enseignants de l'enseignements secondaire,307,50,CUSTOMER_ID : 514539 N.A - ROLE_CODE_goAML,MAND,TIER,CPM,<identification><type>B</type><number>05745772...
3,514539,TRPP,M,SABEUR,BEN CHAABANE,1978-09-08T00:00:00,TN - MEDENINE,TN,US,1,...,BP 72,TN,Enseignants de l'enseignements secondaire,303,50,CUSTOMER_ID : 514539 N.A - ROLE_CODE_goAML,MAND,TIER,CPM,<identification><type>B</type><number>05745772...
4,72383,TRPP,M,MEJDI,BLAGHGI,1979-09-05T00:00:00,TN,TN,TN,1,...,4190,TN,Enseignants universitaires,N.A,SIGNATAIRE,RL,MAND,SIG,CPM,<identification><type>B</type><number>05761996...

In [22]:
pm = get_client_T24.get_PPH('764564', 'CUSTOMER_CODE')

2025-12-29 07:58:53,500 - INFO - Starting to retrieve PPH data for customer ID 764564
2025-12-29 07:58:53,688 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = '' THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '764564'

Connection established successfully.

2025-12-29 07:58:53,696 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'N.A'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE 'N.A'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = '' THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(STREET, ''), 'N.A') AS ADDRESS,
                COALESCE(NULLIF(ADDRESS_ITEM1, ''), 'N.A') AS TOWN,
                COALESCE(NULLIF(ADDRESS, ''), 'N.A') AS CITY,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                --CASE
				--    WHEN COALESCE(COUNTRY, '') = ''
				--         AND COALESCE(TOWN_COUNTRY, '') = ''
				--         AND COALESCE(ADDRESS_ITEM1, '') = ''
				--         AND COALESCE(ADDRESS_ITEM2, '') = ''
				--         AND COALESCE(STREET, '') = ''
				--         AND COALESCE(ADDRESS, '') = ''
				--        THEN 'N.A'
				--    ELSE CONCAT_WS(' - ',
				--         NULLIF(COUNTRY, ''),
				--         NULLIF(TOWN_COUNTRY, ''),
				--         NULLIF(ADDRESS_ITEM1, ''),
				--         NULLIF(ADDRESS_ITEM2, ''),
				--         NULLIF(STREET, ''),
				--         NULLIF(ADDRESS, ''))
				--END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '764564'

2025-12-29 07:58:53,704 - INFO - Retrieved PPH data successfully for customer ID 764564

Connection closed.

In [23]:
pm

,CUSTOMER_TYPE,CUSTOMER_ID,GENDER,FIRST_NAME,LAST_NAME,BIRTHDATE,BIRTH_PLACE,LEGAL_DOC_NAME,LEGAL_ID,LEGAL_ISS_AUTH,...,LEGAL_EXP_DATE,NATIONALITY,RESIDENCE,ADDRESS_TYPE,ADDRESS,TOWN,CITY,ZIP,COUNTRY_CODE,OCCUPATION
0,PM,764564,N.A,None,None,N.A,TN,MF,0288929KAM000,TN,...,None,TN,TN,1,01 BIS RUE DU SENEGAL BP 348,BAB.EL.BHAR,1002 TUNIS BELVEDERE,1001,TN,N.A

In [42]:
account = {
    'account_number': account_number,
    'account_correspondences': account_correspondences,
    'account_detail': account_details,
    'customer_id': customer_id,
    'account_type': account_type,
    'account_rp': account_rp
}

In [44]:
account

{'account_number': '5830764564504',
 'account_correspondences': {'T24_ACCOUNT': '2010484882',
  'EQ_ACCOUNT': '5830764564504',
  'ORACLE_ACCOUNT': '0301156000535'},
 'account_detail': "\n        <IB_account>\n            <institution_name>ARAB TUNISIAN BANK</institution_name>\n            <swift>ATBKTNTT</swift>\n            <account>01900030115600053522</account>\n            <currency_code>TND</currency_code>\n            <account_name>T24 - SOMET HOTEL DJERBA RESORT</account_name>\n            <personal_account_type>CPTC</personal_account_type>\n            \n        <t_entity>\n            <name>SOMET HOTEL DJERBA RESORT</name>\n            <incorporation_legal_form>A</incorporation_legal_form>\n            <business>hebergement touristique et autre hebergement de courte duree</business>\n            <entity_status>A</entity_status>\n            <addresses>\n                <address>\n                    <address_type>2</address_type>\n                    <address>01 BIS RUE DU SENEGAL BP 348</address>\n                    <town>BAB.EL.BHAR</town>\n                    <city>1002 TUNIS BELVEDERE</city>\n                    <country_code>TN</country_code>\n                </address>\n            </addresses>\n            <incorporation_country_code>TN</incorporation_country_code>\n            <related_persons>\n                        <entity_related_person>\n                <person>\n                    <gender>M</gender>\n                    <first_name>SOUFIENE</first_name>\n                    <last_name>BEN HSSINE</last_name>\n                    <birthdate>1966-03-11T00:00:00</birthdate>\n                    <birth_place>TN</birth_place>\n                    <nationality1>TN</nationality1>\n                    <addresses>\n                        <address>\n                            <address_type>1</address_type>\n                            <address>BP 454</address>\n                            <town>DJERBA.HOUMET.SOUK</town>\n                            <city>4180 JERBA</city>\n                            <country_code>TN</country_code>\n                        </address>\n                    </addresses>\n                    <occupation>Autres employes de bureau</occupation>\n                    <identifications>\n                        <identification><type>B</type><number>03593300</number><issue_date>2009-05-26T00:00:00</issue_date><issue_country>TN</issue_country></identification>\n                    </identifications>\n                    <comments>CUSTOMER_ID = 116344, RELATED_PERSON_RELATION_CODE_ATB = 307, RELATED_PERSON_ROLE_CODE_ATB = 90, ROLE_ENTITY = CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML, ROLE_ACCOUNT = MAND</comments>\n                </person>\n                <role>CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML</role>\n            </entity_related_person>\n            <entity_related_person>\n                <person>\n                    <gender>M</gender>\n                    <first_name>ABDELAZIZ</first_name>\n                    <last_name>HALLOUMI</last_name>\n                    <birthdate>1966-01-03T00:00:00</birthdate>\n                    <birth_place>TN</birth_place>\n                    <nationality1>TN</nationality1>\n                    <addresses>\n                        <address>\n                            <address_type>1</address_type>\n                            <address>EL MAY JERBA</address>\n                            <town>DJERBA.HOUMET.SOUK</town>\n                            <city>N.A - city - CustomerID: 82041</city>\n                            <country_code>TN</country_code>\n                        </address>\n                    </addresses>\n                    <occupation>Directeurs d'entreprises</occupation>\n                    <identifications>\n                        <identification><type>B</type><number>03594679</number><issue_date>2000-07-31T00:00:00</issue_date><issue_country>TN</issue_country></identification>\n                    </identifications>\n                    <comments>CUSTOMER_ID = 82041, RELATED_PERSON_RELATION_CODE_ATB = N.A, RELATED_PERSON_ROLE_CODE_ATB = SIGNATAIRE, ROLE_ENTITY = RL, ROLE_ACCOUNT = MAND</comments>\n                </person>\n                <role>RL</role>\n            </entity_related_person>\n            </related_persons>\n            <incorporation_date>1991-12-23T00:00:00</incorporation_date>\n            \n            <entity_identifications>\n                <entity_identifier>\n                    <type>MF</type>\n                    <number>0288929KAM000</number>\n                    <issue_country>TN</issue_country>\n                </entity_identifier>\n            </entity_identifications>\n            \n        </t_entity>\n        \n            <related_persons>\n                        <account_related_person>\n                <t_person>\n                    <gender>M</gender>\n                    <first_name>SOUFIENE</first_name>\n                    <last_name>BEN HSSINE</last_name>\n                    <birthdate>1966-03-11T00:00:00</birthdate>\n                    <birth_place>TN</birth_place>\n                    <nationality1>TN</nationality1>\n                    <residence>TN</residence>\n                    <addresses>\n                        <address>\n                            <address_type>1</address_type>\n                            <address>N.A - address - CustomerID: 116344</address>\n                            <town>DJERBA.HOUMET.SOUK</town>\n                            <city>4180 JERBA</city>\n                            <zip>4180</zip>\n                            <country_code>TN</country_code>\n                        </address>\n                    </addresses>\n                    <occupation>Autres employes de bureau</occupation>\n                    <identifications>\n                        <identification><type>B</type><number>03593300</number><issue_date>2009-05-26T00:00:00</issue_date><issue_country>TN</issue_country></identification>\n                    </identifications>\n                    <comments>CUSTOMER_ID = 116344, RELATED_PERSON_RELATION_CODE_ATB = 307, RELATED_PERSON_ROLE_CODE_ATB = 90, ROLE_ENTITY = CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML, ROLE_ACCOUNT = MAND</comments>\n                </t_person>\n                <role>MAND</role>\n            </account_related_person>\n            <account_related_person>\n                <t_person>\n                    <gender>M</gender>\n                    <first_name>ABDELAZIZ</first_name>\n                    <last_name>HALLOUMI</last_name>\n                    <birthdate>1966-01-03T00:00:00</birthdate>\n                    <birth_place>TN</birth_place>\n                    <nationality1>TN</nationality1>\n                    <residence>TN</residence>\n                    <addresses>\n                        <address>\n                            <address_type>1</address_type>\n                            <address>N.A - address - CustomerID: 82041</address>\n                            <town>DJERBA.HOUMET.SOUK</town>\n                            <city>N.A - city - CustomerID: 82041</city>\n                            <zip>4180</zip>\n                            <country_code>TN</country_code>\n                        </address>\n                    </addresses>\n                    <occupation>Directeurs d'entreprises</occupation>\n                    <identifications>\n                        <identification><type>B</type><number>03594679</number><issue_date>2000-07-31T00:00:00</issue_date><issue_country>TN</issue_country></identification>\n                    </identifications>\n                    <comments>CUSTOMER_ID = 82041, RELATED_PERSON_RELATION_CODE_ATB = N.A, RELATED_PERSON_ROLE_CODE_ATB = SIGNATAIRE, ROLE_ENTITY = RL, ROLE_ACCOUNT = MAND</comments>\n                </t_person>\n                <role>MAND</role>\n            </account_related_person>\n            </related_persons>\n            <opened>2023-09-20T00:00:00</opened>\n            \n            <balance>478.16</balance>\n            <date_balance>2026-01-09T07:22:32</date_balance>\n            <status_code>A</status_code>\n        </IB_account>\n        ",
 'customer_id': '764564',
 'account_type': 'PM',
 'account_rp':   CUSTOMER_ID CUSTOMER_TYPE GENDER FIRST_NAME   LAST_NAME  \
 0      116344           PPH      M   SOUFIENE  BEN HSSINE
 1       82041          TRPP      M  ABDELAZIZ    HALLOUMI

              BIRTHDATE BIRTH_PLACE NATIONALITY RESIDENCE ADDRESS_TYPE  ...  \
 0  1966-03-11T00:00:00          TN          TN        TN            1  ...
 1  1966-01-03T00:00:00          TN          TN        TN            1  ...

     ZIP COUNTRY_CODE                 OCCUPATION  \
 0  4180           TN  Autres employes de bureau
 1  4180           TN   Directeurs d'entreprises

   RELATED_PERSON_RELATION_CODE_ATB RELATED_PERSON_ROLE_CODE_ATB  \
 0                              307                           90
 1                              N.A                   SIGNATAIRE

                                   ROLE_ENTITY ROLE_ACCOUNT SOURCE  \
 0  CUSTOMER_ID : 116344 N.A - ROLE_CODE_goAML         MAND   TIER
 1                                          RL         MAND    SIG

   ACCOUNT_TYPE                         IDENTIFICATIONS_ID_SECTION
 0          CPM  <identification><type>B</type><number>03593300...
 1          CPM  <identification><type>B</type><number>03594679...

 [2 rows x 23 columns]}

In [17]:
account_type

'PPH'

In [15]:
account_rp

,CUSTOMER_TYPE,CUSTOMER_ID,GENDER,FIRST_NAME,LAST_NAME,BIRTHDATE,BIRTH_PLACE,NATIONALITY,RESIDENCE,ADDRESS_TYPE,ADDRESS,TOWN,CITY,ZIP,COUNTRY_CODE,OCCUPATION,ROLE_ACCOUNT,IDENTIFICATIONS_ID_SECTION
0,PPH,61625,M,MOHAMED SADEK,SNOUSSI,1996-09-22T00:00:00,TN - TORKI,TN,TN,1,TORKI GROMBALIA,GROMBALIA,N.A,8030,TN,Cadres de directions des services administrati...,TICPT,<identification><type>B</type><number>09860144...

In [7]:
from src.controller.transaction_router import TransactionRouter

In [8]:
transaction_router = TransactionRouter(TREANSACTION_CODE, DB_CONFIG)

2025-12-26 16:06:22,795 - INFO - Transaction codes loaded successfully.
2025-12-26 16:06:22,797 - INFO - EQAccountant initialized with logging enabled: True
2025-12-26 16:06:22,798 - INFO - T24Accountant initialized with logging enabled: True

Index(['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB',
       'TRANSACTION_DESC_ATB', 'APP_SOURCE', 'OP_TYPE',
       'Categorie_de_transaction', 'TRANSACTION_CODE_GOAML',
       'TRANSACTION_DESC_GOAML', 'FUND_CODE_1', 'FUND_CODE_2', 'IS_INTERFACE',
       'IS_MANUELLE'],
      dtype='object')

In [9]:
transaction_router.get_transactions(account, 2025)

2025-12-26 16:06:22,836 - INFO - Starting to retrieve accountant's transactions for account: 5820061625500, year: 2025

Connection established successfully.

2025-12-26 16:08:27,284 - INFO - Successfully executed query:
            SELECT
                'EQ' AS ACCOUNTANT_SOURCE,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE,
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT_LCY,
                'NA' AS TRANSACTION_AMOUNT_FCY,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5820061625500'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2025'

2025-12-26 16:08:27,306 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                'EQ' AS ACCOUNTANT_SOURCE,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE,
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT_LCY,
                'NA' AS TRANSACTION_AMOUNT_FCY,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5820061625500'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2025'

2025-12-26 16:08:27,314 - INFO - Query executed successfully. Accountant's transactions retrieved for the account.
2025-12-26 16:08:27,314 - INFO - Closing database connection.
2025-12-26 16:08:27,322 - INFO - Returning cleaned DataFrame.
2025-12-26 16:08:27,330 - INFO - Starting to retrieve T24 accountant's transactions for account: 2010284298, year: 2025

Connection closed.
Connection established successfully.

2025-12-26 16:10:17,420 - INFO - Successfully executed query:
            SELECT
                'T24' AS ACCOUNTANT_SOURCE,
                T24_ACCOUNTANT.SYSTEM_ID AS APP_SOURCE_CODE,
                T24_ACCOUNTANT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                --EQ_T24.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
                'NA' AS EQ_ACCOUNT,
                --EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                'NA' AS ORACLE_ACCOUNT,
                T24_ACCOUNTANT.TRANS_REFERENCE AS TRANSACTION_REF,
                'NA' AS TRANSACTION_SEQ,
                T24_ACCOUNTANT.VALUE_DATE AS TRANSACTION_DATE,
                T24_ACCOUNTANT.SYSTEM_DATE_TIME AS TRANSACTION_DATE_TS,
                T24_ACCOUNTANT.CURRENCY AS TRANSACTION_CURRENCY,
                'NA' AS TRANSACTION_AMOUNT,
                T24_ACCOUNTANT.AMOUNT_LCY AS TRANSACTION_AMOUNT_LCY,
                T24_ACCOUNTANT.AMOUNT_FCY AS TRANSACTION_AMOUNT_FCY,
                T24_ACCOUNTANT.TRANSACTION_CODE AS TRANSACTION_CODE_ATB,
                'NA' AS TRANSACTION_DESC_ATB
            FROM [MISDW].[TRG].[T24_FATB_STMT_ENTRY_2024] AS T24_ACCOUNTANT
            --INNER JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24 ON EQ_T24.GLOBUS_ACCT_NUMBER = T24_ACCOUNTANT.ACCOUNT_NUMBER
            --INNER JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            WHERE
                T24_ACCOUNTANT.ACCOUNT_NUMBER = '2010284298'
                AND SUBSTRING(T24_ACCOUNTANT.VALUE_DATE, 1, 4) = '2025'

2025-12-26 16:10:29,093 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                'T24' AS ACCOUNTANT_SOURCE,
                T24_ACCOUNTANT.SYSTEM_ID AS APP_SOURCE_CODE,
                T24_ACCOUNTANT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                --EQ_T24.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
                'NA' AS EQ_ACCOUNT,
                --EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                'NA' AS ORACLE_ACCOUNT,
                T24_ACCOUNTANT.TRANS_REFERENCE AS TRANSACTION_REF,
                'NA' AS TRANSACTION_SEQ,
                T24_ACCOUNTANT.VALUE_DATE AS TRANSACTION_DATE,
                T24_ACCOUNTANT.SYSTEM_DATE_TIME AS TRANSACTION_DATE_TS,
                T24_ACCOUNTANT.CURRENCY AS TRANSACTION_CURRENCY,
                'NA' AS TRANSACTION_AMOUNT,
                T24_ACCOUNTANT.AMOUNT_LCY AS TRANSACTION_AMOUNT_LCY,
                T24_ACCOUNTANT.AMOUNT_FCY AS TRANSACTION_AMOUNT_FCY,
                T24_ACCOUNTANT.TRANSACTION_CODE AS TRANSACTION_CODE_ATB,
                'NA' AS TRANSACTION_DESC_ATB
            FROM [MISDW].[TRG].[T24_FATB_STMT_ENTRY_2024] AS T24_ACCOUNTANT
            --INNER JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24 ON EQ_T24.GLOBUS_ACCT_NUMBER = T24_ACCOUNTANT.ACCOUNT_NUMBER
            --INNER JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            WHERE
                T24_ACCOUNTANT.ACCOUNT_NUMBER = '2010284298'
                AND SUBSTRING(T24_ACCOUNTANT.VALUE_DATE, 1, 4) = '2025'

2025-12-26 16:10:29,101 - INFO - Query executed successfully. T24 accountant's transactions retrieved for the account.
2025-12-26 16:10:29,102 - INFO - Closing database connection.
2025-12-26 16:10:29,110 - INFO - Returning cleaned DataFrame.

Connection closed.
==================  1 - unified_accountant ==================
<class 'pandas.core.frame.DataFrame'>
Index: 425 entries, 59 to 290
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ACCOUNTANT_SOURCE       425 non-null    object
 1   APP_SOURCE_CODE         425 non-null    object
 2   T24_ACCOUNT             425 non-null    object
 3   EQ_ACCOUNT              425 non-null    object
 4   ORACLE_ACCOUNT          425 non-null    object
 5   TRANSACTION_REF         425 non-null    object
 6   TRANSACTION_SEQ         425 non-null    object
 7   TRANSACTION_DATE        425 non-null    object
 8   TRANSACTION_DATE_TS     194 non-null    object
 9   TRANSACTION_CURRENCY    425 non-null    object
 10  TRANSACTION_AMOUNT      425 non-null    object
 11  TRANSACTION_AMOUNT_LCY  425 non-null    object
 12  TRANSACTION_AMOUNT_FCY  231 non-null    object
 13  TRANSACTION_CODE_ATB    425 non-null    object
 14  TRANSACTION_DESC_ATB    425 non-null    object
dtypes: object(15)
memory usage: 53.1+ KB
None
=========================================================
==================  2 - accountant_transactions_with_trx_code ==================
<class 'pandas.core.frame.DataFrame'>
Index: 424 entries, 0 to 424
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ACCOUNTANT_SOURCE         424 non-null    object
 1   APP_SOURCE_CODE           424 non-null    object
 2   T24_ACCOUNT               424 non-null    object
 3   EQ_ACCOUNT                424 non-null    object
 4   ORACLE_ACCOUNT            424 non-null    object
 5   TRANSACTION_REF           424 non-null    object
 6   TRANSACTION_SEQ           424 non-null    object
 7   TRANSACTION_DATE          424 non-null    object
 8   TRANSACTION_DATE_TS       194 non-null    object
 9   TRANSACTION_CURRENCY      424 non-null    object
 10  TRANSACTION_AMOUNT        424 non-null    object
 11  TRANSACTION_AMOUNT_LCY    424 non-null    object
 12  TRANSACTION_AMOUNT_FCY    230 non-null    object
 13  TRANSACTION_CODE_ATB      424 non-null    object
 14  TRANSACTION_DESC_ATB_ACC  424 non-null    object
 15  OP_TYPE                   177 non-null    object
 16  APP_SOURCE                177 non-null    object
 17  TRANSACTION_DESC_ATB_F    230 non-null    object
 18  Categorie_de_transaction  191 non-null    object
 19  TRANSACTION_DESC_GOAML    177 non-null    object
 20  TRANSACTION_CODE_GOAML    177 non-null    object
 21  FUND_CODE_1               177 non-null    object
 22  FUND_CODE_2               177 non-null    object
 23  IS_INTERFACE              177 non-null    object
 24  IS_MANUELLE               0 non-null      object
dtypes: object(25)
memory usage: 86.1+ KB
None
=========================================================

In [10]:
transaction_router.accountant_transactions_with_trx_code[ transaction_router.accountant_transactions_with_trx_code ['TRANSACTION_REF']== 'TT25300DLJFP'].T

                                                                        424
ACCOUNTANT_SOURCE                                                       T24
APP_SOURCE_CODE                                                          TT
T24_ACCOUNT                                                      2010284298
EQ_ACCOUNT                                                               NA
ORACLE_ACCOUNT                                                           NA
TRANSACTION_REF                                                TT25300DLJFP
TRANSACTION_SEQ                                                          NA
TRANSACTION_DATE                                                   20251027
TRANSACTION_DATE_TS                                       20251027103126910
TRANSACTION_CURRENCY                                                    TND
TRANSACTION_AMOUNT                                                       NA
TRANSACTION_AMOUNT_LCY                                            -2500.000
TRANSACTION_AMOUNT_FCY                                                 None
TRANSACTION_CODE_ATB                                                   1013
TRANSACTION_DESC_ATB_ACC                                                 NA
OP_TYPE                                                              Caisse
APP_SOURCE                                                           Teller
TRANSACTION_DESC_ATB_F                  Retrait Especes  Meme Agence
Categorie_de_transaction  code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML                          Retrait Especes Meme Agence
TRANSACTION_CODE_GOAML                                                 B200
FUND_CODE_1                                                               A
FUND_CODE_2                                                               K
IS_INTERFACE                                                              N
IS_MANUELLE                                                             NaN

In [12]:
# Check for duplicates on the merge keys
duplicate_mask = transaction_router.accountant_transactions_with_trx_code.duplicated(
    subset=['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'APP_SOURCE', 'OP_TYPE', 'TRANSACTION_CODE_ATB', 'TRANSACTION_REF', 'TRANSACTION_DATE'], 
    keep=False  # Mark all duplicates (not just first/last)
)
 
# Show all duplicate rows
duplicates = transaction_router.accountant_transactions_with_trx_code[duplicate_mask]
duplicates.sort_values(['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB'])

Empty DataFrame
Columns: [ACCOUNTANT_SOURCE, APP_SOURCE_CODE, T24_ACCOUNT, EQ_ACCOUNT, ORACLE_ACCOUNT, TRANSACTION_REF, TRANSACTION_SEQ, TRANSACTION_DATE, TRANSACTION_DATE_TS, TRANSACTION_CURRENCY, TRANSACTION_AMOUNT, TRANSACTION_AMOUNT_LCY, TRANSACTION_AMOUNT_FCY, TRANSACTION_CODE_ATB, TRANSACTION_DESC_ATB_ACC, OP_TYPE, APP_SOURCE, TRANSACTION_DESC_ATB_F, Categorie_de_transaction, TRANSACTION_DESC_GOAML, TRANSACTION_CODE_GOAML, FUND_CODE_1, FUND_CODE_2, IS_INTERFACE, IS_MANUELLE]
Index: []

[0 rows x 25 columns]

In [11]:
rr = transaction_router.accountant_transactions_with_trx_code.drop_duplicates(
    subset=['T24_ACCOUNT', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB', 'TRANSACTION_DATE', 'TRANSACTION_REF', 'TRANSACTION_SEQ']
)

In [12]:
rr[ rr['TRANSACTION_REF']== 'TT25300DLJFP']

,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,...,OP_TYPE,APP_SOURCE,TRANSACTION_DESC_ATB_F,Categorie_de_transaction,TRANSACTION_DESC_GOAML,TRANSACTION_CODE_GOAML,FUND_CODE_1,FUND_CODE_2,IS_INTERFACE,IS_MANUELLE
424,T24,TT,2010284298,NA,NA,TT25300DLJFP,NA,20251027,20251027103126910,TND,...,Caisse,Teller,Retrait Especes,code affectant directement le compte client (d...,Retrait Especes Meme Agence,B200,A,K,N,NaN

In [13]:
transaction_router.t24_accountant.accountant_transactions

,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_AMOUNT_LCY,TRANSACTION_AMOUNT_FCY,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB
0,T24,FT,2010284298,NA,NA,FT2511404VZCM2BY,NA,20250424,20250424131857768,TND,NA,-18.000,None,8010,NA
1,T24,FT,2010284298,NA,NA,FT25065105FVCTVG,NA,20250306,20250306130949426,TND,NA,-167.944,None,8439,NA
2,T24,FT,2010284298,NA,NA,FT25332041FWV39L,NA,20251128,20251128151519716,TND,NA,-500.000,None,8427,NA
3,T24,FT,2010284298,NA,NA,FT250660XC5HWDW6,NA,20250307,20250307085149192,TND,NA,-167.944,None,8439,NA
4,T24,FT,2010284298,NA,NA,FT251391517SC3LP,NA,20250519,20250519113154689,TND,NA,-16.325,None,8439,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,T24,FT,2010284298,NA,NA,FT252520H1BRBHG3,NA,20250909,20250909114006388,TND,NA,-70.650,None,8439,NA
192,T24,FT,2010284298,NA,NA,FT253090MX04Z4H1,NA,20251105,20251105110713663,TND,NA,-201.600,None,8427,NA
193,T24,FT,2010284298,NA,NA,FT252690ZQ8RS6C7,NA,20250926,20250926112956768,TND,NA,-82.000,None,8439,NA
194,T24,FT,2010284298,NA,NA,FT253560XH6L3B3L,NA,20251222,20251221104758057,TND,NA,-600.000,None,8439,NA
195,T24,FT,2010284298,NA,NA,FT253160SD3LZV3T,NA,20251112,20251112161525548,TND,NA,-82.000,None,8439,NA

In [14]:
transaction_router.t24_accountant.accountant_transactions[transaction_router.t24_accountant.accountant_transactions['TRANSACTION_REF']== 'TT25300DLJFP'].T

                                      124
ACCOUNTANT_SOURCE                     T24
APP_SOURCE_CODE                        TT
T24_ACCOUNT                    2010284298
EQ_ACCOUNT                             NA
ORACLE_ACCOUNT                         NA
TRANSACTION_REF              TT25300DLJFP
TRANSACTION_SEQ                        NA
TRANSACTION_DATE                 20251027
TRANSACTION_DATE_TS     20251027103126910
TRANSACTION_CURRENCY                  TND
TRANSACTION_AMOUNT                     NA
TRANSACTION_AMOUNT_LCY          -2500.000
TRANSACTION_AMOUNT_FCY               None
TRANSACTION_CODE_ATB                 1013
TRANSACTION_DESC_ATB                   NA

In [15]:
import pandas as pd

In [17]:
r1 = pd.concat(
    [
        transaction_router.eq_accountant.accountant_transactions,
        transaction_router.t24_accountant.accountant_transactions
    ],
    ignore_index=True
)

In [31]:
r1[r1['TRANSACTION_REF'] == 'TT25300DLJFP']

,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_AMOUNT_LCY,TRANSACTION_AMOUNT_FCY,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB
8,EQ,T24TL,2010284298,5820061625500,0201119826975,TT25300DLJFP,323,1251027,None,TND,-2500.0000000000,-2500.0000000000,NA,067,Retrait Especes Meme Agence
372,T24,TT,2010284298,NA,NA,TT25300DLJFP,NA,20251027,20251027103126910,TND,NA,-2500.000,None,1013,NA

In [19]:
transaction_router.transaction_code

,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,IS_INTERFACE,IS_MANUELLE
0,EQ,T24TL,297,Comm.OPPOS EFFET,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN,Y,NaN
1,EQ,UAJL,920,Interets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,EQ,@@CC,120,Remb avance placement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,EQ,TLVIR,010,Debit,IBANK,Virement,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,EQ,@@FM,401,Exchange Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4025,T24,TT,4241,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN,N,NaN
4026,T24,TT,4240,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN,N,NaN
4027,T24,TT,7278,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN,N,NaN
4028,T24,TT,4244,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN,N,NaN
4029,T24,TT,4243,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN,N,NaN

In [44]:
r1[r1['TRANSACTION_REF'] == 'TT25300DLJFP'][['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB']]

    ACCOUNTANT_SOURCE APP_SOURCE_CODE TRANSACTION_CODE_ATB
8                  EQ           T24TL                  067
372               T24              TT                 1013

In [38]:
r2=pd.merge(
    left=r1[r1['TRANSACTION_REF'] == 'TT25300DLJFP'],
    right=transaction_router.transaction_code[['ACCOUNTANT_SOURCE', 'OP_TYPE', 'APP_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB', 'TRANSACTION_DESC_ATB', 'Categorie_de_transaction', 'TRANSACTION_DESC_GOAML', 'TRANSACTION_CODE_GOAML', 'FUND_CODE_1', 'FUND_CODE_2', 'IS_INTERFACE', 'IS_MANUELLE']].copy(deep=True),
    left_on=['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB'],
    right_on=['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB'],
    how='left',
    suffixes=('_ACC', '_F') # accountant, param trx code file
)

In [41]:
r2.T

,0,1,2
ACCOUNTANT_SOURCE,EQ,T24,T24
APP_SOURCE_CODE,T24TL,TT,TT
T24_ACCOUNT,2010284298,2010284298,2010284298
EQ_ACCOUNT,5820061625500,NA,NA
ORACLE_ACCOUNT,0201119826975,NA,NA
TRANSACTION_REF,TT25300DLJFP,TT25300DLJFP,TT25300DLJFP
TRANSACTION_SEQ,323,NA,NA
TRANSACTION_DATE,1251027,20251027,20251027
TRANSACTION_DATE_TS,None,20251027103126910,20251027103126910
TRANSACTION_CURRENCY,TND,TND,TND
TRANSACTION_AMOUNT,-2500.0000000000,NA,NA
TRANSACTION_AMOUNT_LCY,-2500.0000000000,-2500.000,-2500.000
TRANSACTION_AMOUNT_FCY,NA,None,None
TRANSACTION_CODE_ATB,067,1013,1013
TRANSACTION_DESC_ATB_ACC,Retrait Especes Meme Agence,NA,NA
OP_TYPE,Caisse,Caisse,Caisse
APP_SOURCE,Teller,Teller,Teller
TRANSACTION_DESC_ATB_F,Retrait Especes Meme Agence,Retrait Especes,Retrait Especes Meme Agence
Categorie_de_transaction,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML,Retrait Especes Meme Agence,Retrait Especes Meme Agence,Retrait Especes Meme Agence
TRANSACTION_CODE_GOAML,B200,B200,B200
FUND_CODE_1,A,A,A
FUND_CODE_2,K,K,K
IS_INTERFACE,Y,N,N
IS_MANUELLE,NaN,NaN,NaN

In [25]:
transaction_router.transaction_code[transaction_router.transaction_code.duplicated()]

,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,IS_INTERFACE,IS_MANUELLE
2678,EQ,AABS5,410,Branch Settle - Due From,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2762,EQ,AABS,410,Branch Settle - Due From,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2918,EQ,AABS5,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2942,EQ,AABS2,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2981,EQ,AABS,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Check for duplicates on the merge keys
duplicate_mask = transaction_router.transaction_code.duplicated(
    subset=['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB'], 
    keep=False  # Mark all duplicates (not just first/last)
)
 
# Show all duplicate rows
duplicates = transaction_router.transaction_code[duplicate_mask]
duplicates.sort_values(['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'APP_SOURCE', 'OP_TYPE', 'TRANSACTION_CODE_ATB'])

,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,IS_INTERFACE,IS_MANUELLE
1325,EQ,AABS,410,Branch Settle - Due From,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2762,EQ,AABS,410,Branch Settle - Due From,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1466,EQ,AABS,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2981,EQ,AABS,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1439,EQ,AABS2,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2942,EQ,AABS2,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1257,EQ,AABS5,410,Branch Settle - Due From,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2678,EQ,AABS5,410,Branch Settle - Due From,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1425,EQ,AABS5,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2918,EQ,AABS5,910,Branch Settle - Due To,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
transaction_router.eq_accountant.accountant_transactions[transaction_router.eq_accountant.accountant_transactions['TRANSACTION_REF']== 'TT25300DLJFP'].T

                                                   2
ACCOUNTANT_SOURCE                                 EQ
APP_SOURCE_CODE                                T24TL
T24_ACCOUNT                               2010284298
EQ_ACCOUNT                             5820061625500
ORACLE_ACCOUNT                         0201119826975
TRANSACTION_REF                         TT25300DLJFP
TRANSACTION_SEQ                                  323
TRANSACTION_DATE                             1251027
TRANSACTION_DATE_TS                             None
TRANSACTION_CURRENCY                             TND
TRANSACTION_AMOUNT                  -2500.0000000000
TRANSACTION_AMOUNT_LCY              -2500.0000000000
TRANSACTION_AMOUNT_FCY                            NA
TRANSACTION_CODE_ATB                             067
TRANSACTION_DESC_ATB    Retrait Especes  Meme Agence

In [15]:
account_correspondences

{'T24_ACCOUNT': '2000720518',
 'EQ_ACCOUNT': '5825211792580',
 'ORACLE_ACCOUNT': '0251120006141'}

In [25]:
customer_id

'383430'

In [26]:
account_type

'PM'

In [27]:
account_rp

,CUSTOMER_ID,CUSTOMER_TYPE,GENDER,FIRST_NAME,LAST_NAME,BIRTHDATE,BIRTH_PLACE,NATIONALITY,RESIDENCE,ADDRESS_TYPE,...,CITY,ZIP,COUNTRY_CODE,OCCUPATION,RELATED_PERSON_RELATION_CODE_ATB,RELATED_PERSON_ROLE_CODE_ATB,ROLE_ENTITY,ROLE_ACCOUNT,SOURCE,IDENTIFICATIONS_ID_SECTION
0,46300,TRPP,M,MOHAMED,ALOUINI,1984-08-11T00:00:00,TN,TN,TN,1,...,N.A,3100,TN,Dirigeants et gerants dans le commerce de gros...,307,50,CUSTOMER_ID : 46300 N.A - ROLE_CODE_goAML,MAND,TIER,<identification><type>B</type><number>07652027...

In [8]:
print(account_details)

        <IB_account>
            <institution_name>ARAB TUNISIAN BANK</institution_name>
            <swift>ATBKTNTT</swift>
            <account>01001020111982697533</account>
            <currency_code>TND</currency_code>
            <account_name>T24 - MOHAMED SADEK SNOUSSI</account_name>
            <personal_account_type>1CHQ</personal_account_type>

            <related_persons>
                        <account_related_person>
                <t_person>
                    <gender>M</gender>
                    <first_name>MOHAMED SADEK</first_name>
                    <last_name>SNOUSSI</last_name>
                    <birthdate>1996-09-22T00:00:00</birthdate>
                    <birth_place>TN - TORKI</birth_place>
                    <nationality1>TN</nationality1>
                    <residence>TN</residence>
                    <addresses>
                        <address>
                            <address_type>1</address_type>
                            <address>N.A - address - CustomerID: 61625</address>
                            <town>GROMBALIA</town>
                            <city>N.A - city - CustomerID: 61625</city>
                            <zip>8030</zip>
                            <country_code>TN</country_code>
                        </address>
                    </addresses>
                    <occupation>Cadres de directions des services administratifs et financiers</occupation>
                    <identifications>
                        <identification><type>B</type><number>09860144</number><issue_date>2021-04-15T00:00:00</issue_date><issue_country>TN</issue_country></identification>
                    </identifications>
                </t_person>
                <role>TICPT</role>
            </account_related_person>
            </related_persons>
            <opened>2023-01-31T00:00:00</opened>

            <balance>49727.951</balance>
            <date_balance>2025-10-27T07:36:41</date_balance>
            <status_code>A</status_code>
        </IB_account>

In [9]:
account_rp

,CUSTOMER_ID,CUSTOMER_TYPE,GENDER,FIRST_NAME,LAST_NAME,BIRTHDATE,BIRTH_PLACE,NATIONALITY,RESIDENCE,ADDRESS_TYPE,ZIP,ADDRESS,COUNTRY_CODE,OCCUPATION,RELATED_PERSON_RELATION_CODE_ATB,RELATED_PERSON_ROLE_CODE_ATB,ROLE_ENTITY,ROLE_ACCOUNT,IDENTIFICATIONS_ID_SECTION
0,148147,PPH,M,ILHEM,BOUGUACHA,1970-01-10T00:00:00,TN,TN,TN,1,3000,TN - SFAX - SFAX MEDINA - AV FARHAT HACHED R H...,TN,Secretaires,307,60,CUSTOMER_ID : 148147 N.A - ROLE_CODE_goAML,MAND,<identification><type>B</type><number>05265654...
1,150794,PPH,M,CHOKRI,LEHIANI,1963-09-15T00:00:00,TN,TN,TN,1,3000,TN - SFAX - SFAX.MEDINA - AV FARHAT HACHED RUE...,TN,Directeurs d'entreprises,302,60,CUSTOMER_ID : 150794 N.A - ROLE_CODE_goAML,MAND,<identification><type>B</type><number>01280519...
2,150794,PPH,M,CHOKRI,LEHIANI,1963-09-15T00:00:00,TN,TN,TN,1,3000,TN - SFAX - SFAX.MEDINA - AV FARHAT HACHED RUE...,TN,Directeurs d'entreprises,303,20,CUSTOMER_ID : 150794 N.A - ROLE_CODE_goAML,MAND,<identification><type>B</type><number>01280519...
3,148147,PPH,M,ILHEM,BOUGUACHA,1970-01-10T00:00:00,TN,TN,TN,1,3000,TN - SFAX - SFAX MEDINA - AV FARHAT HACHED R H...,TN,Secretaires,307,None,CUSTOMER_ID : 148147 N.A - ROLE_CODE_goAML,MAND,<identification><type>B</type><number>05265654...
4,150794,PPH,M,CHOKRI,LEHIANI,1963-09-15T00:00:00,TN,TN,TN,1,3000,TN - SFAX - SFAX.MEDINA - AV FARHAT HACHED RUE...,TN,Directeurs d'entreprises,N.A,SIGNATAIRE,RL,MAND,<identification><type>B</type><number>01280519...

In [18]:
import pandas as pd

In [19]:
data = [[1, 'Joe', 70000, 3], [2, 'Henry', 80000, 4], [3, 'Sam', 60000, None], [4, 'Max', 90000, None]]
employee = pd.DataFrame(data, columns=['id', 'name', 'salary', 'managerId']).astype({'id':'Int64', 'name':'object', 'salary':'Int64', 'managerId':'Int64'})

In [20]:
employee

   id   name  salary  managerId
0   1    Joe   70000          3
1   2  Henry   80000          4
2   3    Sam   60000       <NA>
3   4    Max   90000       <NA>

In [31]:
pd.merge(
    left=employee,
    right=employee,
    left_on='managerId',
    right_on='id',
    suffixes=('_emp', '_mng')
).loc[lambda row : row['salary_emp'] > row['salary_mng'], ['name_emp']].rename(columns={'name_emp':'Employee'})

  Employee
0      Joe

In [32]:
merged_df = pd.merge(
    left=employee,
    right=employee,
    left_on='managerId',
    right_on='id',
    suffixes=('_emp', '_mng')
)

In [37]:
merged_df['salary_emp'] > merged_df['salary_mng']

0     True
1    False
dtype: boolean

In [35]:
merged_df[merged_df['salary_emp'] > merged_df['salary_mng']]

,id_emp,name_emp,salary_emp,managerId_emp,id_mng,name_mng,salary_mng,managerId_mng
0,1,Joe,70000,3,3,Sam,60000,<NA>

In [38]:
data = [[1, 'a@b.com'], [2, 'c@d.com'], [3, 'a@b.com']]
person = pd.DataFrame(data, columns=['id', 'email']).astype({'id':'Int64', 'email':'object'})

In [39]:
person

   id    email
0   1  a@b.com
1   2  c@d.com
2   3  a@b.com

In [46]:
person.groupby('email').count().reset_index().rename(columns={'email':'Email', 'id':'count'}).loc[lambda row: row['count'] > 1, ['Email']]

     Email
0  a@b.com

In [48]:
person

   id    email
0   1  a@b.com
1   2  c@d.com
2   3  a@b.com

In [54]:
person[person.duplicated(subset='email', keep=False)].drop_duplicates(subset='email', keep='first')

   id    email
0   1  a@b.com