In [1]:
import sys
sys.path.append('../')

In [2]:
from src.config import DB_CONFIG, TREANSACTION_CODE

In [3]:
from src.model.get_client_T24 import GetClientT24

In [4]:
get_client_T24 = GetClientT24(DB_CONFIG)

In [5]:
account_number = '5812273189500'
print(get_client_T24.account_status_lookup(account_number)) # True -> Active Account

account_correspondences, account_details, customer_id, account_type, account_rp = get_client_T24.get_client(account_number)

2025-04-28 07:25:18,852 - INFO - Executing account status lookup for account: 5812273189500

Connection established successfully.

2025-04-28 07:25:19,358 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5812273189500'

2025-04-28 07:25:19,359 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5812273189500'

2025-04-28 07:25:19,361 - INFO - Account 5812273189500 is IS_ACTIVE
2025-04-28 07:25:19,408 - INFO - Executing account status lookup for account: 5812273189500

Connection closed.
True
Connection established successfully.

2025-04-28 07:25:19,817 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5812273189500'

2025-04-28 07:25:19,818 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5812273189500'

2025-04-28 07:25:19,820 - INFO - Account 5812273189500 is IS_ACTIVE
2025-04-28 07:25:19,897 - INFO - Executing query to retrieve account information for account number: 5812273189500

Connection closed.
Connection established successfully.

2025-04-28 07:25:29,233 - INFO - Successfully executed query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5812273189500'

2025-04-28 07:25:29,238 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5812273189500'

2025-04-28 07:25:29,246 - INFO - Successfully retrieved account information for account number: 5812273189500
2025-04-28 07:25:29,311 - INFO - Executing query to retrieve arrangement information for arrangement id : AA22101SFS0P

Connection closed.
Connection established successfully.

2025-04-28 07:25:31,145 - INFO - Successfully executed query:
        SELECT
            LEFT(RECID, CHARINDEX('-', RECID) - 1) AS ARRANGEMENT_ID,
            CUSTOMER_3,
            CUSTOMER_ROLE_4,
            L_ACCT_TYPE
        FROM [MISDW].[GO_AML].[T24_FATB_AA_ARR_CUSTOMER]
        WHERE
            LEFT(RECID, CHARINDEX('-', RECID) - 1) = 'AA22101SFS0P'

2025-04-28 07:25:31,147 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            LEFT(RECID, CHARINDEX('-', RECID) - 1) AS ARRANGEMENT_ID,
            CUSTOMER_3,
            CUSTOMER_ROLE_4,
            L_ACCT_TYPE
        FROM [MISDW].[GO_AML].[T24_FATB_AA_ARR_CUSTOMER]
        WHERE
            LEFT(RECID, CHARINDEX('-', RECID) - 1) = 'AA22101SFS0P'

2025-04-28 07:25:31,149 - INFO - Successfully retrieved account information for arrangement id : AA22101SFS0P
2025-04-28 07:25:31,199 - INFO - Starting to retrieve PPH data for customer ID 273189

Connection closed.
  ARRANGEMENT_ID CUSTOMER_ID CUSTOMER_ROLE L_ACCT_TYPE
0   AA22101SFS0P      273189         OWNER           3
The DataFrame has only one record, and CUSTOMER_ROLE is OWNER.
Connection established successfully.

2025-04-28 07:25:31,490 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '273189'

2025-04-28 07:25:31,492 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '273189'

2025-04-28 07:25:31,497 - INFO - Retrieved PPH data successfully for customer ID 273189
2025-04-28 07:25:31,553 - INFO - Executing query to retrieve mandates information for account mandate id : None
2025-04-28 07:25:31,630 - INFO - Successfully executed query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = 'None'

2025-04-28 07:25:31,632 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = 'None'

Connection closed.
Connection established successfully.

2025-04-28 07:25:36,634 - WARNING - Failed to execute query after 1 attempts
2025-04-28 07:25:36,637 - WARNING - No data found for account mandate id : None

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME   LAST_NAME  \
0           PPH      273189      M      LOTFI  BEN FARHAT

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1969-11-14T00:00:00  TN - Tunis            CIN  05146654             TN

        LEGAL_ISS_DATE LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  2011-04-20T00:00:00           None          TN        TN            1

    ZIP                                            ADDRESS COUNTRY_CODE  \
0  2066  TN - TUNIS - EL.KABARIA - BLOC B6 APPRT 145 RE...           TN

                                   OCCUPATION ROLE_ACCOUNT
0  Dirigeants et gerants non classes ailleurs        TICPT
==================
+++++++++++++++

In [7]:
account = {
    'account_number': account_number,
    'account_correspondences': account_correspondences,
    'account_detail': account_details,
    'customer_id': customer_id,
    'account_type': account_type,
    'account_rp': account_rp
}

In [8]:
from src.controller.transaction_router import TransactionRouter

In [9]:
transaction_router = TransactionRouter(TREANSACTION_CODE, DB_CONFIG)

2025-04-28 07:27:10,887 - INFO - Transaction codes loaded successfully.
2025-04-28 07:27:10,888 - INFO - EQAccountant initialized with logging enabled: True

Index(['APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB', 'TRANSACTION_DESC_ATB',
       'APP_SOURCE', 'OP_TYPE', 'Categorie_de_transaction',
       'TRANSACTION_CODE_GOAML', 'TRANSACTION_DESC_GOAML', 'FUND_CODE_1',
       'FUND_CODE_2', '_merge'],
      dtype='object')

In [10]:
year = '2025'
transaction_router.clear_cash()
transaction_router.get_transactions(account, year)

2025-04-28 07:27:14,995 - INFO - Starting to retrieve accountant's transactions for account: 5812273189500, year: 2025

Connection established successfully.

2025-04-28 07:31:03,613 - INFO - Successfully executed query:
            SELECT
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5812273189500'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2025'

2025-04-28 07:32:05,047 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5812273189500'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2025'

2025-04-28 07:32:05,054 - INFO - Query executed successfully. Accountant's transactions retrieved for the account.
2025-04-28 07:32:05,055 - INFO - Closing database connection.
2025-04-28 07:32:05,078 - INFO - Returning cleaned DataFrame.
2025-04-28 07:32:05,128 - INFO - Starting retrieval of cards for account: 0891110000737
2025-04-28 07:32:05,138 - INFO - Executing query for account: 0891110000737
2025-04-28 07:32:05,251 - INFO - Successfully executed query:
            SELECT
                CUSTOMER_CARDHOLDER.CUS_IDEN AS ORACLE_ACC,
                CUSTOMER_CARDHOLDER.CUS_CODE AS CARD_ID,
                CARDS.CAR_NUMB AS CARD_NUMBER,
                CUSTOMER_CARDHOLDER.CUS_FIRS_NAM1 AS CARD_HOLDER_NAME,
                CUSTOMER_CARDHOLDER.CUS_FIRS_IDE1 AS CARD_HOLDER_LEGAL_ID
            FROM [MISDW].[TRG].[ATM_CUSTOMER_CARDHOLDER] AS CUSTOMER_CARDHOLDER
            LEFT JOIN [MISDW].[TRG].[ATM_CARDS] AS CARDS ON CARDS.CAR_CUS_CODE = CUSTOMER_CARDHOLDER.CUS_CODE
            WHERE
                CUSTOMER_CARDHOLDER.CUS_IDEN = '0891110000737'

2025-04-28 07:32:05,254 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                CUSTOMER_CARDHOLDER.CUS_IDEN AS ORACLE_ACC,
                CUSTOMER_CARDHOLDER.CUS_CODE AS CARD_ID,
                CARDS.CAR_NUMB AS CARD_NUMBER,
                CUSTOMER_CARDHOLDER.CUS_FIRS_NAM1 AS CARD_HOLDER_NAME,
                CUSTOMER_CARDHOLDER.CUS_FIRS_IDE1 AS CARD_HOLDER_LEGAL_ID
            FROM [MISDW].[TRG].[ATM_CUSTOMER_CARDHOLDER] AS CUSTOMER_CARDHOLDER
            LEFT JOIN [MISDW].[TRG].[ATM_CARDS] AS CARDS ON CARDS.CAR_CUS_CODE = CUSTOMER_CARDHOLDER.CUS_CODE
            WHERE
                CUSTOMER_CARDHOLDER.CUS_IDEN = '0891110000737'

2025-04-28 07:32:05,256 - INFO - Query executed successfully; card data retrieved for account: 0891110000737
2025-04-28 07:32:05,257 - INFO - Starting to retrieve PPH data for customer ID 05146654

Connection closed.
============*********==============
Index(['T24_ACCOUNT', 'EQ_ACCOUNT', 'ORACLE_ACCOUNT', 'TRANSACTION_REF',
       'TRANSACTION_SEQ', 'TRANSACTION_DATE', 'TRANSACTION_DATE_TS',
       'TRANSACTION_CURRENCY', 'TRANSACTION_AMOUNT', 'TRANSACTION_CODE_ATB',
       'TRANSACTION_DESC_ATB_ACC', 'APP_SOURCE_CODE', 'TRANSACTION_DESC_ATB_F',
       'APP_SOURCE', 'OP_TYPE', 'Categorie_de_transaction',
       'TRANSACTION_DESC_GOAML', 'TRANSACTION_CODE_GOAML', 'FUND_CODE_1',
       'FUND_CODE_2'],
      dtype='object')
============================== transaction router - card =========================================
=======================================================================
card router
    T24_ACCOUNT     EQ_ACCOUNT ORACLE_ACCOUNT   TRANSACTION_REF  \
0    2002611131  5812273189500  0891110000737     S001444178509
1    2002611131  5812273189500  0891110000737     S808700801457
2    2002611131  5812273189500  0891110000737     S104003057221
3    2002611131  5812273189500  0891110000737     S808700439326
4    2002611131  5812273189500  0891110000737     S030000809772
..          ...            ...            ...               ...
171  2002611131  5812273189500  0891110000737  C210425075267357
172  2002611131  5812273189500  0891110000737  C210425075269117
173  2002611131  5812273189500  0891110000737  C220425073819453
174  2002611131  5812273189500  0891110000737  C230425073622389
175  2002611131  5812273189500  0891110000737  C240425072624189

    TRANSACTION_SEQ TRANSACTION_DATE TRANSACTION_DATE_TS TRANSACTION_CURRENCY  \
0              2665          1250107                None                  TND
1             34893          1250109                None                  TND
2              9329          1250110                None                  TND
3             79631          1250113                None                  TND
4              6355          1250116                None                  TND
..              ...              ...                 ...                  ...
171           23809          1250422                None                  TND
172           21488          1250422                None                  TND
173            2924          1250423                None                  TND
174           14342          1250424                None                  TND
175            7481          1250425                None                  TND

    TRANSACTION_AMOUNT TRANSACTION_CODE_ATB TRANSACTION_DESC_ATB_ACC  \
0      -201.6000000000                  427              Retrait GAB
1      -131.3900000000                  427              Retrait GAB
2      -400.0000000000                  427              Retrait GAB
3      -101.3000000000                  427              Retrait GAB
4       -51.1500000000                  427              Retrait GAB
..                 ...                  ...                      ...
171     -42.0000000000                  439       Paiement par carte
172     -31.8000000000                  439       Paiement par carte
173     -21.4900000000                  439       Paiement par carte
174     -34.0000000000                  439       Paiement par carte
175    -100.0000000000                  439       Paiement par carte

    APP_SOURCE_CODE               TRANSACTION_DESC_ATB_F APP_SOURCE OP_TYPE  \
0              @@O2  Retrait GAB                              IBANK   Carte
1              @@O2  Retrait GAB                              IBANK   Carte
2              @@O2  Retrait GAB                              IBANK   Carte
3              @@O2  Retrait GAB                              IBANK   Carte
4              @@O2  Retrait GAB                              IBANK   Carte
..              ...                                  ...        ...     ...
171           MXPCP  Paiement par carte                       IBANK   Carte
172           MXPCP  Paiement par carte                       IBANK   Carte
173           MXPCP  Paiement par carte                       IBANK   Carte
174           MXPCP  Paiement par carte                       IBANK   Carte
175           MXPCP  Paiement par carte                       IBANK   Carte

                              Categorie_de_transaction  \
0    code affectant directement le compte client (d...
1    code affectant directement le compte client (d...
2    code affectant directement le compte client (d...
3    code affectant directement le compte client (d...
4    code affectant directement le compte client (d...
..                                                 ...
171  code affectant directement le compte client (d...
172  code affectant directement le compte client (d...
173  code affectant directement le compte client (d...
174  code affectant directement le compte client (d...
175  code affectant directement le compte client (d...

                        TRANSACTION_DESC_GOAML TRANSACTION_CODE_GOAML  \
0     Retrait par cartes électroniques locales                   B393
1     Retrait par cartes électroniques locales                   B393
2     Retrait par cartes électroniques locales                   B393
3     Retrait par cartes électroniques locales                   B393
4     Retrait par cartes électroniques locales                   B393
..                                         ...                    ...
171  Paiement par cartes électroniques locales                   B108
172  Paiement par cartes électroniques locales                   B108
173  Paiement par cartes électroniques locales                   B108
174  Paiement par cartes électroniques locales                   B108
175  Paiement par cartes électroniques locales                   B108

    FUND_CODE_1 FUND_CODE_2
0             A           K
1             A           K
2             A           K
3             A           K
4             A           K
..          ...         ...
171           A           A
172           A           A
173           A           A
174           A           A
175           A           A

[159 rows x 20 columns]
self.account_related_cards is empty
Connection established successfully.
Connection established successfully.

2025-04-28 07:32:06,310 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:06,312 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:06,316 - INFO - Retrieved PPH data successfully for customer ID 05146654
2025-04-28 07:32:06,343 - INFO - Starting to retrieve PPH data for customer ID 05146654

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME   LAST_NAME  \
0           PPH      273189      M      LOTFI  BEN FARHAT

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1969-11-14T00:00:00  TN - Tunis            CIN  05146654             TN

        LEGAL_ISS_DATE LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  2011-04-20T00:00:00           None          TN        TN            1

    ZIP                                            ADDRESS COUNTRY_CODE  \
0  2066  TN - TUNIS - EL.KABARIA - BLOC B6 APPRT 145 RE...           TN

                                   OCCUPATION
0  Dirigeants et gerants non classes ailleurs
==================
Connection established successfully.

2025-04-28 07:32:07,282 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:07,285 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:07,292 - INFO - Retrieved PPH data successfully for customer ID 05146654
2025-04-28 07:32:07,338 - INFO - Starting to retrieve PPH data for customer ID 05146654

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME   LAST_NAME  \
0           PPH      273189      M      LOTFI  BEN FARHAT

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1969-11-14T00:00:00  TN - Tunis            CIN  05146654             TN

        LEGAL_ISS_DATE LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  2011-04-20T00:00:00           None          TN        TN            1

    ZIP                                            ADDRESS COUNTRY_CODE  \
0  2066  TN - TUNIS - EL.KABARIA - BLOC B6 APPRT 145 RE...           TN

                                   OCCUPATION
0  Dirigeants et gerants non classes ailleurs
==================
Connection established successfully.

2025-04-28 07:32:08,188 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:08,190 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:08,193 - INFO - Retrieved PPH data successfully for customer ID 05146654
2025-04-28 07:32:08,225 - INFO - Starting to retrieve PPH data for customer ID 05146654

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME   LAST_NAME  \
0           PPH      273189      M      LOTFI  BEN FARHAT

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1969-11-14T00:00:00  TN - Tunis            CIN  05146654             TN

        LEGAL_ISS_DATE LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  2011-04-20T00:00:00           None          TN        TN            1

    ZIP                                            ADDRESS COUNTRY_CODE  \
0  2066  TN - TUNIS - EL.KABARIA - BLOC B6 APPRT 145 RE...           TN

                                   OCCUPATION
0  Dirigeants et gerants non classes ailleurs
==================
Connection established successfully.

2025-04-28 07:32:09,048 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:09,050 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:09,054 - INFO - Retrieved PPH data successfully for customer ID 05146654
2025-04-28 07:32:09,086 - INFO - Starting to retrieve PPH data for customer ID 05146654

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME   LAST_NAME  \
0           PPH      273189      M      LOTFI  BEN FARHAT

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1969-11-14T00:00:00  TN - Tunis            CIN  05146654             TN

        LEGAL_ISS_DATE LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  2011-04-20T00:00:00           None          TN        TN            1

    ZIP                                            ADDRESS COUNTRY_CODE  \
0  2066  TN - TUNIS - EL.KABARIA - BLOC B6 APPRT 145 RE...           TN

                                   OCCUPATION
0  Dirigeants et gerants non classes ailleurs
==================
Connection established successfully.

2025-04-28 07:32:09,944 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:09,947 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:09,952 - INFO - Retrieved PPH data successfully for customer ID 05146654
2025-04-28 07:32:09,985 - INFO - Starting to retrieve PPH data for customer ID 05146654

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME   LAST_NAME  \
0           PPH      273189      M      LOTFI  BEN FARHAT

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1969-11-14T00:00:00  TN - Tunis            CIN  05146654             TN

        LEGAL_ISS_DATE LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  2011-04-20T00:00:00           None          TN        TN            1

    ZIP                                            ADDRESS COUNTRY_CODE  \
0  2066  TN - TUNIS - EL.KABARIA - BLOC B6 APPRT 145 RE...           TN

                                   OCCUPATION
0  Dirigeants et gerants non classes ailleurs
==================
Connection established successfully.

2025-04-28 07:32:10,866 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:10,868 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:10,873 - INFO - Retrieved PPH data successfully for customer ID 05146654
2025-04-28 07:32:10,898 - INFO - Starting to retrieve PPH data for customer ID 05146654

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME   LAST_NAME  \
0           PPH      273189      M      LOTFI  BEN FARHAT

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1969-11-14T00:00:00  TN - Tunis            CIN  05146654             TN

        LEGAL_ISS_DATE LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  2011-04-20T00:00:00           None          TN        TN            1

    ZIP                                            ADDRESS COUNTRY_CODE  \
0  2066  TN - TUNIS - EL.KABARIA - BLOC B6 APPRT 145 RE...           TN

                                   OCCUPATION
0  Dirigeants et gerants non classes ailleurs
==================
Connection established successfully.

2025-04-28 07:32:11,706 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:11,708 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:11,713 - INFO - Retrieved PPH data successfully for customer ID 05146654
2025-04-28 07:32:11,750 - INFO - Starting to retrieve PPH data for customer ID 05146654

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME   LAST_NAME  \
0           PPH      273189      M      LOTFI  BEN FARHAT

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1969-11-14T00:00:00  TN - Tunis            CIN  05146654             TN

        LEGAL_ISS_DATE LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  2011-04-20T00:00:00           None          TN        TN            1

    ZIP                                            ADDRESS COUNTRY_CODE  \
0  2066  TN - TUNIS - EL.KABARIA - BLOC B6 APPRT 145 RE...           TN

                                   OCCUPATION
0  Dirigeants et gerants non classes ailleurs
==================
Connection established successfully.

2025-04-28 07:32:12,416 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:12,419 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:12,426 - INFO - Retrieved PPH data successfully for customer ID 05146654
2025-04-28 07:32:12,459 - INFO - Starting to retrieve PPH data for customer ID 05146654

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME   LAST_NAME  \
0           PPH      273189      M      LOTFI  BEN FARHAT

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1969-11-14T00:00:00  TN - Tunis            CIN  05146654             TN

        LEGAL_ISS_DATE LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  2011-04-20T00:00:00           None          TN        TN            1

    ZIP                                            ADDRESS COUNTRY_CODE  \
0  2066  TN - TUNIS - EL.KABARIA - BLOC B6 APPRT 145 RE...           TN

                                   OCCUPATION
0  Dirigeants et gerants non classes ailleurs
==================
Connection established successfully.

2025-04-28 07:32:13,324 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:13,326 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '05146654'

2025-04-28 07:32:13,331 - INFO - Retrieved PPH data successfully for customer ID 05146654
2025-04-28 07:32:13,380 - INFO - Database connection closed.
2025-04-28 07:32:13,381 - INFO - Cleaning and returning the retrieved DataFrame.
2025-04-28 07:32:13,381 - INFO - Starting retrieval of cards trx for account: 0891110000737
2025-04-28 07:32:13,394 - INFO - Executing query for account: 0891110000737

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME   LAST_NAME  \
0           PPH      273189      M      LOTFI  BEN FARHAT

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1969-11-14T00:00:00  TN - Tunis            CIN  05146654             TN

        LEGAL_ISS_DATE LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  2011-04-20T00:00:00           None          TN        TN            1

    ZIP                                            ADDRESS COUNTRY_CODE  \
0  2066  TN - TUNIS - EL.KABARIA - BLOC B6 APPRT 145 RE...           TN

                                   OCCUPATION
0  Dirigeants et gerants non classes ailleurs
==================
Connection closed.
Connection established successfully.

2025-04-28 07:32:20,344 - INFO - Successfully executed query:
            SELECT
                EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEAB + EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEAN + EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEAS AS EQ_ACCOUNT,
            	CARD_TRX.AUT_ACCO_ID1_F102 AS ORACLE_ACCOUNT,
                CARD_TRX.AUT_PRIM_ACCT_NUMB_F002 AS CARD_NUMBER,
                'S' + SUBSTRING(CAST(CARD_TRX.AUT_CARD_ACCP_TERM_ID_F041 AS VARCHAR), 1, 6) + CARD_TRX.AUT_SYST_TRAC_AUDIT_NUMB_F011 AS TRANSACTION_REF,
                FORMAT(CARD_TRX.AUT_RESP_SYST_TIME, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,

                'TN' AS COUNTRY_1,

                'TN' AS COUNTRY_2,
                CURRENCY_2.AlphabeticCode AS CURRENCY_CODE_2,
				FORMAT(ISNULL(CARD_TRX.AUT_BILL_AMOU_F006, 0) + ISNULL(CARD_TRX.AUT_BILL_AMOU_FEES_F008, 0) / POWER(10, CURRENCY_2.MinorUnit), '0.##################') FOREIGN_AMOUNT_2,

                '30' + '/' + SUBSTRING(CAST(AUT_CARD_ACCP_TERM_ID_F041 AS VARCHAR), 1, 6) + AUT_SYST_TRAC_AUDIT_NUMB_F011 + '/' + FORMAT(CARD_TRX.AUT_REQU_SYST_TIME, 'yyyy MM dd') + 'T00:00:00' AS TRANSACTION_NUMBER,
                CARD_TRX.AUT_CARD_ACCP_NAME_LOC_F043 AS TRANSACTION_LOCATION,
                FORMAT(CARD_TRX.AUT_REQU_SYST_TIME, 'yyyy-MM-dd') + 'T00:00:00' AS DATE_TRANSACTION,
                'C' AS TRANSACTION_STATUS_CODE,

                CARD_TRX.AUT_CARD_ACCP_NAME_LOC_F043 AS NAR,

                'Card - AUTHORIZATION' AS IBANK_SOURCE

            FROM [MISDW].[TRG].[ATM_AUTHORIZATION] AS CARD_TRX
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQA_ACC_EXTERNAL_ACCOUNT_NUMBER ON EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEEAN = CARD_TRX.AUT_ACCO_ID1_F102
            LEFT JOIN [MISDW].[GO_AML].[CURRENCY_CODES] AS CURRENCY_2 ON FORMAT(CURRENCY_2.NumericCode, '000') = CARD_TRX.AUT_ADDI_AMOU_F054_CURR_CODE2
            WHERE
                CARD_TRX.AUT_ACCO_ID1_F102 = '0891110000737'
                AND FORMAT(CARD_TRX.AUT_REQU_SYST_TIME, 'yyyy') = '2025'

2025-04-28 07:37:14,127 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEAB + EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEAN + EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEAS AS EQ_ACCOUNT,
            	CARD_TRX.AUT_ACCO_ID1_F102 AS ORACLE_ACCOUNT,
                CARD_TRX.AUT_PRIM_ACCT_NUMB_F002 AS CARD_NUMBER,
                'S' + SUBSTRING(CAST(CARD_TRX.AUT_CARD_ACCP_TERM_ID_F041 AS VARCHAR), 1, 6) + CARD_TRX.AUT_SYST_TRAC_AUDIT_NUMB_F011 AS TRANSACTION_REF,
                FORMAT(CARD_TRX.AUT_RESP_SYST_TIME, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,

                'TN' AS COUNTRY_1,

                'TN' AS COUNTRY_2,
                CURRENCY_2.AlphabeticCode AS CURRENCY_CODE_2,
				FORMAT(ISNULL(CARD_TRX.AUT_BILL_AMOU_F006, 0) + ISNULL(CARD_TRX.AUT_BILL_AMOU_FEES_F008, 0) / POWER(10, CURRENCY_2.MinorUnit), '0.##################') FOREIGN_AMOUNT_2,

                '30' + '/' + SUBSTRING(CAST(AUT_CARD_ACCP_TERM_ID_F041 AS VARCHAR), 1, 6) + AUT_SYST_TRAC_AUDIT_NUMB_F011 + '/' + FORMAT(CARD_TRX.AUT_REQU_SYST_TIME, 'yyyy MM dd') + 'T00:00:00' AS TRANSACTION_NUMBER,
                CARD_TRX.AUT_CARD_ACCP_NAME_LOC_F043 AS TRANSACTION_LOCATION,
                FORMAT(CARD_TRX.AUT_REQU_SYST_TIME, 'yyyy-MM-dd') + 'T00:00:00' AS DATE_TRANSACTION,
                'C' AS TRANSACTION_STATUS_CODE,

                CARD_TRX.AUT_CARD_ACCP_NAME_LOC_F043 AS NAR,

                'Card - AUTHORIZATION' AS IBANK_SOURCE

            FROM [MISDW].[TRG].[ATM_AUTHORIZATION] AS CARD_TRX
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQA_ACC_EXTERNAL_ACCOUNT_NUMBER ON EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEEAN = CARD_TRX.AUT_ACCO_ID1_F102
            LEFT JOIN [MISDW].[GO_AML].[CURRENCY_CODES] AS CURRENCY_2 ON FORMAT(CURRENCY_2.NumericCode, '000') = CARD_TRX.AUT_ADDI_AMOU_F054_CURR_CODE2
            WHERE
                CARD_TRX.AUT_ACCO_ID1_F102 = '0891110000737'
                AND FORMAT(CARD_TRX.AUT_REQU_SYST_TIME, 'yyyy') = '2025'

2025-04-28 07:37:14,136 - INFO - Query executed successfully; card trx data retrieved for account: 0891110000737
2025-04-28 07:37:14,175 - INFO - Database connection closed.
2025-04-28 07:37:14,177 - INFO - Cleaning and returning the retrieved DataFrame.

Connection closed.
process_transactions
===================================
===================================
 0 - carte
['both', 'left_only']
Categories (3, object): ['left_only', 'right_only', 'both']
===================================
===================================
===================================
===================================
 case 3 - left and both
===================================
===================================
card - model
Empty DataFrame
Columns: []
Index: []

0it [00:00, ?it/s]

card controller - card trx to process
    T24_ACCOUNT     EQ_ACCOUNT ORACLE_ACCOUNT TRANSACTION_REF TRANSACTION_SEQ  \
0    2002611131  5812273189500  0891110000737   S001444178509            2665
1    2002611131  5812273189500  0891110000737   S808700801457           34893
2    2002611131  5812273189500  0891110000737   S104003057221            9329
3    2002611131  5812273189500  0891110000737   S808700439326           79631
4    2002611131  5812273189500  0891110000737   S030000809772            6355
..          ...            ...            ...             ...             ...
116  2002611131  5812273189500  0891110000737   S258606513737             181
117  2002611131  5812273189500  0891110000737   S787210006708             367
118  2002611131  5812273189500  0891110000737   S100002116250           26715
119  2002611131  5812273189500  0891110000737   S019178413832            1021
120  2002611131  5812273189500  0891110000737   S954770876916           12375

    TRANSACTION_DATE TRANSACTION_DATE_TS_x TRANSACTION_CURRENCY  \
0            1250107                  None                  TND
1            1250109                  None                  TND
2            1250110                  None                  TND
3            1250113                  None                  TND
4            1250116                  None                  TND
..               ...                   ...                  ...
116          1250114                  None                  TND
117          1250120                  None                  TND
118          1250127                  None                  TND
119          1250203                  None                  TND
120          1250224                  None                  TND

    TRANSACTION_AMOUNT TRANSACTION_CODE_ATB  ...  \
0      -201.6000000000                  427  ...
1      -131.3900000000                  427  ...
2      -400.0000000000                  427  ...
3      -101.3000000000                  427  ...
4       -51.1500000000                  427  ...
..                 ...                  ...  ...
116     -21.5000000000                  439  ...
117     -83.0000000000                  439  ...
118    -710.3000000000                  439  ...
119     -32.0000000000                  439  ...
120     -10.3400000000                  439  ...

                   TRANSACTION_LOCATION     DATE_TRANSACTION  \
0        ATM-BH-BEN-AROUS-BEN-AROUS-TUN  2025-01-07T00:00:00
1          CAISSE-CENTRALE-KHELIDIA-TUN  2025-01-09T00:00:00
2            ATB-BEN-AROUS-BEN-AROUS-TN  2025-01-10T00:00:00
3          CAISSE-CENTRALE-KHELIDIA-TUN  2025-01-12T00:00:00
4    ATM-BNA-BEN-AROUS-AGENCE-BEN-ARTUN  2025-01-16T00:00:00
..                                  ...                  ...
116          MARWEN-ZRELLI-MENZAH-5-TUN  2025-01-13T00:00:00
117        SIT-MARCH-TESKERTI-TUNIS-TUN  2025-01-19T00:00:00
118     OFFICE-DE-LAVIATION-CITUNIS-TUN  2025-01-27T00:00:00
119               VIA-MERCATO-LAC-2-TUN  2025-02-02T00:00:00
120           TUNISIE-TELECOM-TUNIS-TUN  2025-02-24T00:00:00

    TRANSACTION_STATUS_CODE                                       NAR  \
0                         C  ATM BH BEN AROUS      >BEN AROUS    >TUN
1                         C  CAISSE CENTRALE       >KHELIDIA     >TUN
2                         C  ATB BEN AROUS          BEN AROUS      TN
3                         C  CAISSE CENTRALE       >KHELIDIA     >TUN
4                         C  ATM BNA BEN AROUS     >AGENCE BEN AR>TUN
..                      ...                                       ...
116                       C  MARWEN ZRELLI         >MENZAH 5     >TUN
117                       C  SIT MARCH TESKERTI    >TUNIS        >TUN
118                       C  OFFICE DE LAVIATION CI>TUNIS        >TUN
119                       C  VIA MERCATO           >LAC 2        >TUN
120                       C  TUNISIE TELECOM       >TUNIS        >TUN

             IBANK_SOURCE _merge TRANSACTION_NATURE CURRENCY_CODE_1  \
0    Card - AUTHORIZATION   both     ATM_Withdrawal             TND
1    Card - AUTHORIZATION   both     ATM_Withdrawal             TND
2    Card - AUTHORIZATION   both     ATM_Withdrawal             TND
3    Card - AUTHORIZATION   both     ATM_Withdrawal             TND
4    Card - AUTHORIZATION   both     ATM_Withdrawal             TND
..                    ...    ...                ...             ...
116  Card - AUTHORIZATION   both       Card_Payment             TND
117  Card - AUTHORIZATION   both       Card_Payment             TND
118  Card - AUTHORIZATION   both       Card_Payment             TND
119  Card - AUTHORIZATION   both       Card_Payment             TND
120  Card - AUTHORIZATION   both       Card_Payment             TND

    FOREIGN_AMOUNT_1 AMOUNT_LOCAL
0              201.6        201.6
1             131.39       131.39
2              400.0        400.0
3              101.3        101.3
4              51.15        51.15
..               ...          ...
116             21.5         21.5
117             83.0         83.0
118            710.3        710.3
119             32.0         32.0
120            10.34        10.34

[121 rows x 37 columns]
**************
Empty DataFrame
Columns: []
Index: []
=============================== transaction router - card - case 2 - is empty ========================================
True
=======================================================================

In [24]:
import pandas as pd

In [27]:
accountant_card = pd.merge(
    left=transaction_router.eq_accountant.accountant_transactions,
    right=transaction_router.transaction_code[['TRANSACTION_CODE_ATB', 'TRANSACTION_DESC_ATB', 'APP_SOURCE_CODE', 'APP_SOURCE', 'OP_TYPE', 'Categorie_de_transaction', 'TRANSACTION_DESC_GOAML', 'TRANSACTION_CODE_GOAML', 'FUND_CODE_1', 'FUND_CODE_2']],
    left_on=['APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB'],
    right_on=['APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB'],
    how='left',
    indicator=True
).query("APP_SOURCE_CODE == 'MXPCP' and Categorie_de_transaction == 'code affectant directement le compte client (débit/crédit)'").copy(deep=True)

In [28]:
accountant_card

,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_CODE_ATB,...,APP_SOURCE_CODE,TRANSACTION_DESC_ATB_y,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_DESC_GOAML,TRANSACTION_CODE_GOAML,FUND_CODE_1,FUND_CODE_2,_merge
38,2002557757,5854349108500,0541107011701,C020124080925220,30426,1240103,2024-01-03 11.24,TND,-818.8050000000,439,...,MXPCP,Paiement par carte,Rectification / Injection Manuelle,Carte,code affectant directement le compte client (d...,Paiement par cartes électroniques locales,B108,A,A,both
39,2002557757,5854349108500,0541107011701,C020124080925221,30745,1240103,2024-01-03 11.25,TND,-515.5080000000,439,...,MXPCP,Paiement par carte,Rectification / Injection Manuelle,Carte,code affectant directement le compte client (d...,Paiement par cartes électroniques locales,B108,A,A,both
40,2002557757,5854349108500,0541107011701,C04012407447710,1067,1240105,2024-01-05 08.34,TND,-474.0000000000,439,...,MXPCP,Paiement par carte,Rectification / Injection Manuelle,Carte,code affectant directement le compte client (d...,Paiement par cartes électroniques locales,B108,A,A,both
41,2002557757,5854349108500,0541107011701,C04012407447793,1690,1240105,2024-01-05 08.39,TND,-181.1050000000,439,...,MXPCP,Paiement par carte,Rectification / Injection Manuelle,Carte,code affectant directement le compte client (d...,Paiement par cartes électroniques locales,B108,A,A,both
42,2002557757,5854349108500,0541107011701,C090124085320102,13105,1240110,2024-01-10 09.51,TND,-98.0000000000,439,...,MXPCP,Paiement par carte,Rectification / Injection Manuelle,Carte,code affectant directement le compte client (d...,Paiement par cartes électroniques locales,B108,A,A,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2002557757,5854349108500,0541107011701,C161224151846037,16290,1241218,None,TND,-33.8000000000,439,...,MXPCP,Paiement par carte,Rectification / Injection Manuelle,Carte,code affectant directement le compte client (d...,Paiement par cartes électroniques locales,B108,A,A,both
136,2002557757,5854349108500,0541107011701,C161224151824371,17732,1241219,None,TND,-515.5080000000,439,...,MXPCP,Paiement par carte,Rectification / Injection Manuelle,Carte,code affectant directement le compte client (d...,Paiement par cartes électroniques locales,B108,A,A,both
137,2002557757,5854349108500,0541107011701,C161224151824668,4179,1241219,None,TND,-181.1050000000,439,...,MXPCP,Paiement par carte,Rectification / Injection Manuelle,Carte,code affectant directement le compte client (d...,Paiement par cartes électroniques locales,B108,A,A,both
138,2002557757,5854349108500,0541107011701,C161224151846036,24287,1241219,None,TND,-30.2000000000,439,...,MXPCP,Paiement par carte,Rectification / Injection Manuelle,Carte,code affectant directement le compte client (d...,Paiement par cartes électroniques locales,B108,A,A,both
139,2002557757,5854349108500,0541107011701,C161224151846038,14687,1241219,None,TND,-59.2000000000,439,...,MXPCP,Paiement par carte,Rectification / Injection Manuelle,Carte,code affectant directement le compte client (d...,Paiement par cartes électroniques locales,B108,A,A,both

In [10]:
from src.controller.carte import Carte

In [11]:
carte = Carte(DB_CONFIG)

In [29]:
carte.account =  account
carte.accountant_trx = accountant_card
carte.year = year
carte.get_transactions()

2025-04-22 16:16:26,947 - INFO - Starting retrieval of cards for account: 0541107011701
2025-04-22 16:16:27,057 - INFO - Executing query for account: 0541107011701
2025-04-22 16:16:27,095 - INFO - Successfully executed query:
            SELECT
                CUSTOMER_CARDHOLDER.CUS_IDEN AS ORACLE_ACC,
                CUSTOMER_CARDHOLDER.CUS_CODE AS CARD_ID,
                CARDS.CAR_NUMB AS CARD_NUMBER,
                CUSTOMER_CARDHOLDER.CUS_FIRS_NAM1 AS CARD_HOLDER_NAME,
                CUSTOMER_CARDHOLDER.CUS_FIRS_IDE1 AS CARD_HOLDER_LEGAL_ID
            FROM [MISDW].[TRG].[ATM_CUSTOMER_CARDHOLDER] AS CUSTOMER_CARDHOLDER
            LEFT JOIN [MISDW].[TRG].[ATM_CARDS] AS CARDS ON CARDS.CAR_CUS_CODE = CUSTOMER_CARDHOLDER.CUS_CODE
            WHERE
                CUSTOMER_CARDHOLDER.CUS_IDEN = '0541107011701'

2025-04-22 16:16:27,098 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                CUSTOMER_CARDHOLDER.CUS_IDEN AS ORACLE_ACC,
                CUSTOMER_CARDHOLDER.CUS_CODE AS CARD_ID,
                CARDS.CAR_NUMB AS CARD_NUMBER,
                CUSTOMER_CARDHOLDER.CUS_FIRS_NAM1 AS CARD_HOLDER_NAME,
                CUSTOMER_CARDHOLDER.CUS_FIRS_IDE1 AS CARD_HOLDER_LEGAL_ID
            FROM [MISDW].[TRG].[ATM_CUSTOMER_CARDHOLDER] AS CUSTOMER_CARDHOLDER
            LEFT JOIN [MISDW].[TRG].[ATM_CARDS] AS CARDS ON CARDS.CAR_CUS_CODE = CUSTOMER_CARDHOLDER.CUS_CODE
            WHERE
                CUSTOMER_CARDHOLDER.CUS_IDEN = '0541107011701'

2025-04-22 16:16:27,100 - INFO - Query executed successfully; card data retrieved for account: 0541107011701
2025-04-22 16:16:27,102 - INFO - Starting to retrieve PPH data for customer ID 07788786

self.account_related_cards is empty
Connection established successfully.
Connection established successfully.

2025-04-22 16:16:27,419 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '07788786'

2025-04-22 16:16:27,423 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '07788786'

2025-04-22 16:16:32,426 - WARNING - Failed to execute query after 1 attempts
2025-04-22 16:16:32,426 - WARNING - No PPH data found for customer ID 07788786
2025-04-22 16:16:32,677 - WARNING - No data found for CARD_HOLDER_LEGAL_ID: 07788786
2025-04-22 16:16:32,678 - INFO - Starting to retrieve PPH data for customer ID 07788786

Connection closed.
================================
================================
True
Empty DataFrame
Columns: []
Index: []
================================
================================
Connection established successfully.

2025-04-22 16:16:32,996 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '07788786'

2025-04-22 16:16:32,997 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '07788786'

2025-04-22 16:16:37,999 - WARNING - Failed to execute query after 1 attempts
2025-04-22 16:16:38,001 - WARNING - No PPH data found for customer ID 07788786
2025-04-22 16:16:38,057 - WARNING - No data found for CARD_HOLDER_LEGAL_ID: 07788786
2025-04-22 16:16:38,059 - INFO - Starting to retrieve PPH data for customer ID 07788786
2025-04-22 16:16:38,169 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '07788786'

2025-04-22 16:16:38,173 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '07788786'

Connection closed.
================================
================================
True
Empty DataFrame
Columns: []
Index: []
================================
================================
Connection established successfully.

2025-04-22 16:16:43,175 - WARNING - Failed to execute query after 1 attempts
2025-04-22 16:16:43,176 - WARNING - No PPH data found for customer ID 07788786
2025-04-22 16:16:43,201 - WARNING - No data found for CARD_HOLDER_LEGAL_ID: 07788786
2025-04-22 16:16:43,202 - INFO - Starting to retrieve PPH data for customer ID 07788786
2025-04-22 16:16:43,289 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '07788786'

2025-04-22 16:16:43,290 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '07788786'

Connection closed.
================================
================================
True
Empty DataFrame
Columns: []
Index: []
================================
================================
Connection established successfully.

2025-04-22 16:16:48,292 - WARNING - Failed to execute query after 1 attempts
2025-04-22 16:16:48,293 - WARNING - No PPH data found for customer ID 07788786
2025-04-22 16:16:48,785 - WARNING - No data found for CARD_HOLDER_LEGAL_ID: 07788786
2025-04-22 16:16:48,786 - INFO - Starting to retrieve PPH data for customer ID 07788786
2025-04-22 16:16:48,908 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '07788786'

2025-04-22 16:16:48,909 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                LEGAL_ID = '07788786'

Connection closed.
================================
================================
True
Empty DataFrame
Columns: []
Index: []
================================
================================
Connection established successfully.

2025-04-22 16:16:53,910 - WARNING - Failed to execute query after 1 attempts
2025-04-22 16:16:53,911 - WARNING - No PPH data found for customer ID 07788786
2025-04-22 16:16:54,007 - WARNING - No data found for CARD_HOLDER_LEGAL_ID: 07788786
2025-04-22 16:16:54,098 - INFO - Database connection closed.
2025-04-22 16:16:54,098 - INFO - Cleaning and returning the retrieved DataFrame.
2025-04-22 16:16:54,099 - INFO - Starting retrieval of cards trx for account: 0541107011701
2025-04-22 16:16:54,110 - INFO - Executing query for account: 0541107011701

Connection closed.
================================
================================
True
Empty DataFrame
Columns: []
Index: []
================================
================================
Connection closed.
Connection established successfully.

2025-04-22 16:16:55,865 - INFO - Successfully executed query:
            SELECT
                EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEAB + EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEAN + EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEAS AS EQ_ACCOUNT,
            	CARD_TRX.AUT_ACCO_ID1_F102 AS ORACLE_ACCOUNT,
                CARD_TRX.AUT_PRIM_ACCT_NUMB_F002 AS CARD_NUMBER,
                'S' + SUBSTRING(CAST(CARD_TRX.AUT_CARD_ACCP_TERM_ID_F041 AS VARCHAR), 1, 6) + CARD_TRX.AUT_SYST_TRAC_AUDIT_NUMB_F011 AS TRANSACTION_REF,
                FORMAT(CARD_TRX.AUT_RESP_SYST_TIME, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,

                'TN' AS COUNTRY_1,

                'TN' AS COUNTRY_2,
                CURRENCY_2.AlphabeticCode AS CURRENCY_CODE_2,
				FORMAT(ISNULL(CARD_TRX.AUT_BILL_AMOU_F006, 0) + ISNULL(CARD_TRX.AUT_BILL_AMOU_FEES_F008, 0) / POWER(10, CURRENCY_2.MinorUnit), '0.##################') FOREIGN_AMOUNT_2,

                '30' + '/' + SUBSTRING(CAST(AUT_CARD_ACCP_TERM_ID_F041 AS VARCHAR), 1, 6) + AUT_SYST_TRAC_AUDIT_NUMB_F011 + '/' + FORMAT(CARD_TRX.AUT_REQU_SYST_TIME, 'yyyy MM dd') + 'T00:00:00' AS TRANSACTION_NUMBER,
                CARD_TRX.AUT_CARD_ACCP_NAME_LOC_F043 AS TRANSACTION_LOCATION,
                FORMAT(CARD_TRX.AUT_REQU_SYST_TIME, 'yyyy-MM-dd') + 'T00:00:00' AS DATE_TRANSACTION,
                'C' AS TRANSACTION_STATUS_CODE,

                CARD_TRX.AUT_CARD_ACCP_NAME_LOC_F043 AS NAR,

                'Card - AUTHORIZATION' AS IBANK_SOURCE

            FROM [MISDW].[TRG].[ATM_AUTHORIZATION] AS CARD_TRX
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQA_ACC_EXTERNAL_ACCOUNT_NUMBER ON EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEEAN = CARD_TRX.AUT_ACCO_ID1_F102
            LEFT JOIN [MISDW].[GO_AML].[CURRENCY_CODES] AS CURRENCY_2 ON FORMAT(CURRENCY_2.NumericCode, '000') = CARD_TRX.AUT_ADDI_AMOU_F054_CURR_CODE2
            WHERE
                CARD_TRX.AUT_ACCO_ID1_F102 = '0541107011701'
                AND FORMAT(CARD_TRX.AUT_REQU_SYST_TIME, 'yyyy') = '2024'

2025-04-22 16:17:18,151 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEAB + EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEAN + EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEAS AS EQ_ACCOUNT,
            	CARD_TRX.AUT_ACCO_ID1_F102 AS ORACLE_ACCOUNT,
                CARD_TRX.AUT_PRIM_ACCT_NUMB_F002 AS CARD_NUMBER,
                'S' + SUBSTRING(CAST(CARD_TRX.AUT_CARD_ACCP_TERM_ID_F041 AS VARCHAR), 1, 6) + CARD_TRX.AUT_SYST_TRAC_AUDIT_NUMB_F011 AS TRANSACTION_REF,
                FORMAT(CARD_TRX.AUT_RESP_SYST_TIME, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,

                'TN' AS COUNTRY_1,

                'TN' AS COUNTRY_2,
                CURRENCY_2.AlphabeticCode AS CURRENCY_CODE_2,
				FORMAT(ISNULL(CARD_TRX.AUT_BILL_AMOU_F006, 0) + ISNULL(CARD_TRX.AUT_BILL_AMOU_FEES_F008, 0) / POWER(10, CURRENCY_2.MinorUnit), '0.##################') FOREIGN_AMOUNT_2,

                '30' + '/' + SUBSTRING(CAST(AUT_CARD_ACCP_TERM_ID_F041 AS VARCHAR), 1, 6) + AUT_SYST_TRAC_AUDIT_NUMB_F011 + '/' + FORMAT(CARD_TRX.AUT_REQU_SYST_TIME, 'yyyy MM dd') + 'T00:00:00' AS TRANSACTION_NUMBER,
                CARD_TRX.AUT_CARD_ACCP_NAME_LOC_F043 AS TRANSACTION_LOCATION,
                FORMAT(CARD_TRX.AUT_REQU_SYST_TIME, 'yyyy-MM-dd') + 'T00:00:00' AS DATE_TRANSACTION,
                'C' AS TRANSACTION_STATUS_CODE,

                CARD_TRX.AUT_CARD_ACCP_NAME_LOC_F043 AS NAR,

                'Card - AUTHORIZATION' AS IBANK_SOURCE

            FROM [MISDW].[TRG].[ATM_AUTHORIZATION] AS CARD_TRX
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQA_ACC_EXTERNAL_ACCOUNT_NUMBER ON EQA_ACC_EXTERNAL_ACCOUNT_NUMBER.NEEAN = CARD_TRX.AUT_ACCO_ID1_F102
            LEFT JOIN [MISDW].[GO_AML].[CURRENCY_CODES] AS CURRENCY_2 ON FORMAT(CURRENCY_2.NumericCode, '000') = CARD_TRX.AUT_ADDI_AMOU_F054_CURR_CODE2
            WHERE
                CARD_TRX.AUT_ACCO_ID1_F102 = '0541107011701'
                AND FORMAT(CARD_TRX.AUT_REQU_SYST_TIME, 'yyyy') = '2024'

2025-04-22 16:17:18,156 - INFO - Query executed successfully; card trx data retrieved for account: 0541107011701
2025-04-22 16:17:18,220 - INFO - Database connection closed.
2025-04-22 16:17:18,220 - INFO - Cleaning and returning the retrieved DataFrame.

Connection closed.

In [39]:
carte.ibank_carte.card_transactions

,EQ_ACCOUNT,ORACLE_ACCOUNT,CARD_NUMBER,TRANSACTION_REF,TRANSACTION_DATE_TS,COUNTRY_1,COUNTRY_2,CURRENCY_CODE_2,FOREIGN_AMOUNT_2,TRANSACTION_NUMBER,TRANSACTION_LOCATION,DATE_TRANSACTION,TRANSACTION_STATUS_CODE,NAR,IBANK_SOURCE
0,5854349108500,0541107011701,4338003053244736,S915750198604,2024-01-03 10.11,TN,TN,TND,474,30/915750198604/2024 01 03T00:00:00,SODEXO-ALI-ANNABI-TUTUN,2024-01-03T00:00:00,C,SODEXO >ALI ANNABI TU>TUN,Card - AUTHORIZATION
1,5854349108500,0541107011701,4338003053244736,S954770363652,2024-01-03 14.44,TN,TN,TND,181.105,30/954770363652/2024 01 03T00:00:00,TUNISIE-TELECOM-TUNIS-TUN,2024-01-03T00:00:00,C,TUNISIE TELECOM >TUNIS >TUN,Card - AUTHORIZATION
2,5854349108500,0541107011701,4338003053244736,S000982942320,2024-01-08 15.06,TN,TN,TND,98,30/000982942320/2024 01 08T00:00:00,STEG-TUNIS-TUN,2024-01-08T00:00:00,C,STEG >TUNIS >TUN,Card - AUTHORIZATION
3,5854349108500,0541107011701,4338003053244736,S956780408397,2024-01-26 09.47,TN,TN,TND,515.508,30/956780408397/2024 01 26T00:00:00,TUNISIANA-TUNIS-TUN,2024-01-26T00:00:00,C,TUNISIANA >TUNIS >TUN,Card - AUTHORIZATION
4,5854349108500,0541107011701,4338003053244736,S956780412450,2024-01-26 09.52,TN,TN,TND,818.805,30/956780412450/2024 01 26T00:00:00,TUNISIANA-TUNIS-TUN,2024-01-26T00:00:00,C,TUNISIANA >TUNIS >TUN,Card - AUTHORIZATION
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,5854349108500,0541107011701,4338003053244736,S956780578091,2024-12-13 11.06,TN,TN,TND,818.805,30/956780578091/2024 12 13T00:00:00,TUNISIANA-TUNIS-TUN,2024-12-13T00:00:00,C,TUNISIANA >TUNIS >TUN,Card - AUTHORIZATION
96,5854349108500,0541107011701,4338003053244736,S956780580938,2024-12-13 11.10,TN,TN,TND,93.605,30/956780580938/2024 12 13T00:00:00,TUNISIANA-TUNIS-TUN,2024-12-13T00:00:00,C,TUNISIANA >TUNIS >TUN,Card - AUTHORIZATION
97,5854349108500,0541107011701,4338003053244736,S000982584668,2024-12-13 11.16,TN,TN,TND,59.2,30/000982584668/2024 12 13T00:00:00,SONEDE-TUNIS-TUN,2024-12-13T00:00:00,C,SONEDE >TUNIS >TUN,Card - AUTHORIZATION
98,5854349108500,0541107011701,4338003053244736,S000982586819,2024-12-13 11.19,TN,TN,TND,33.8,30/000982586819/2024 12 13T00:00:00,SONEDE-TUNIS-TUN,2024-12-13T00:00:00,C,SONEDE >TUNIS >TUN,Card - AUTHORIZATION
99,5854349108500,0541107011701,4338003053244736,S000982588855,2024-12-13 11.23,TN,TN,TND,30.2,30/000982588855/2024 12 13T00:00:00,SONEDE-TUNIS-TUN,2024-12-13T00:00:00,C,SONEDE >TUNIS >TUN,Card - AUTHORIZATION

In [40]:
accountant_card.drop_duplicates(subset=['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE'], inplace=True)

accountant_card.loc[:, 'T24_ACCOUNT'] = accountant_card['T24_ACCOUNT'].astype(str).str.strip()
accountant_card.loc[:, 'EQ_ACCOUNT'] = accountant_card['EQ_ACCOUNT'].astype(str).str.strip()
accountant_card.loc[:, 'ORACLE_ACCOUNT'] = accountant_card['ORACLE_ACCOUNT'].astype(str).str.strip()
accountant_card.loc[:, 'TRANSACTION_REF'] = accountant_card['TRANSACTION_REF'].astype(str).str.strip()

In [41]:
carte.ibank_carte.card_transactions.sort_values(
    by=['EQ_ACCOUNT', 'ORACLE_ACCOUNT', 'CARD_NUMBER', 'IBANK_SOURCE', 'DATE_TRANSACTION', 'TRANSACTION_REF'],
    inplace=True
)

carte.ibank_carte.card_transactions.drop_duplicates(
    subset=['EQ_ACCOUNT', 'ORACLE_ACCOUNT', 'CARD_NUMBER', 'IBANK_SOURCE', 'DATE_TRANSACTION', 'TRANSACTION_REF'], 
    keep='first',
    inplace=True
)

In [46]:
accountant_card['TRANSACTION_REF']

38     C020124080925220
39     C020124080925221
40      C04012407447710
41      C04012407447793
42     C090124085320102
             ...
135    C161224151846037
136    C161224151824371
137    C161224151824668
138    C161224151846036
139    C161224151846038
Name: TRANSACTION_REF, Length: 102, dtype: object

In [54]:
pd.merge(
    left=accountant_card,
    right=carte.ibank_carte.card_transactions,
    left_on=['EQ_ACCOUNT', 'ORACLE_ACCOUNT', 'TRANSACTION_REF'],
    right_on=['EQ_ACCOUNT', 'ORACLE_ACCOUNT','TRANSACTION_REF'],
    how='left',
    #indicator=True,
    indicator='merge_status'  # Use a custom name
)['APP_SOURCE']

0      Rectification / Injection Manuelle
1      Rectification / Injection Manuelle
2      Rectification / Injection Manuelle
3      Rectification / Injection Manuelle
4      Rectification / Injection Manuelle
                      ...
97     Rectification / Injection Manuelle
98     Rectification / Injection Manuelle
99     Rectification / Injection Manuelle
100    Rectification / Injection Manuelle
101    Rectification / Injection Manuelle
Name: APP_SOURCE, Length: 102, dtype: object