In [1]:
import sys
sys.path.append('../')

In [2]:
from src.config import DB_CONFIG, TREANSACTION_CODE

In [3]:
from src.model.get_client_T24 import GetClientT24

In [4]:
get_client_T24 = GetClientT24(DB_CONFIG)

In [5]:
account_number = '5943043515500'
print(get_client_T24.account_status_lookup(account_number)) # True -> Active Account

account_correspondences, account_details, customer_id, account_type, account_rp = get_client_T24.get_client(account_number)

2025-04-10 07:52:33,238 - INFO - Executing account status lookup for account: 5943043515500

Connection established successfully.

2025-04-10 07:52:33,680 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5943043515500'

2025-04-10 07:52:33,681 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5943043515500'

2025-04-10 07:52:33,683 - INFO - Account 5943043515500 is IS_ACTIVE
2025-04-10 07:52:33,711 - INFO - Executing account status lookup for account: 5943043515500
2025-04-10 07:52:33,820 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5943043515500'

2025-04-10 07:52:33,820 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5943043515500'

2025-04-10 07:52:33,822 - INFO - Account 5943043515500 is IS_ACTIVE
2025-04-10 07:52:33,863 - INFO - Executing query to retrieve account information for account number: 5943043515500

Connection closed.
True
Connection established successfully.
Connection closed.
Connection established successfully.

2025-04-10 07:52:37,804 - INFO - Successfully executed query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5943043515500'

2025-04-10 07:52:37,805 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5943043515500'

2025-04-10 07:52:37,809 - INFO - Successfully retrieved account information for account number: 5943043515500
2025-04-10 07:52:37,843 - INFO - Executing query to retrieve arrangement information for arrangement id : AA231494CTGS

Connection closed.
Connection established successfully.

2025-04-10 07:52:38,578 - INFO - Successfully executed query:
        SELECT
            LEFT(RECID, CHARINDEX('-', RECID) - 1) AS ARRANGEMENT_ID,
            CUSTOMER_3,
            CUSTOMER_ROLE_4,
            L_ACCT_TYPE
        FROM [MISDW].[GO_AML].[T24_FATB_AA_ARR_CUSTOMER]
        WHERE
            LEFT(RECID, CHARINDEX('-', RECID) - 1) = 'AA231494CTGS'

2025-04-10 07:52:38,579 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            LEFT(RECID, CHARINDEX('-', RECID) - 1) AS ARRANGEMENT_ID,
            CUSTOMER_3,
            CUSTOMER_ROLE_4,
            L_ACCT_TYPE
        FROM [MISDW].[GO_AML].[T24_FATB_AA_ARR_CUSTOMER]
        WHERE
            LEFT(RECID, CHARINDEX('-', RECID) - 1) = 'AA231494CTGS'

2025-04-10 07:52:38,581 - INFO - Successfully retrieved account information for arrangement id : AA231494CTGS
2025-04-10 07:52:38,618 - INFO - Starting to retrieve PPH data for customer ID 43515

Connection closed.
  ARRANGEMENT_ID CUSTOMER_ID CUSTOMER_ROLE L_ACCT_TYPE
0   AA231494CTGS       43515         OWNER           3
The DataFrame has only one record, and CUSTOMER_ROLE is OWNER.
Connection established successfully.

2025-04-10 07:52:39,215 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '43515'

2025-04-10 07:52:39,218 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '43515'

2025-04-10 07:52:39,221 - INFO - Retrieved PPH data successfully for customer ID 43515
2025-04-10 07:52:39,260 - INFO - Executing query to retrieve mandates information for account mandate id : None

Connection closed.
Connection established successfully.

2025-04-10 07:52:39,546 - INFO - Successfully executed query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = 'None'

2025-04-10 07:52:39,552 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = 'None'

2025-04-10 07:52:44,554 - WARNING - Failed to execute query after 1 attempts
2025-04-10 07:52:44,555 - WARNING - No data found for account mandate id : None

Connection closed.
======= fct aggregate_legal_id_section ===========
  CUSTOMER_TYPE CUSTOMER_ID GENDER FIRST_NAME LAST_NAME            BIRTHDATE  \
0           PRO       43515      F   KHOULOUD  BOURAYOU  1995-08-28T00:00:00
1           PRO       43515      F   KHOULOUD  BOURAYOU  1995-08-28T00:00:00

       BIRTH_PLACE LEGAL_DOC_NAME       LEGAL_ID LEGAL_ISS_AUTH  \
0  TN - TEBOURSOUK             MF  1824208DAP000             TN
1  TN - TEBOURSOUK            CIN       14255090             TN

        LEGAL_ISS_DATE LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE  \
0  2023-05-23T00:00:00           None          TN        TN            1
1  2022-08-17T00:00:00           None          TN        TN            1

    ZIP                                 ADDRESS COUNTRY_CODE  \
0  9040  TN - BEJA - TEBOURSOUK - CITE AIN MRAD           TN
1  9040  TN - BEJA - TEBOURSOUK - CITE AIN MRAD           TN

           OCCUPATION ROLE_ACCOUNT
0  Medecins dentistes        TICPT
1  Medecins dentistes        TICPT
==================
+++++++++++++++

In [6]:
account = {
    'account_number': account_number,
    'account_correspondences': account_correspondences,
    'account_detail': account_details,
    'customer_id': customer_id,
    'account_type': account_type,
    'account_rp': account_rp
}

In [7]:
from src.controller.transaction_router import TransactionRouter

In [8]:
transaction_router = TransactionRouter(TREANSACTION_CODE, DB_CONFIG)

2025-04-10 07:52:52,831 - INFO - Transaction codes loaded successfully.
2025-04-10 07:52:52,832 - INFO - EQAccountant initialized with logging enabled: True

Index(['APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB', 'TRANSACTION_DESC_ATB',
       'APP_SOURCE', 'OP_TYPE', 'Categorie_de_transaction',
       'TRANSACTION_CODE_GOAML', 'TRANSACTION_DESC_GOAML', 'FUND_CODE_1',
       'FUND_CODE_2', '_merge'],
      dtype='object')

In [9]:
year = '2024'
transaction_router.clear_cash()
transaction_router.get_transactions(account, year)

2025-04-10 07:52:55,140 - INFO - Starting to retrieve accountant's transactions for account: 5943043515500, year: 2024

Connection established successfully.

2025-04-10 07:53:34,570 - INFO - Successfully executed query:
            SELECT
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5943043515500'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2024'

2025-04-10 07:55:31,761 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5943043515500'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2024'

2025-04-10 07:55:31,764 - INFO - Query executed successfully. Accountant's transactions retrieved for the account.
2025-04-10 07:55:31,765 - INFO - Closing database connection.
2025-04-10 07:55:31,791 - INFO - Returning cleaned DataFrame.

Connection closed.
============*********==============
Index(['T24_ACCOUNT', 'EQ_ACCOUNT', 'ORACLE_ACCOUNT', 'TRANSACTION_REF',
       'TRANSACTION_SEQ', 'TRANSACTION_DATE', 'TRANSACTION_DATE_TS',
       'TRANSACTION_CURRENCY', 'TRANSACTION_AMOUNT', 'TRANSACTION_CODE_ATB',
       'TRANSACTION_DESC_ATB_ACC', 'APP_SOURCE_CODE', 'TRANSACTION_DESC_ATB_F',
       'APP_SOURCE', 'OP_TYPE', 'Categorie_de_transaction',
       'TRANSACTION_DESC_GOAML', 'TRANSACTION_CODE_GOAML', 'FUND_CODE_1',
       'FUND_CODE_2'],
      dtype='object')

In [10]:
transaction_router.accountant_transactions_with_trx_code.query(
    "OP_TYPE == 'Virement' and Categorie_de_transaction == 'code affectant directement le compte client (débit/crédit)'"
)

,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB_ACC,APP_SOURCE_CODE,TRANSACTION_DESC_ATB_F,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_DESC_GOAML,TRANSACTION_CODE_GOAML,FUND_CODE_1,FUND_CODE_2
57,2010390397,5943043515500,1431167000370,51433821,89,1241113,None,TND,-200.0000000000,023,Virement Emis,TLVIR,Virement Emis,IBANK,Virement,code affectant directement le compte client (d...,Virement emis,B117,A,A
58,2010390397,5943043515500,1431167000370,51160610,77,1240105,2024-01-05 10.08,TND,-240.0000000000,024,Virement Emis,TLVIR,Virement Emis,IBANK,Virement,code affectant directement le compte client (d...,Virement emis,B117,A,A
59,2010390397,5943043515500,1431167000370,51207205,25,1240207,2024-02-07 11.49,TND,-400.0000000000,024,Virement Emis,TLVIR,Virement Emis,IBANK,Virement,code affectant directement le compte client (d...,Virement emis,B117,A,A
60,2010390397,5943043515500,1431167000370,51207476,43,1240717,None,TND,-945.0000000000,024,Virement Emis,TLVIR,Virement Emis,IBANK,Virement,code affectant directement le compte client (d...,Virement emis,B117,A,A
107,2010390397,5943043515500,1431167000370,2448,2,1240712,None,TND,250.0000000000,524,Virement recu,TLVIR,Virement recu,IBANK,Virement,code affectant directement le compte client (d...,Virement recus,B399,A,A

In [11]:
transaction_router.eq_accountant.accountant_transactions.query("APP_SOURCE_CODE == 'TLVIR'")

,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE_CODE
97,2010390397,5943043515500,1431167000370,51433821,89,1241113,None,TND,-200.0000000000,023,Virement Emis,TLVIR
3,2010390397,5943043515500,1431167000370,51160610,77,1240105,2024-01-05 10.08,TND,-240.0000000000,024,Virement Emis,TLVIR
8,2010390397,5943043515500,1431167000370,51207205,25,1240207,2024-02-07 11.49,TND,-400.0000000000,024,Virement Emis,TLVIR
51,2010390397,5943043515500,1431167000370,51207476,43,1240717,None,TND,-945.0000000000,024,Virement Emis,TLVIR
1,2010390397,5943043515500,1431167000370,51160610,81,1240105,2024-01-05 10.08,TND,-0.4750000000,270,TVA,TLVIR
9,2010390397,5943043515500,1431167000370,51207205,29,1240207,2024-02-07 11.49,TND,-0.4750000000,270,TVA,TLVIR
17,2010390397,5943043515500,1431167000370,MBXDI-0000074858,276,1240223,2024-02-23 13.26,TND,-0.1900000000,270,TVA,TLVIR
18,2010390397,5943043515500,1431167000370,MBXDI-0000075907,462,1240305,2024-03-05 10.11,TND,-0.1900000000,270,TVA,TLVIR
23,2010390397,5943043515500,1431167000370,MBXDI-0000078129,479,1240404,2024-04-04 07.09,TND,-0.1900000000,270,TVA,TLVIR
25,2010390397,5943043515500,1431167000370,MBXDI-0000078611,1037,1240408,2024-04-08 10.46,TND,-0.1900000000,270,TVA,TLVIR
31,2010390397,5943043515500,1431167000370,MBXDI-0000080203,1341,1240502,2024-05-02 13.20,TND,-0.1900000000,270,TVA,TLVIR
37,2010390397,5943043515500,1431167000370,MBXDI-0000080967,516,1240509,2024-05-09 10.47,TND,-0.1900000000,270,TVA,TLVIR
44,2010390397,5943043515500,1431167000370,MBXDI-0000082830,1311,1240603,2024-06-03 10.30,TND,-0.1900000000,270,TVA,TLVIR
61,2010390397,5943043515500,1431167000370,MBXDI-0000084867,983,1240701,None,TND,-0.1900000000,270,TVA,TLVIR
62,2010390397,5943043515500,1431167000370,MBXDI-0000085010,967,1240702,None,TND,-0.1900000000,270,TVA,TLVIR
74,2010390397,5943043515500,1431167000370,2448,5,1240712,None,TND,-0.3800000000,270,TVA,TLVIR
49,2010390397,5943043515500,1431167000370,51207476,47,1240717,None,TND,-0.4750000000,270,TVA,TLVIR
56,2010390397,5943043515500,1431167000370,MBXDI-0000087535,603,1240805,None,TND,-0.1900000000,270,TVA,TLVIR
80,2010390397,5943043515500,1431167000370,MBXDI-0000088673,232,1240823,None,TND,-0.1900000000,270,TVA,TLVIR
69,2010390397,5943043515500,1431167000370,MBXDI-0000089720,1247,1240903,None,TND,-0.1900000000,270,TVA,TLVIR
66,2010390397,5943043515500,1431167000370,MBXDI-0000090603,310,1240913,None,TND,-0.1900000000,270,TVA,TLVIR
84,2010390397,5943043515500,1431167000370,MBXDI-0000092321,607,1241003,None,TND,-0.1900000000,270,TVA,TLVIR
54,2010390397,5943043515500,1431167000370,MBXDI-0000093011,683,1241011,None,TND,-0.1900000000,270,TVA,TLVIR
103,2010390397,5943043515500,1431167000370,MBXDI-0000094920,1459,1241104,None,TND,-0.1900000000,270,TVA,TLVIR
96,2010390397,5943043515500,1431167000370,51433821,93,1241113,None,TND,-0.3800000000,270,TVA,TLVIR
101,2010390397,5943043515500,1431167000370,MBXDI-0000097646,831,1241204,None,TND,-0.1900000000,270,TVA,TLVIR
89,2010390397,5943043515500,1431167000370,MBXDI-0000098930,328,1241220,None,TND,-0.1900000000,270,TVA,TLVIR
75,2010390397,5943043515500,1431167000370,2448,3,1240712,None,TND,-2.0000000000,283,Commission virement re\u,TLVIR
2,2010390397,5943043515500,1431167000370,51160610,79,1240105,2024-01-05 10.08,TND,-2.5000000000,300,Commission virement Emis,TLVIR
6,2010390397,5943043515500,1431167000370,51207205,27,1240207,2024-02-07 11.49,TND,-2.5000000000,300,Commission virement Emis,TLVIR
15,2010390397,5943043515500,1431167000370,MBXDI-0000074858,274,1240223,2024-02-23 13.26,TND,-1.0000000000,300,Commission virement Emis,TLVIR
19,2010390397,5943043515500,1431167000370,MBXDI-0000075907,460,1240305,2024-03-05 10.11,TND,-1.0000000000,300,Commission virement Emis,TLVIR
22,2010390397,5943043515500,1431167000370,MBXDI-0000078129,477,1240404,2024-04-04 07.09,TND,-1.0000000000,300,Commission virement Emis,TLVIR
26,2010390397,5943043515500,1431167000370,MBXDI-0000078611,1035,1240408,2024-04-08 10.46,TND,-1.0000000000,300,Commission virement Emis,TLVIR
28,2010390397,5943043515500,1431167000370,MBXDI-0000080203,1339,1240502,2024-05-02 13.20,TND,-1.0000000000,300,Commission virement Emis,TLVIR
36,2010390397,5943043515500,1431167000370,MBXDI-0000080967,514,1240509,2024-05-09 10.47,TND,-1.0000000000,300,Commission virement Emis,TLVIR
45,2010390397,5943043515500,1431167000370,MBXDI-0000082830,1309,1240603,2024-06-03 10.30,TND,-1.0000000000,300,Commission virement Emis,TLVIR
58,2010390397,5943043515500,1431167000370,MBXDI-0000084867,981,1240701,None,TND,-1.0000000000,300,Commission virement Emis,TLVIR
63,2010390397,5943043515500,1431167000370,MBXDI-0000085010,965,1240702,None,TND,-1.0000000000,300,Commission virement Emis,TLVIR
50,2010390397,5943043515500,1431167000370,51207476,45,1240717,None,TND,-2.5000000000,300,Commission virement Emis,TLVIR
55,2010390397,5943043515500,1431167000370,MBXDI-0000087535,601,1240805,None,TND,-1.0000000000,300,Commission virement Emis,TLVIR
81,2010390397,5943043515500,1431167000370,MBXDI-0000088673,230,1240823,None,TND,-1.0000000000,300,Commission virement Emis,TLVIR
70,2010390397,5943043515500,1431167000370,MBXDI-0000089720,1245,1240903,None,TND,-1.0000000000,300,Commission virement Emis,TLVIR
67,2010390397,5943043515500,1431167000370,MBXDI-0000090603,308,1240913,None,TND,-1.0000000000,300,Commission virement Emis,TLVIR
85,2010390397,5943043515500,1431167000370,MBXDI-0000092321,605,1241003,None,TND,-1.0000000000,300,Commission virement Emis,TLVIR
52,2010390397,5943043515500,1431167000370,MBXDI-0000093011,681,1241011,None,TND,-1.0000000000,300,Commission virement Emis,TLVIR
104,2010390397,5943043515500,1431167000370,MBXDI-0000094920,1457,1241104,None,TND,-1.0000000000,300,Commission virement Emis,TLVIR
98,2010390397,5943043515500,1431167000370,51433821,91,1241113,None,TND,-2.0000000000,300,Commission virement Emis,TLVIR
99,2010390397,5943043515500,1431167000370,MBXDI-0000097646,829,1241204,None,TND,-1.0000000000,300,Commission virement Emis,TLVIR
87,2010390397,5943043515500,1431167000370,MBXDI-0000098930,326,1241220,None,TND,-1.0000000000,300,Commission virement Emis,TLVIR
76,2010390397,5943043515500,1431167000370,2448,2,1240712,None,TND,250.0000000000,524,Virement recu,TLVIR

In [18]:
transaction_router.transaction_code

,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,_merge
0,T24TL,297,Comm.OPPOS EFFET,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN,left_only
1,UAJL,920,Interets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,@@CC,120,Remb avance placement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,TLVIR,010,Debit,NaN,Virement,NaN,NaN,NaN,NaN,NaN,left_only
4,@@FM,401,Exchange Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...
3762,TCTL3,223,Paiement effet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3763,TCTL0,510,Credit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3764,UDHD,878,Transf Sld Data cleaning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,both
3765,USR6,010,Debit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3766,UAZN1,598,Credits divers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [12]:
import pandas as pd

In [12]:
pd.merge(
    left=transaction_router.eq_accountant.accountant_transactions.query("APP_SOURCE_CODE == 'TLVIR'"),
    right=transaction_router.transaction_code[['TRANSACTION_CODE_ATB', 'TRANSACTION_DESC_ATB', 'APP_SOURCE_CODE', 'APP_SOURCE', 'OP_TYPE', 'Categorie_de_transaction', 'TRANSACTION_DESC_GOAML', 'TRANSACTION_CODE_GOAML', 'FUND_CODE_1', 'FUND_CODE_2']],
    left_on=['APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB'],
    right_on=['APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB'],
    how='left',
    indicator=True
).query("APP_SOURCE_CODE == 'TLVIR' and Categorie_de_transaction == 'code affectant directement le compte client (débit/crédit)'").T

,0,1,2,3,50
T24_ACCOUNT,2010390397,2010390397,2010390397,2010390397,2010390397
EQ_ACCOUNT,5943043515500,5943043515500,5943043515500,5943043515500,5943043515500
ORACLE_ACCOUNT,1431167000370,1431167000370,1431167000370,1431167000370,1431167000370
TRANSACTION_REF,51433821,51160610,51207205,51207476,2448
TRANSACTION_SEQ,89,77,25,43,2
TRANSACTION_DATE,1241113,1240105,1240207,1240717,1240712
TRANSACTION_DATE_TS,None,2024-01-05 10.08,2024-02-07 11.49,None,None
TRANSACTION_CURRENCY,TND,TND,TND,TND,TND
TRANSACTION_AMOUNT,-200.0000000000,-240.0000000000,-400.0000000000,-945.0000000000,250.0000000000
TRANSACTION_CODE_ATB,023,024,024,024,524
TRANSACTION_DESC_ATB_x,Virement Emis,Virement Emis,Virement Emis,Virement Emis,Virement recu
APP_SOURCE_CODE,TLVIR,TLVIR,TLVIR,TLVIR,TLVIR
TRANSACTION_DESC_ATB_y,Virement Emis,Virement Emis,Virement Emis,Virement Emis,Virement recu
APP_SOURCE,NaN,NaN,NaN,NaN,IBANK
OP_TYPE,Virement,Virement,Virement,Virement,Virement
Categorie_de_transaction,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML,Virement emis,Virement emis,Virement emis,Virement emis,Virement recus
TRANSACTION_CODE_GOAML,B117,B117,B117,B117,B399
FUND_CODE_1,A,A,A,A,A
FUND_CODE_2,A,A,A,A,A
_merge,both,both,both,both,both

In [26]:
transaction_router.transaction_code[transaction_router.transaction_code['TRANSACTION_CODE_ATB'] == '024']

,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,_merge
197,TCTL3,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
222,UDHD,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
282,TLVIR,024,Virement Emis,NaN,Virement,code affectant directement le compte client (d...,B117,Virement emis,A,A,left_only
1163,TCTL6,024,Virement Emis,IBANK,Virement,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,both
1396,UDHD1,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2322,01CF,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3420,UAGM,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3564,TCTL0,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3605,TCTL7,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3632,TCTL1,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3699,TCTL,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [14]:
transaction_router.transaction_code[transaction_router.transaction_code.TRANSACTION_CODE_ATB == '024']

,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,_merge
197,TCTL3,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
222,UDHD,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
282,TLVIR,024,Virement Emis,NaN,Virement,code affectant directement le compte client (d...,B117,Virement emis,A,A,left_only
1163,TCTL6,024,Virement Emis,IBANK,Virement,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,both
1396,UDHD1,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2322,01CF,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3420,UAGM,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3564,TCTL0,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3605,TCTL7,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3632,TCTL1,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3699,TCTL,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [16]:
import os

In [18]:
os.listdir('./')

['.ipynb_checkpoints',
 'accountant',
 'accountant_trx_f_04_04_2025.xlsx',
 'ibank_virement.ipynb']

In [28]:
trx_code = pd.read_excel('accountant_trx_f_04_04_2025.xlsx', sheet_name='Sheet1')
trx_code['APP_SOURCE_CODE'] = trx_code['APP_SOURCE_CODE'].str.strip()
trx_code['APP_SOURCE_CODE'] = trx_code['APP_SOURCE_CODE'].str.upper()
trx_code['TRANSACTION_CODE_ATB'] = trx_code['TRANSACTION_CODE_ATB'].astype(int).astype(str).str.zfill(3)
trx_code

,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,_merge
0,T24TL,297,Comm.OPPOS EFFET,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN,left_only
1,UAJL,920,Interets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,@@CC,120,Remb avance placement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,TLVIR,010,Debit,NaN,Virement,NaN,NaN,NaN,NaN,NaN,left_only
4,@@FM,401,Exchange Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...
3762,TCTL3,223,Paiement effet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3763,TCTL0,510,Credit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3764,UDHD,878,Transf Sld Data cleaning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,both
3765,USR6,010,Debit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3766,UAZN1,598,Credits divers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [29]:
trx_code[trx_code.TRANSACTION_CODE_ATB == '024']

,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,_merge
197,TCTL3,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
222,UDHD,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
282,TLVIR,024,Virement Emis,NaN,Virement,code affectant directement le compte client (d...,B117,Virement emis,A,A,left_only
1163,TCTL6,024,Virement Emis,IBANK,Virement,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,both
1396,UDHD1,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2322,01CF,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3420,UAGM,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3564,TCTL0,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3605,TCTL7,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3632,TCTL1,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3699,TCTL,024,Virement Emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [13]:
from src.controller.virement import Virement

In [14]:
virement = Virement(DB_CONFIG)

In [15]:
virement.account =  account
virement.year = year
virement.accountant_trx = transaction_router.accountant_transactions_with_trx_code.query(
    "OP_TYPE == 'Virement' and Categorie_de_transaction == 'code affectant directement le compte client (débit/crédit)'"
)
virement.get_transactions()

2025-04-10 07:57:20,707 - INFO - Starting Virement_cc emis's transactions retrieval for account: 5943043515500, year: 2024

===============================
 accountant trx virement
(5, 20)
===============================
===============================
IBANK Virement Trx
(5, 20)
(5, 20)
===============================
===============================
unique_values
{'524', '024', '023'}
===============================

2025-04-10 07:57:21,013 - INFO - Executing query with max_attempts: 1

Connection established successfully.

2025-04-10 07:59:17,780 - INFO - Successfully executed query:
            SELECT
                'Y' AS PART_1_IS_MY_CLIENT,
                'I' AS PART_1_ROLE,
                TRIM(TRIM(VIREMENT_EMIS_MEME_BQE.BRN_ACC) + TRIM(VIREMENT_EMIS_MEME_BQE.ACCOUNT_ID) + TRIM(VIREMENT_EMIS_MEME_BQE.SFX_ACC)) AS EQ_ACCOUNT,
                TRIM(VIREMENT_EMIS_MEME_BQE.POSTING_REF) AS TRANSACTION_REF,
                VIREMENT_EMIS_MEME_BQE.POSTING_DATE AS TRANSACTION_DATE,

                'A' AS FUND_CODE_1,
                VIREMENT_EMIS_MEME_BQE.COD_DEV AS CURRENCY_CODE_1,
                'TN' AS COUNTRY_1,
                VIREMENT_EMIS_MEME_BQE.LOCAL_AMOUNT AS FOREIGN_AMOUNT_1,

                'Y' AS PART_2_IS_MY_CLIENT,
                'ACCOUNT' AS PART_2_TYPE,
                'B' AS PART_2_ROLE,
                EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS AS PART_2_ACCOUNT,
                '' AS PART_2_DETAILS,

                'A' AS FUND_CODE_2,
                COD_DEV AS CURRENCY_CODE_2,
                'TN' AS COUNTRY_2,
                LOCAL_AMOUNT AS FOREIGN_AMOUNT_2,

                '30' + '/' + VIREMENT_EMIS_MEME_BQE.TRANSACTION_NUMBER + '/' +
                    CAST(YEAR(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) AS NVARCHAR(4)) + ' ' +
                    RIGHT('0' + CAST(MONTH(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) AS NVARCHAR(2)), 2) + ' ' +
                    RIGHT('0' + CAST(DAY(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) AS NVARCHAR(2)), 2) AS TRANSACTION_NUMBER,
                'TN' AS TRANSACTION_LOCATION,
                CAST(YEAR(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) AS NVARCHAR(4)) + '-' +
                    RIGHT('0' + CAST(MONTH(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) AS NVARCHAR(2)), 2) + '-' +
                    RIGHT('0' + CAST(DAY(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) AS NVARCHAR(2)), 2) + 'T00:00:00' AS DATE_TRANSACTION,
                VIREMENT_EMIS_MEME_BQE.TRANS_CODE_DESC AS TRANS_CODE_DESC_ATB,
                VIREMENT_EMIS_MEME_BQE.TRANS_CODE AS TRANSMODE_CODE_ATB,
                'B117' AS TRANSACTION_CODE_GOAML,
                VIREMENT_EMIS_MEME_BQE.LOCAL_AMOUNT AS AMOUNT_LOCAL,
                'C' AS TRANSACTION_STATUS_CODE,

                ' BENIF_OPE ' + VIREMENT_EMIS_MEME_BQE.BENIF_OPE AS NAR,

                'VIREMENT_EMIS_MEME_BQE' AS SOURCE

            FROM [MISDW].[GO_AML].[IBANK_VIREMENT_EMIS_MEME_BQE] AS VIREMENT_EMIS_MEME_BQE
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEEAN = VIREMENT_EMIS_MEME_BQE.BENIF_NYMCPT
            WHERE
                YEAR(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) = '2024'--'2024'
                AND VIREMENT_EMIS_MEME_BQE.BRN_ACC + VIREMENT_EMIS_MEME_BQE.ACCOUNT_ID + VIREMENT_EMIS_MEME_BQE.SFX_ACC = '5943043515500'--'5838234740501'

2025-04-10 07:59:17,784 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                'Y' AS PART_1_IS_MY_CLIENT,
                'I' AS PART_1_ROLE,
                TRIM(TRIM(VIREMENT_EMIS_MEME_BQE.BRN_ACC) + TRIM(VIREMENT_EMIS_MEME_BQE.ACCOUNT_ID) + TRIM(VIREMENT_EMIS_MEME_BQE.SFX_ACC)) AS EQ_ACCOUNT,
                TRIM(VIREMENT_EMIS_MEME_BQE.POSTING_REF) AS TRANSACTION_REF,
                VIREMENT_EMIS_MEME_BQE.POSTING_DATE AS TRANSACTION_DATE,

                'A' AS FUND_CODE_1,
                VIREMENT_EMIS_MEME_BQE.COD_DEV AS CURRENCY_CODE_1,
                'TN' AS COUNTRY_1,
                VIREMENT_EMIS_MEME_BQE.LOCAL_AMOUNT AS FOREIGN_AMOUNT_1,

                'Y' AS PART_2_IS_MY_CLIENT,
                'ACCOUNT' AS PART_2_TYPE,
                'B' AS PART_2_ROLE,
                EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS AS PART_2_ACCOUNT,
                '' AS PART_2_DETAILS,

                'A' AS FUND_CODE_2,
                COD_DEV AS CURRENCY_CODE_2,
                'TN' AS COUNTRY_2,
                LOCAL_AMOUNT AS FOREIGN_AMOUNT_2,

                '30' + '/' + VIREMENT_EMIS_MEME_BQE.TRANSACTION_NUMBER + '/' +
                    CAST(YEAR(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) AS NVARCHAR(4)) + ' ' +
                    RIGHT('0' + CAST(MONTH(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) AS NVARCHAR(2)), 2) + ' ' +
                    RIGHT('0' + CAST(DAY(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) AS NVARCHAR(2)), 2) AS TRANSACTION_NUMBER,
                'TN' AS TRANSACTION_LOCATION,
                CAST(YEAR(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) AS NVARCHAR(4)) + '-' +
                    RIGHT('0' + CAST(MONTH(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) AS NVARCHAR(2)), 2) + '-' +
                    RIGHT('0' + CAST(DAY(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) AS NVARCHAR(2)), 2) + 'T00:00:00' AS DATE_TRANSACTION,
                VIREMENT_EMIS_MEME_BQE.TRANS_CODE_DESC AS TRANS_CODE_DESC_ATB,
                VIREMENT_EMIS_MEME_BQE.TRANS_CODE AS TRANSMODE_CODE_ATB,
                'B117' AS TRANSACTION_CODE_GOAML,
                VIREMENT_EMIS_MEME_BQE.LOCAL_AMOUNT AS AMOUNT_LOCAL,
                'C' AS TRANSACTION_STATUS_CODE,

                ' BENIF_OPE ' + VIREMENT_EMIS_MEME_BQE.BENIF_OPE AS NAR,

                'VIREMENT_EMIS_MEME_BQE' AS SOURCE

            FROM [MISDW].[GO_AML].[IBANK_VIREMENT_EMIS_MEME_BQE] AS VIREMENT_EMIS_MEME_BQE
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEEAN = VIREMENT_EMIS_MEME_BQE.BENIF_NYMCPT
            WHERE
                YEAR(VIREMENT_EMIS_MEME_BQE.POSTING_DATE) = '2024'--'2024'
                AND VIREMENT_EMIS_MEME_BQE.BRN_ACC + VIREMENT_EMIS_MEME_BQE.ACCOUNT_ID + VIREMENT_EMIS_MEME_BQE.SFX_ACC = '5943043515500'--'5838234740501'

2025-04-10 07:59:17,795 - INFO - Query executed successfully; Virement_cc emis's transactions data retrieved for the account.
2025-04-10 07:59:17,796 - INFO - Closing database connection.
2025-04-10 07:59:18,488 - INFO - Returning cleaned DataFrame.

Connection closed.
===============================
ibank_virement
(5, 28)
===============================

In [17]:
# accountant vir
accountant_vir = virement.accountant_trx.copy(deep=True)
print(accountant_vir.columns)
accountant_vir

Index(['T24_ACCOUNT', 'EQ_ACCOUNT', 'ORACLE_ACCOUNT', 'TRANSACTION_REF',
       'TRANSACTION_SEQ', 'TRANSACTION_DATE', 'TRANSACTION_DATE_TS',
       'TRANSACTION_CURRENCY', 'TRANSACTION_AMOUNT', 'TRANSACTION_CODE_ATB',
       'TRANSACTION_DESC_ATB_ACC', 'APP_SOURCE_CODE', 'TRANSACTION_DESC_ATB_F',
       'APP_SOURCE', 'OP_TYPE', 'Categorie_de_transaction',
       'TRANSACTION_DESC_GOAML', 'TRANSACTION_CODE_GOAML', 'FUND_CODE_1',
       'FUND_CODE_2'],
      dtype='object')

,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB_ACC,APP_SOURCE_CODE,TRANSACTION_DESC_ATB_F,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_DESC_GOAML,TRANSACTION_CODE_GOAML,FUND_CODE_1,FUND_CODE_2
57,2010390397,5943043515500,1431167000370,51433821,89,1241113,None,TND,-200.0000000000,023,Virement Emis,TLVIR,Virement Emis,IBANK,Virement,code affectant directement le compte client (d...,Virement emis,B117,A,A
58,2010390397,5943043515500,1431167000370,51160610,77,1240105,2024-01-05 10.08,TND,-240.0000000000,024,Virement Emis,TLVIR,Virement Emis,IBANK,Virement,code affectant directement le compte client (d...,Virement emis,B117,A,A
59,2010390397,5943043515500,1431167000370,51207205,25,1240207,2024-02-07 11.49,TND,-400.0000000000,024,Virement Emis,TLVIR,Virement Emis,IBANK,Virement,code affectant directement le compte client (d...,Virement emis,B117,A,A
60,2010390397,5943043515500,1431167000370,51207476,43,1240717,None,TND,-945.0000000000,024,Virement Emis,TLVIR,Virement Emis,IBANK,Virement,code affectant directement le compte client (d...,Virement emis,B117,A,A
107,2010390397,5943043515500,1431167000370,2448,2,1240712,None,TND,250.0000000000,524,Virement recu,TLVIR,Virement recu,IBANK,Virement,code affectant directement le compte client (d...,Virement recus,B399,A,A

In [18]:
# extrat vir ibank
extrat_vir = virement.ibank_virement.virement_transactions.copy(deep=True)

extrat_vir['TRANSACTION_DATE_J'] = '1' + extrat_vir['TRANSACTION_DATE'].dt.strftime('%y%m%d')

# Sort 'virement_transactions' by EQ_ACCOUNT, TRANSACTION_REF, TRANSACTION_DATE_J
extrat_vir = extrat_vir.sort_values(
    by=['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE_J']
)

# Remove duplicates in 'virement_transactions' (keep first occurrence)
extrat_vir = extrat_vir.drop_duplicates(
    subset=['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE_J'], keep='first'
)

print(extrat_vir.columns)

extrat_vir

Index(['PART_1_IS_MY_CLIENT', 'PART_1_ROLE', 'EQ_ACCOUNT', 'TRANSACTION_REF',
       'TRANSACTION_DATE', 'FUND_CODE_1', 'CURRENCY_CODE_1', 'COUNTRY_1',
       'FOREIGN_AMOUNT_1', 'PART_2_IS_MY_CLIENT', 'PART_2_TYPE', 'PART_2_ROLE',
       'PART_2_ACCOUNT', 'PART_2_DETAILS', 'FUND_CODE_2', 'CURRENCY_CODE_2',
       'COUNTRY_2', 'FOREIGN_AMOUNT_2', 'TRANSACTION_NUMBER',
       'TRANSACTION_LOCATION', 'DATE_TRANSACTION', 'TRANS_CODE_DESC_ATB',
       'TRANSMODE_CODE_ATB', 'TRANSACTION_CODE_GOAML', 'AMOUNT_LOCAL',
       'TRANSACTION_STATUS_CODE', 'NAR', 'SOURCE', 'TRANSACTION_DATE_J'],
      dtype='object')

,PART_1_IS_MY_CLIENT,PART_1_ROLE,EQ_ACCOUNT,TRANSACTION_REF,TRANSACTION_DATE,FUND_CODE_1,CURRENCY_CODE_1,COUNTRY_1,FOREIGN_AMOUNT_1,PART_2_IS_MY_CLIENT,...,TRANSACTION_LOCATION,DATE_TRANSACTION,TRANS_CODE_DESC_ATB,TRANSMODE_CODE_ATB,TRANSACTION_CODE_GOAML,AMOUNT_LOCAL,TRANSACTION_STATUS_CODE,NAR,SOURCE,TRANSACTION_DATE_J
0,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE,1241113

In [20]:
pd.merge(
    left=accountant_vir,
    right=extrat_vir,
    left_on=['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE'],
    right_on=['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE_J'],
    how='left',
    indicator=True
).T

,0,1,2,3,4
T24_ACCOUNT,2010390397,2010390397,2010390397,2010390397,2010390397
EQ_ACCOUNT,5943043515500,5943043515500,5943043515500,5943043515500,5943043515500
ORACLE_ACCOUNT,1431167000370,1431167000370,1431167000370,1431167000370,1431167000370
TRANSACTION_REF,51433821,51160610,51207205,51207476,2448
TRANSACTION_SEQ,89,77,25,43,2
TRANSACTION_DATE_x,1241113,1240105,1240207,1240717,1240712
TRANSACTION_DATE_TS,None,2024-01-05 10.08,2024-02-07 11.49,None,None
TRANSACTION_CURRENCY,TND,TND,TND,TND,TND
TRANSACTION_AMOUNT,-200.0000000000,-240.0000000000,-400.0000000000,-945.0000000000,250.0000000000
TRANSACTION_CODE_ATB,023,024,024,024,524
TRANSACTION_DESC_ATB_ACC,Virement Emis,Virement Emis,Virement Emis,Virement Emis,Virement recu
APP_SOURCE_CODE,TLVIR,TLVIR,TLVIR,TLVIR,TLVIR
TRANSACTION_DESC_ATB_F,Virement Emis,Virement Emis,Virement Emis,Virement Emis,Virement recu
APP_SOURCE,IBANK,IBANK,IBANK,IBANK,IBANK
OP_TYPE,Virement,Virement,Virement,Virement,Virement
Categorie_de_transaction,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML,Virement emis,Virement emis,Virement emis,Virement emis,Virement recus
TRANSACTION_CODE_GOAML_x,B117,B117,B117,B117,B399
FUND_CODE_1_x,A,A,A,A,A
FUND_CODE_2_x,A,A,A,A,A
PART_1_IS_MY_CLIENT,Y,NaN,NaN,NaN,NaN
PART_1_ROLE,I,NaN,NaN,NaN,NaN
TRANSACTION_DATE_y,2024-11-13 00:00:00,NaT,NaT,NaT,NaT
FUND_CODE_1_y,A,NaN,NaN,NaN,NaN
CURRENCY_CODE_1,TND,NaN,NaN,NaN,NaN
COUNTRY_1,TN,NaN,NaN,NaN,NaN
FOREIGN_AMOUNT_1,200.000,NaN,NaN,NaN,NaN
PART_2_IS_MY_CLIENT,Y,NaN,NaN,NaN,NaN
PART_2_TYPE,ACCOUNT,NaN,NaN,NaN,NaN
PART_2_ROLE,B,NaN,NaN,NaN,NaN
PART_2_ACCOUNT,5821129753500,NaN,NaN,NaN,NaN
PART_2_DETAILS,,NaN,NaN,NaN,NaN
FUND_CODE_2_y,A,NaN,NaN,NaN,NaN
CURRENCY_CODE_2,TND,NaN,NaN,NaN,NaN
COUNTRY_2,TN,NaN,NaN,NaN,NaN
FOREIGN_AMOUNT_2,200.000,NaN,NaN,NaN,NaN
TRANSACTION_NUMBER,30/51433821/2024 11 13,NaN,NaN,NaN,NaN
TRANSACTION_LOCATION,TN,NaN,NaN,NaN,NaN
DATE_TRANSACTION,2024-11-13T00:00:00,NaN,NaN,NaN,NaN
TRANS_CODE_DESC_ATB,Virement Emis,NaN,NaN,NaN,NaN
TRANSMODE_CODE_ATB,024,NaN,NaN,NaN,NaN
TRANSACTION_CODE_GOAML_y,B117,NaN,NaN,NaN,NaN
AMOUNT_LOCAL,200.000,NaN,NaN,NaN,NaN
TRANSACTION_STATUS_CODE,C,NaN,NaN,NaN,NaN
NAR,BENIF_OPE STMDLP,NaN,NaN,NaN,NaN
SOURCE,VIREMENT_EMIS_MEME_BQE,NaN,NaN,NaN,NaN
TRANSACTION_DATE_J,1241113,NaN,NaN,NaN,NaN
_merge,both,left_only,left_only,left_only,left_only

In [47]:
accountant_vir.T

,57,58,59,60,107
T24_ACCOUNT,2010390397,2010390397,2010390397,2010390397,2010390397
EQ_ACCOUNT,5943043515500,5943043515500,5943043515500,5943043515500,5943043515500
ORACLE_ACCOUNT,1431167000370,1431167000370,1431167000370,1431167000370,1431167000370
TRANSACTION_REF,51433821,51160610,51207205,51207476,2448
TRANSACTION_SEQ,89,77,25,43,2
TRANSACTION_DATE,1241113,1240105,1240207,1240717,1240712
TRANSACTION_DATE_TS,None,2024-01-05 10.08,2024-02-07 11.49,None,None
TRANSACTION_CURRENCY,TND,TND,TND,TND,TND
TRANSACTION_AMOUNT,-200.0000000000,-240.0000000000,-400.0000000000,-945.0000000000,250.0000000000
TRANSACTION_CODE_ATB,023,024,024,024,524
TRANSACTION_DESC_ATB_ACC,Virement Emis,Virement Emis,Virement Emis,Virement Emis,Virement recu
APP_SOURCE_CODE,TLVIR,TLVIR,TLVIR,TLVIR,TLVIR
TRANSACTION_DESC_ATB_F,Virement Emis,Virement Emis,Virement Emis,Virement Emis,Virement recu
APP_SOURCE,NaN,NaN,NaN,NaN,IBANK
OP_TYPE,Virement,Virement,Virement,Virement,Virement
Categorie_de_transaction,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...
TRANSACTION_DESC_GOAML,Virement emis,Virement emis,Virement emis,Virement emis,Virement recus
TRANSACTION_CODE_GOAML,B117,B117,B117,B117,B399
FUND_CODE_1,A,A,A,A,A
FUND_CODE_2,A,A,A,A,A

In [29]:
accountant_vir = virement.ibank_virement.virement_transactions.copy(deep=True)

In [30]:
extrat_vir = virement.ibank_virement.virement_transactions.drop_duplicates(subset=['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE']).copy(deep=True)

In [31]:
accountant_vir

,PART_1_IS_MY_CLIENT,PART_1_ROLE,EQ_ACCOUNT,TRANSACTION_REF,TRANSACTION_DATE,FUND_CODE_1,CURRENCY_CODE_1,COUNTRY_1,FOREIGN_AMOUNT_1,PART_2_IS_MY_CLIENT,...,TRANSACTION_NUMBER,TRANSACTION_LOCATION,DATE_TRANSACTION,TRANS_CODE_DESC_ATB,TRANSMODE_CODE_ATB,TRANSACTION_CODE_GOAML,AMOUNT_LOCAL,TRANSACTION_STATUS_CODE,NAR,SOURCE
0,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,30/51433821/2024 11 13,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE
1,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,30/51433821/2024 11 13,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE
2,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,30/51433821/2024 11 13,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE
3,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,30/51433821/2024 11 13,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE
4,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,30/51433821/2024 11 13,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE

In [32]:
extrat_vir

,PART_1_IS_MY_CLIENT,PART_1_ROLE,EQ_ACCOUNT,TRANSACTION_REF,TRANSACTION_DATE,FUND_CODE_1,CURRENCY_CODE_1,COUNTRY_1,FOREIGN_AMOUNT_1,PART_2_IS_MY_CLIENT,...,TRANSACTION_NUMBER,TRANSACTION_LOCATION,DATE_TRANSACTION,TRANS_CODE_DESC_ATB,TRANSMODE_CODE_ATB,TRANSACTION_CODE_GOAML,AMOUNT_LOCAL,TRANSACTION_STATUS_CODE,NAR,SOURCE
0,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,30/51433821/2024 11 13,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE

In [33]:
pd.merge(
    left=accountant_vir,
    right=extrat_vir,
    left_on=['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE'],
    right_on=['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE'],
    how='left',
    indicator=True
)

,PART_1_IS_MY_CLIENT_x,PART_1_ROLE_x,EQ_ACCOUNT,TRANSACTION_REF,TRANSACTION_DATE,FUND_CODE_1_x,CURRENCY_CODE_1_x,COUNTRY_1_x,FOREIGN_AMOUNT_1_x,PART_2_IS_MY_CLIENT_x,...,TRANSACTION_LOCATION_y,DATE_TRANSACTION_y,TRANS_CODE_DESC_ATB_y,TRANSMODE_CODE_ATB_y,TRANSACTION_CODE_GOAML_y,AMOUNT_LOCAL_y,TRANSACTION_STATUS_CODE_y,NAR_y,SOURCE_y,_merge
0,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE,both
1,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE,both
2,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE,both
3,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE,both
4,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE,both

In [24]:
accountant_vir['TRANSACTION_DATE_J'] = '1' + accountant_vir['TRANSACTION_DATE'].dt.strftime('%y%m%d')

# Sort 'virement_transactions' by EQ_ACCOUNT, TRANSACTION_REF, TRANSACTION_DATE_J
accountant_vir = accountant_vir.sort_values(
    by=['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE_J']
)

# Remove duplicates in 'virement_transactions' (keep first occurrence)
accountant_vir = accountant_vir.drop_duplicates(
    subset=['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE_J'], keep='first'
)

accountant_vir

,PART_1_IS_MY_CLIENT,PART_1_ROLE,EQ_ACCOUNT,TRANSACTION_REF,TRANSACTION_DATE,FUND_CODE_1,CURRENCY_CODE_1,COUNTRY_1,FOREIGN_AMOUNT_1,PART_2_IS_MY_CLIENT,...,TRANSACTION_LOCATION,DATE_TRANSACTION,TRANS_CODE_DESC_ATB,TRANSMODE_CODE_ATB,TRANSACTION_CODE_GOAML,AMOUNT_LOCAL,TRANSACTION_STATUS_CODE,NAR,SOURCE,TRANSACTION_DATE_J
0,Y,I,5943043515500,51433821,2024-11-13,A,TND,TN,200.000,Y,...,TN,2024-11-13T00:00:00,Virement Emis,024,B117,200.000,C,BENIF_OPE STMDLP,VIREMENT_EMIS_MEME_BQE,1241113

In [27]:
accountant_vir.columns

Index(['PART_1_IS_MY_CLIENT', 'PART_1_ROLE', 'EQ_ACCOUNT', 'TRANSACTION_REF',
       'TRANSACTION_DATE', 'FUND_CODE_1', 'CURRENCY_CODE_1', 'COUNTRY_1',
       'FOREIGN_AMOUNT_1', 'PART_2_IS_MY_CLIENT', 'PART_2_TYPE', 'PART_2_ROLE',
       'PART_2_ACCOUNT', 'PART_2_DETAILS', 'FUND_CODE_2', 'CURRENCY_CODE_2',
       'COUNTRY_2', 'FOREIGN_AMOUNT_2', 'TRANSACTION_NUMBER',
       'TRANSACTION_LOCATION', 'DATE_TRANSACTION', 'TRANS_CODE_DESC_ATB',
       'TRANSMODE_CODE_ATB', 'TRANSACTION_CODE_GOAML', 'AMOUNT_LOCAL',
       'TRANSACTION_STATUS_CODE', 'NAR', 'SOURCE', 'TRANSACTION_DATE_J'],
      dtype='object')

In [25]:
import pandas as pd

In [28]:
pd.merge(
    left=accountant_vir,
    right=extrat_vir,
    left_on=['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE'],
    right_on=['EQ_ACCOUNT', 'TRANSACTION_REF', 'TRANSACTION_DATE_J'],
    how='left',
    indicator=True
)

KeyError: 'TRANSACTION_DATE_J'