In [1]:
import sys
sys.path.append('../')

In [2]:
from src.config import DB_CONFIG, TREANSACTION_CODE

In [8]:
from src.model.get_client_T24 import GetClientT24

In [11]:
get_client_T24 = GetClientT24(DB_CONFIG)

In [12]:
account_number = '5820136815521'
print(get_client_T24.account_status_lookup(account_number)) # True -> Active Account

account_correspondences, account_details, customer_id, account_type, account_rp = get_client_T24.get_client(account_number)

2025-04-14 10:23:25,314 - INFO - Executing account status lookup for account: 5820136815521

Connection established successfully.

2025-04-14 10:23:25,718 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820136815521'

2025-04-14 10:23:25,720 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820136815521'

2025-04-14 10:23:25,721 - INFO - Account 5820136815521 is IS_ACTIVE
2025-04-14 10:23:25,750 - INFO - Executing account status lookup for account: 5820136815521
2025-04-14 10:23:25,826 - INFO - Successfully executed query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820136815521'

2025-04-14 10:23:25,828 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            CASE
                WHEN COUNT(*) > 0 THEN 'IS_CLOSED'
                WHEN COUNT(*) = 0 THEN 'IS_ACTIVE'
            END AS STATUS
        FROM [MISDW].[TRG].[T24_FATB_ACCOUNT_CLOSED] AS T24_ACCOUNT_CLOSED
        LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT_CLOSED.ACCOUNT_NO = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
        WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820136815521'

2025-04-14 10:23:25,829 - INFO - Account 5820136815521 is IS_ACTIVE
2025-04-14 10:23:25,849 - INFO - Executing query to retrieve account information for account number: 5820136815521

Connection closed.
True
Connection established successfully.
Connection closed.
Connection established successfully.

2025-04-14 10:23:28,085 - INFO - Successfully executed query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820136815521'

2025-04-14 10:23:28,087 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
					T24_ACCOUNT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                    ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
					EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                    T24_ACCOUNT.ARRANGEMENT_ID AS ARRANGEMENT_ID,
                    T24_ACCOUNT.MANDATE_RECORD,
                    T24_CUSTOMER.L_NATURE_CLIENT AS CUST_TYPE,
                    T24_CUSTOMER.CUSTOMER_NO AS CUSTOMER_ID,
                    T24_ACCOUNT.ALT_ACCT_ID AS RIB,
                    CASE
                        WHEN T24_ACCOUNT.CURRENCY = 'TDC' THEN 'TND'
                        ELSE T24_ACCOUNT.CURRENCY
                    END AS CURRENCY_DESC,
                    --T24_ACCOUNT.CURRENCY AS CURRENCY_DESC,
                    --T24_ACCOUNT.SHORT_TITLE AS ACCOUNT_NAME,
					'T24 - ' + T24_CUSTOMER.NAME_1 AS ACCOUNT_NAME,
                    T24_ACCOUNT.CATEGORY AS ACOUNT_TYPE_CODE_ATB,
                    ACCOUNT_TYPE.Description_ATB AS ACOUNT_TYPE_DESC_ATB,
                    ACCOUNT_TYPE.ACCOUNT_TYPE_goAML AS ACOUNT_TYPE_CODE_goAML,
                    EQ_ACCOUNT.EQA_BALANCE_CCY AS BALANCE,
                    T24_ACCOUNT.OPENING_DATE,
                    CASE
                        WHEN T24_ACCOUNT.OPENING_DATE = 0 THEN '0000-00-00T00:00:00'
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))) = 1 THEN
                            CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, T24_ACCOUNT.OPENING_DATE))), 23) + 'T00:00:00'
                        ELSE NULL
                    END AS OPENING_DATE_FORMATTED,
                    NULL AS ACCT_CLOSE_DATE,
                    NULL AS CLOSED_DATE_FORMATTED,
                    'A' AS STATUS,
                    'T24' AS SOURCE
                FROM [MISDW].[TRG].[T24_FATB_ACCOUNT] AS T24_ACCOUNT
                LEFT JOIN [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS T24_CUSTOMER ON T24_CUSTOMER.CUSTOMER_CODE = T24_ACCOUNT.CUSTOMER_NO
                LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS ALTERNATE_ACCOUNT ON T24_ACCOUNT.ACCOUNT_NUMBER = ALTERNATE_ACCOUNT.GLOBUS_ACCT_NUMBER
				LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = ALTERNATIVE_NUMBER
				LEFT JOIN [MISDW].[GO_AML].[EQA_ACCOUNT_DAILY] AS EQ_ACCOUNT ON EQ_ACCOUNT.BRN_ACC + EQ_ACCOUNT.BN + EQ_ACCOUNT.SFX_ACC = ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE_EQ_T24] ON ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_T24 = T24_ACCOUNT.CATEGORY
                LEFT JOIN [MISDW].[GO_AML].[ACCOUNT_TYPE] ON ACCOUNT_TYPE.ACCOUNT_TYPE_ATB = ACCOUNT_TYPE_EQ_T24.ACCOUNT_TYPE_EQ
				WHERE ALTERNATE_ACCOUNT.ALTERNATIVE_NUMBER = '5820136815521'

2025-04-14 10:23:28,090 - INFO - Successfully retrieved account information for account number: 5820136815521
2025-04-14 10:23:28,105 - INFO - Starting to retrieve PM data for customer ID 136815
2025-04-14 10:23:28,202 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PM
            SELECT
                NAME_1 AS NAME,
                'N.A' AS LEGAL_FORM_DESC_ATB,
                L_FORM_JURID AS LEGAL_FORM_CODE_ATB,
                FJ.code_goAML AS LEGAL_FORM_CODE_goAML,
                INDUSTRY.DESCRIPTION AS BUSINESS_DESC,
                CASE
                    WHEN CUSTOMER.L_SIT_JUR = 2 THEN 'A'
                    ELSE 'I'
                END AS ENTITY_STATUS,
                '2' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COUNTRY AS INCORPORATION_COUNTRY_CODE,
                CASE
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, BIRTH_INCORP_DATE))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, BIRTH_INCORP_DATE))), 23) + 'T00:00:00'
                    ELSE '0000-00-00T00:00:00'
                END AS INCORPORATION_DATE,
                'MF' AS ENTITY_IDENTIFIER_TYPE,
                CUSTOMER.LEGAL_ID AS ENTITY_IDENTIFIER_ID,
                CUSTOMER.COUNTRY AS ENTITY_ISSUE_COUNTRY
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
            LEFT JOIN [MISDW].[GO_AML].[FORME_JURIDIQUE] AS FJ ON FORMAT(CAST(FJ.ID_FORMJ AS INT), '00') = FORMAT(CAST(CUSTOMER.L_FORM_JURID AS INT), '00')
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_INDUSTRY] AS INDUSTRY ON RIGHT(REPLICATE('0', 4) + INDUSTRY.INDUSTRY_CODE, 4) = RIGHT(REPLICATE('0', 4) + CUSTOMER.INDUSTRY, 4)
            WHERE CUSTOMER_CODE = '136815'

2025-04-14 10:23:28,203 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PM
            SELECT
                NAME_1 AS NAME,
                'N.A' AS LEGAL_FORM_DESC_ATB,
                L_FORM_JURID AS LEGAL_FORM_CODE_ATB,
                FJ.code_goAML AS LEGAL_FORM_CODE_goAML,
                INDUSTRY.DESCRIPTION AS BUSINESS_DESC,
                CASE
                    WHEN CUSTOMER.L_SIT_JUR = 2 THEN 'A'
                    ELSE 'I'
                END AS ENTITY_STATUS,
                '2' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COUNTRY AS INCORPORATION_COUNTRY_CODE,
                CASE
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, BIRTH_INCORP_DATE))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, BIRTH_INCORP_DATE))), 23) + 'T00:00:00'
                    ELSE '0000-00-00T00:00:00'
                END AS INCORPORATION_DATE,
                'MF' AS ENTITY_IDENTIFIER_TYPE,
                CUSTOMER.LEGAL_ID AS ENTITY_IDENTIFIER_ID,
                CUSTOMER.COUNTRY AS ENTITY_ISSUE_COUNTRY
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
            LEFT JOIN [MISDW].[GO_AML].[FORME_JURIDIQUE] AS FJ ON FORMAT(CAST(FJ.ID_FORMJ AS INT), '00') = FORMAT(CAST(CUSTOMER.L_FORM_JURID AS INT), '00')
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_INDUSTRY] AS INDUSTRY ON RIGHT(REPLICATE('0', 4) + INDUSTRY.INDUSTRY_CODE, 4) = RIGHT(REPLICATE('0', 4) + CUSTOMER.INDUSTRY, 4)
            WHERE CUSTOMER_CODE = '136815'

2025-04-14 10:23:28,205 - INFO - Retrieved PM data successfully for customer ID 136815
2025-04-14 10:23:28,229 - INFO - Executing query to retrieve related third party information for customer id : 136815

Connection closed.
Connection established successfully.
Connection closed.
Connection established successfully.

2025-04-14 10:23:28,345 - INFO - Successfully executed query:
        SELECT
            RELATION_CUSTOMER.CUSTOMER,
            RELATION_CUSTOMER.OF_CUSTOMER_2,
            RELATION_CUSTOMER.IS_RELATION_1,
            CUSTOMER_ROLE.ROLE_14
        FROM [MISDW].[GO_AML].[T24_FBNK_RELATION_CUSTOMER] AS RELATION_CUSTOMER
        LEFT JOIN [MISDW].[GO_AML].[T24_FBNK_CUSTOMER_ROLE] AS CUSTOMER_ROLE ON RELATION_CUSTOMER.CUSTOMER = CUSTOMER_ROLE.RECID
        WHERE RELATION_CUSTOMER.CUSTOMER = '136815'

2025-04-14 10:23:28,346 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            RELATION_CUSTOMER.CUSTOMER,
            RELATION_CUSTOMER.OF_CUSTOMER_2,
            RELATION_CUSTOMER.IS_RELATION_1,
            CUSTOMER_ROLE.ROLE_14
        FROM [MISDW].[GO_AML].[T24_FBNK_RELATION_CUSTOMER] AS RELATION_CUSTOMER
        LEFT JOIN [MISDW].[GO_AML].[T24_FBNK_CUSTOMER_ROLE] AS CUSTOMER_ROLE ON RELATION_CUSTOMER.CUSTOMER = CUSTOMER_ROLE.RECID
        WHERE RELATION_CUSTOMER.CUSTOMER = '136815'

2025-04-14 10:23:28,348 - INFO - Successfully retrieved related third party information for customer id : 136815
2025-04-14 10:23:28,371 - INFO - Starting to retrieve PM-related person details based on Level 1 results.
2025-04-14 10:23:28,377 - INFO - Processing row for RELATED_PERSON_ID 104371 with RELATED_PERSON_ROLE 40
2025-04-14 10:23:28,475 - INFO - Successfully executed query:
                SELECT
                    CUSTOMER_CODE AS CUSTOMER_ID,
                	L_NATURE_CLIENT AS CUSTOMER_TYPE,
                    CASE
                        WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                        WHEN GENDER = 'MALE' THEN 'M'
                        WHEN GENDER = 'FEMALE' THEN 'F'
                    END AS GENDER,
                    GIVEN_NAMES AS FIRST_NAME,
                    FAMILY_NAME AS LAST_NAME,
                    CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                    CASE
					    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					        NULLIF(COUNTRY, ''),
					        NULLIF(CUST_BIRTH_COUNTRY, ''),
					        NULLIF(L_PLACE_OF_BIRT, '')
					    )
					END AS BIRTH_PLACE,
                    LEGAL_DOC_NAME,
                    LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                    LEGAL_ISS_AUTH, --Pays d'émission du passeport
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                    NATIONALITY,
                    RESIDENCE,
                    '1' AS ADDRESS_TYPE,
                    COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
	                CASE
					    WHEN COALESCE(COUNTRY, '') = ''
					         AND COALESCE(TOWN_COUNTRY, '') = ''
					         AND COALESCE(ADDRESS_ITEM1, '') = ''
					         AND COALESCE(ADDRESS_ITEM2, '') = ''
					         AND COALESCE(STREET, '') = ''
					         AND COALESCE(ADDRESS, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					         NULLIF(COUNTRY, ''),
					         NULLIF(TOWN_COUNTRY, ''),
					         NULLIF(ADDRESS_ITEM1, ''),
					         NULLIF(ADDRESS_ITEM2, ''),
					         NULLIF(STREET, ''),
					         NULLIF(ADDRESS, ''))
					END AS ADDRESS,
                    COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                	COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION,
                    '305' AS RELATED_PERSON_RELATION_CODE_ATB,
                    '40' AS RELATED_PERSON_ROLE_CODE_ATB,
                    'CUSTOMER_ID : 104371 N.A - ROLE_CODE_goAML' AS ROLE_ENTITY -- relation with the entity
                    --'MAND' AS ROLE_ACCOUNT -- Relation to the account
                --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS CUSTOMER
                FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
                LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
                WHERE
                    CUSTOMER.CUSTOMER_CODE = '104371'

2025-04-14 10:23:28,476 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
                    CUSTOMER_CODE AS CUSTOMER_ID,
                	L_NATURE_CLIENT AS CUSTOMER_TYPE,
                    CASE
                        WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                        WHEN GENDER = 'MALE' THEN 'M'
                        WHEN GENDER = 'FEMALE' THEN 'F'
                    END AS GENDER,
                    GIVEN_NAMES AS FIRST_NAME,
                    FAMILY_NAME AS LAST_NAME,
                    CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                    CASE
					    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					        NULLIF(COUNTRY, ''),
					        NULLIF(CUST_BIRTH_COUNTRY, ''),
					        NULLIF(L_PLACE_OF_BIRT, '')
					    )
					END AS BIRTH_PLACE,
                    LEGAL_DOC_NAME,
                    LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                    LEGAL_ISS_AUTH, --Pays d'émission du passeport
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                    NATIONALITY,
                    RESIDENCE,
                    '1' AS ADDRESS_TYPE,
                    COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
	                CASE
					    WHEN COALESCE(COUNTRY, '') = ''
					         AND COALESCE(TOWN_COUNTRY, '') = ''
					         AND COALESCE(ADDRESS_ITEM1, '') = ''
					         AND COALESCE(ADDRESS_ITEM2, '') = ''
					         AND COALESCE(STREET, '') = ''
					         AND COALESCE(ADDRESS, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					         NULLIF(COUNTRY, ''),
					         NULLIF(TOWN_COUNTRY, ''),
					         NULLIF(ADDRESS_ITEM1, ''),
					         NULLIF(ADDRESS_ITEM2, ''),
					         NULLIF(STREET, ''),
					         NULLIF(ADDRESS, ''))
					END AS ADDRESS,
                    COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                	COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION,
                    '305' AS RELATED_PERSON_RELATION_CODE_ATB,
                    '40' AS RELATED_PERSON_ROLE_CODE_ATB,
                    'CUSTOMER_ID : 104371 N.A - ROLE_CODE_goAML' AS ROLE_ENTITY -- relation with the entity
                    --'MAND' AS ROLE_ACCOUNT -- Relation to the account
                --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS CUSTOMER
                FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
                LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
                WHERE
                    CUSTOMER.CUSTOMER_CODE = '104371'

2025-04-14 10:23:28,479 - INFO - Data retrieved successfully for RELATED_PERSON_ID 104371
2025-04-14 10:23:28,479 - INFO - Processing row for RELATED_PERSON_ID 567297 with RELATED_PERSON_ROLE 10
2025-04-14 10:23:28,557 - INFO - Successfully executed query:
                SELECT
                    CUSTOMER_CODE AS CUSTOMER_ID,
                	L_NATURE_CLIENT AS CUSTOMER_TYPE,
                    CASE
                        WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                        WHEN GENDER = 'MALE' THEN 'M'
                        WHEN GENDER = 'FEMALE' THEN 'F'
                    END AS GENDER,
                    GIVEN_NAMES AS FIRST_NAME,
                    FAMILY_NAME AS LAST_NAME,
                    CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                    CASE
					    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					        NULLIF(COUNTRY, ''),
					        NULLIF(CUST_BIRTH_COUNTRY, ''),
					        NULLIF(L_PLACE_OF_BIRT, '')
					    )
					END AS BIRTH_PLACE,
                    LEGAL_DOC_NAME,
                    LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                    LEGAL_ISS_AUTH, --Pays d'émission du passeport
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                    NATIONALITY,
                    RESIDENCE,
                    '1' AS ADDRESS_TYPE,
                    COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
	                CASE
					    WHEN COALESCE(COUNTRY, '') = ''
					         AND COALESCE(TOWN_COUNTRY, '') = ''
					         AND COALESCE(ADDRESS_ITEM1, '') = ''
					         AND COALESCE(ADDRESS_ITEM2, '') = ''
					         AND COALESCE(STREET, '') = ''
					         AND COALESCE(ADDRESS, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					         NULLIF(COUNTRY, ''),
					         NULLIF(TOWN_COUNTRY, ''),
					         NULLIF(ADDRESS_ITEM1, ''),
					         NULLIF(ADDRESS_ITEM2, ''),
					         NULLIF(STREET, ''),
					         NULLIF(ADDRESS, ''))
					END AS ADDRESS,
                    COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                	COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION,
                    '307' AS RELATED_PERSON_RELATION_CODE_ATB,
                    '10' AS RELATED_PERSON_ROLE_CODE_ATB,
                    'CUSTOMER_ID : 567297 N.A - ROLE_CODE_goAML' AS ROLE_ENTITY -- relation with the entity
                    --'MAND' AS ROLE_ACCOUNT -- Relation to the account
                --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS CUSTOMER
                FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
                LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
                WHERE
                    CUSTOMER.CUSTOMER_CODE = '567297'

Connection closed.
********************************
df_related_third_party_processed
    PM_ID RELATED_PERSON_ID RELATED_PERSON_RELATION RELATED_PERSON_ROLE
0  136815            104371                     305                  40
1  136815            567297                     307                  10
2  136815            567297                     309                  20
********************************
Connection established successfully.
===== in get_PM_related_persons_l2 =====
RELATED_PERSON_RELATION --- RELATED_PERSON_ROLE
305 40
===== in get_PM_related_persons_l2 =====
RELATED_PERSON_RELATION --- RELATED_PERSON_ROLE
307 10

2025-04-14 10:23:28,558 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
                    CUSTOMER_CODE AS CUSTOMER_ID,
                	L_NATURE_CLIENT AS CUSTOMER_TYPE,
                    CASE
                        WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                        WHEN GENDER = 'MALE' THEN 'M'
                        WHEN GENDER = 'FEMALE' THEN 'F'
                    END AS GENDER,
                    GIVEN_NAMES AS FIRST_NAME,
                    FAMILY_NAME AS LAST_NAME,
                    CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                    CASE
					    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					        NULLIF(COUNTRY, ''),
					        NULLIF(CUST_BIRTH_COUNTRY, ''),
					        NULLIF(L_PLACE_OF_BIRT, '')
					    )
					END AS BIRTH_PLACE,
                    LEGAL_DOC_NAME,
                    LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                    LEGAL_ISS_AUTH, --Pays d'émission du passeport
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                    NATIONALITY,
                    RESIDENCE,
                    '1' AS ADDRESS_TYPE,
                    COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
	                CASE
					    WHEN COALESCE(COUNTRY, '') = ''
					         AND COALESCE(TOWN_COUNTRY, '') = ''
					         AND COALESCE(ADDRESS_ITEM1, '') = ''
					         AND COALESCE(ADDRESS_ITEM2, '') = ''
					         AND COALESCE(STREET, '') = ''
					         AND COALESCE(ADDRESS, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					         NULLIF(COUNTRY, ''),
					         NULLIF(TOWN_COUNTRY, ''),
					         NULLIF(ADDRESS_ITEM1, ''),
					         NULLIF(ADDRESS_ITEM2, ''),
					         NULLIF(STREET, ''),
					         NULLIF(ADDRESS, ''))
					END AS ADDRESS,
                    COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                	COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION,
                    '307' AS RELATED_PERSON_RELATION_CODE_ATB,
                    '10' AS RELATED_PERSON_ROLE_CODE_ATB,
                    'CUSTOMER_ID : 567297 N.A - ROLE_CODE_goAML' AS ROLE_ENTITY -- relation with the entity
                    --'MAND' AS ROLE_ACCOUNT -- Relation to the account
                --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS CUSTOMER
                FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
                LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
                WHERE
                    CUSTOMER.CUSTOMER_CODE = '567297'

2025-04-14 10:23:28,561 - INFO - Data retrieved successfully for RELATED_PERSON_ID 567297
2025-04-14 10:23:28,562 - INFO - Processing row for RELATED_PERSON_ID 567297 with RELATED_PERSON_ROLE 20
2025-04-14 10:23:28,641 - INFO - Successfully executed query:
                SELECT
                    CUSTOMER_CODE AS CUSTOMER_ID,
                	L_NATURE_CLIENT AS CUSTOMER_TYPE,
                    CASE
                        WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                        WHEN GENDER = 'MALE' THEN 'M'
                        WHEN GENDER = 'FEMALE' THEN 'F'
                    END AS GENDER,
                    GIVEN_NAMES AS FIRST_NAME,
                    FAMILY_NAME AS LAST_NAME,
                    CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                    CASE
					    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					        NULLIF(COUNTRY, ''),
					        NULLIF(CUST_BIRTH_COUNTRY, ''),
					        NULLIF(L_PLACE_OF_BIRT, '')
					    )
					END AS BIRTH_PLACE,
                    LEGAL_DOC_NAME,
                    LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                    LEGAL_ISS_AUTH, --Pays d'émission du passeport
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                    NATIONALITY,
                    RESIDENCE,
                    '1' AS ADDRESS_TYPE,
                    COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
	                CASE
					    WHEN COALESCE(COUNTRY, '') = ''
					         AND COALESCE(TOWN_COUNTRY, '') = ''
					         AND COALESCE(ADDRESS_ITEM1, '') = ''
					         AND COALESCE(ADDRESS_ITEM2, '') = ''
					         AND COALESCE(STREET, '') = ''
					         AND COALESCE(ADDRESS, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					         NULLIF(COUNTRY, ''),
					         NULLIF(TOWN_COUNTRY, ''),
					         NULLIF(ADDRESS_ITEM1, ''),
					         NULLIF(ADDRESS_ITEM2, ''),
					         NULLIF(STREET, ''),
					         NULLIF(ADDRESS, ''))
					END AS ADDRESS,
                    COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                	COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION,
                    '309' AS RELATED_PERSON_RELATION_CODE_ATB,
                    '20' AS RELATED_PERSON_ROLE_CODE_ATB,
                    'CUSTOMER_ID : 567297 N.A - ROLE_CODE_goAML' AS ROLE_ENTITY -- relation with the entity
                    --'MAND' AS ROLE_ACCOUNT -- Relation to the account
                --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS CUSTOMER
                FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
                LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
                WHERE
                    CUSTOMER.CUSTOMER_CODE = '567297'

2025-04-14 10:23:28,643 - INFO - Successfully converted query result to DataFrame for query:
                SELECT
                    CUSTOMER_CODE AS CUSTOMER_ID,
                	L_NATURE_CLIENT AS CUSTOMER_TYPE,
                    CASE
                        WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                        WHEN GENDER = 'MALE' THEN 'M'
                        WHEN GENDER = 'FEMALE' THEN 'F'
                    END AS GENDER,
                    GIVEN_NAMES AS FIRST_NAME,
                    FAMILY_NAME AS LAST_NAME,
                    CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                    CASE
					    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					        NULLIF(COUNTRY, ''),
					        NULLIF(CUST_BIRTH_COUNTRY, ''),
					        NULLIF(L_PLACE_OF_BIRT, '')
					    )
					END AS BIRTH_PLACE,
                    LEGAL_DOC_NAME,
                    LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                    LEGAL_ISS_AUTH, --Pays d'émission du passeport
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                    CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                    NATIONALITY,
                    RESIDENCE,
                    '1' AS ADDRESS_TYPE,
                    COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
	                CASE
					    WHEN COALESCE(COUNTRY, '') = ''
					         AND COALESCE(TOWN_COUNTRY, '') = ''
					         AND COALESCE(ADDRESS_ITEM1, '') = ''
					         AND COALESCE(ADDRESS_ITEM2, '') = ''
					         AND COALESCE(STREET, '') = ''
					         AND COALESCE(ADDRESS, '') = ''
					        THEN 'N.A'
					    ELSE CONCAT_WS(' - ',
					         NULLIF(COUNTRY, ''),
					         NULLIF(TOWN_COUNTRY, ''),
					         NULLIF(ADDRESS_ITEM1, ''),
					         NULLIF(ADDRESS_ITEM2, ''),
					         NULLIF(STREET, ''),
					         NULLIF(ADDRESS, ''))
					END AS ADDRESS,
                    COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                	COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION,
                    '309' AS RELATED_PERSON_RELATION_CODE_ATB,
                    '20' AS RELATED_PERSON_ROLE_CODE_ATB,
                    'CUSTOMER_ID : 567297 N.A - ROLE_CODE_goAML' AS ROLE_ENTITY -- relation with the entity
                    --'MAND' AS ROLE_ACCOUNT -- Relation to the account
                --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER] AS CUSTOMER
                FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS] AS CUSTOMER
                LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
                WHERE
                    CUSTOMER.CUSTOMER_CODE = '567297'

2025-04-14 10:23:28,645 - INFO - Data retrieved successfully for RELATED_PERSON_ID 567297
2025-04-14 10:23:28,645 - INFO - Finished processing all rows for PM-related person details.
2025-04-14 10:23:28,672 - INFO - Executing query to retrieve mandates information for account mandate id : 136815.20221130-1
2025-04-14 10:23:28,715 - INFO - Successfully executed query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = '136815.20221130-1'

2025-04-14 10:23:28,716 - INFO - Successfully converted query result to DataFrame for query:
        SELECT
            EB_MANDATE.MANDATE_ID,
            EB_MANDATE.SIGNATORY_GROUP,
            SIGNATORY_G.SIGNATORY_CUSTOMER_2,
            SIGNATORY_G.START_DATE_3,
            SIGNATORY_G.END_DATE_4
        FROM [MISDW].[GO_AML].[T24_EB_MANDATE] AS EB_MANDATE
        LEFT JOIN [MISDW].[GO_AML].[T24_EB_SIGNATORY_G001] AS SIGNATORY_G ON SIGNATORY_G.SIG_GROUP_ID = EB_MANDATE.SIGNATORY_GROUP
        WHERE
            EB_MANDATE.MANDATE_ID = '136815.20221130-1'

2025-04-14 10:23:28,718 - INFO - Successfully retrieved mandates information for account mandate id : 136815.20221130-1
2025-04-14 10:23:28,738 - INFO - Starting to retrieve PPH data for customer ID 567297

===== in get_PM_related_persons_l2 =====
RELATED_PERSON_RELATION --- RELATED_PERSON_ROLE
309 20
Connection closed.
phase 1
  CUSTOMER_ID CUSTOMER_TYPE GENDER    FIRST_NAME LAST_NAME  \
0      104371           PPH      M        MONCEF   SELLAMI
1      567297           PPH      M  MOHAMED HEDI     ABBES

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1938-05-27T00:00:00          TN            CIN  00455380             TN
1  1982-07-10T00:00:00          TN            CIN  08328854             TN

   ... RESIDENCE ADDRESS_TYPE   ZIP  \
0  ...        TN            1  2036
1  ...        TN            1  1053

                                             ADDRESS COUNTRY_CODE  \
0  TN - ARIANA - SOUKRA - RUE IBN JAZZAR LA SOUKR...           TN
1  TN - TUNIS - LA MARSA - IMMEUBLE BARCELONA APP...           TN

                                        OCCUPATION  \
0       Dirigeants et gerants non classes ailleurs
1  Autres cadres de direction non classes ailleurs

  RELATED_PERSON_RELATION_CODE_ATB RELATED_PERSON_ROLE_CODE_ATB  \
0                              305                           40
1                              307                           10

                                  ROLE_ENTITY ROLE_ACCOUNT
0  CUSTOMER_ID : 104371 N.A - ROLE_CODE_goAML         MAND
1  CUSTOMER_ID : 567297 N.A - ROLE_CODE_goAML         MAND

[2 rows x 23 columns]
Connection established successfully.
Connection closed.
************ filtered_df_mandates_processed ****************
          MANDATE_ID SIGNATORY_GROUP CUSTOMER_ID START_DATE   END_DATE
0  136815.20221130-1        136815.1      567297 2024-07-11 2122-11-01
1  136815.20221130-1        136815.1      729941 2024-07-19 2122-11-01

2025-04-14 10:23:28,855 - INFO - Successfully executed query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '567297'

2025-04-14 10:23:28,858 - INFO - Successfully converted query result to DataFrame for query:
            -- T24 - CUSTOMERS - PPH
            SELECT
                L_NATURE_CLIENT AS CUSTOMER_TYPE,
                --CUSTOMER_NO AS CUSTOMER_ID,
                CUSTOMER_CODE AS CUSTOMER_ID,
                CASE
                    WHEN GENDER IS NULL OR GENDER = '' THEN 'M'
                    WHEN GENDER = 'MALE' THEN 'M'
                    WHEN GENDER = 'FEMALE' THEN 'F'
                END AS GENDER,
                GIVEN_NAMES AS FIRST_NAME,
                FAMILY_NAME AS LAST_NAME,
                CASE
                        WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))) = 1 THEN CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, DATE_OF_BIRTH))), 23) + 'T00:00:00'
                        ELSE '0000-00-00T00:00:00'
                    END AS BIRTHDATE,
                CASE
				    WHEN COALESCE(COUNTRY, '') = '' AND COALESCE(CUST_BIRTH_COUNTRY, '') = '' AND COALESCE(L_PLACE_OF_BIRT, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				        NULLIF(COUNTRY, ''),
				        NULLIF(CUST_BIRTH_COUNTRY, ''),
				        NULLIF(L_PLACE_OF_BIRT, '')
				    )
				END AS BIRTH_PLACE,
                LEGAL_DOC_NAME,
                LEGAL_ID, --Numéro de la carte d’identité nationale CIN / Numéro passeport
                LEGAL_ISS_AUTH, --Pays d'émission du passeport
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_ISS_DATE, 112), 120) + 'T00:00:00' AS LEGAL_ISS_DATE,
                CONVERT(NVARCHAR, CONVERT(DATE, LEGAL_EXP_DATE, 112), 120) + 'T00:00:00' AS LEGAL_EXP_DATE,
                NATIONALITY,
                RESIDENCE,
                '1' AS ADDRESS_TYPE,
                COALESCE(NULLIF(POST_CODE, ''), 'N.A') AS ZIP,
                CASE
				    WHEN COALESCE(COUNTRY, '') = ''
				         AND COALESCE(TOWN_COUNTRY, '') = ''
				         AND COALESCE(ADDRESS_ITEM1, '') = ''
				         AND COALESCE(ADDRESS_ITEM2, '') = ''
				         AND COALESCE(STREET, '') = ''
				         AND COALESCE(ADDRESS, '') = ''
				        THEN 'N.A'
				    ELSE CONCAT_WS(' - ',
				         NULLIF(COUNTRY, ''),
				         NULLIF(TOWN_COUNTRY, ''),
				         NULLIF(ADDRESS_ITEM1, ''),
				         NULLIF(ADDRESS_ITEM2, ''),
				         NULLIF(STREET, ''),
				         NULLIF(ADDRESS, ''))
				END AS ADDRESS,
                COALESCE(NULLIF(COUNTRY, ''), 'N.A') AS COUNTRY_CODE,
                COALESCE(NULLIF(T24_OCCUPATION.LIBELLE, ''), 'N.A') AS OCCUPATION
                --'TICPT' AS ROLE_ACCOUNT
            --FROM [MISDW].[TRG].[T24_FBNK_CUSTOMER]
            FROM [MISDW].[GO_AML].[T24_CUSTOMER_DECOMPOSED_LEGAL_DETAILS]
            LEFT JOIN [MISDW].[GO_AML].[T24_OCCUPATION] AS T24_OCCUPATION ON RIGHT('0000' + T24_OCCUPATION.CODE, 4) = RIGHT('0000' + OCCUPATION, 4)
            WHERE
                CUSTOMER_CODE = '567297'

2025-04-14 10:23:28,861 - INFO - Retrieved PPH data successfully for customer ID 567297

Connection established successfully.
Connection closed.
phase 2
  CUSTOMER_TYPE CUSTOMER_ID GENDER    FIRST_NAME LAST_NAME  \
0           PPH      567297      M  MOHAMED HEDI     ABBES

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1982-07-10T00:00:00          TN            CIN  08328854             TN

   ... LEGAL_EXP_DATE NATIONALITY RESIDENCE ADDRESS_TYPE   ZIP  \
0  ...           None          TN        TN            1  1053

                                             ADDRESS COUNTRY_CODE  \
0  TN - TUNIS - LA MARSA - IMMEUBLE BARCELONA APP...           TN

                                        OCCUPATION  \
0  Autres cadres de direction non classes ailleurs

  RELATED_PERSON_ROLE_CODE_ATB ROLE_ENTITY
0                   SIGNATAIRE          RL

[1 rows x 21 columns]
phase 3
df_related_third_party_signatory_g.columns
Index(['CUSTOMER_TYPE', 'CUSTOMER_ID', 'GENDER', 'FIRST_NAME', 'LAST_NAME',
       'BIRTHDATE', 'BIRTH_PLACE', 'LEGAL_DOC_NAME', 'LEGAL_ID',
       'LEGAL_ISS_AUTH', 'LEGAL_ISS_DATE', 'LEGAL_EXP_DATE', 'NATIONALITY',
       'RESIDENCE', 'ADDRESS_TYPE', 'ZIP', 'ADDRESS', 'COUNTRY_CODE',
       'OCCUPATION', 'RELATED_PERSON_ROLE_CODE_ATB', 'ROLE_ENTITY'],
      dtype='object')
df_pm_related_persons_details.columns
Index(['CUSTOMER_ID', 'CUSTOMER_TYPE', 'GENDER', 'FIRST_NAME', 'LAST_NAME',
       'BIRTHDATE', 'BIRTH_PLACE', 'LEGAL_DOC_NAME', 'LEGAL_ID',
       'LEGAL_ISS_AUTH', 'LEGAL_ISS_DATE', 'LEGAL_EXP_DATE', 'NATIONALITY',
       'RESIDENCE', 'ADDRESS_TYPE', 'ZIP', 'ADDRESS', 'COUNTRY_CODE',
       'OCCUPATION', 'RELATED_PERSON_RELATION_CODE_ATB',
       'RELATED_PERSON_ROLE_CODE_ATB', 'ROLE_ENTITY', 'ROLE_ACCOUNT'],
      dtype='object')
phase 4 - concat
df_pm_related_persons_details.columns
Index(['CUSTOMER_ID', 'CUSTOMER_TYPE', 'GENDER', 'FIRST_NAME', 'LAST_NAME',
       'BIRTHDATE', 'BIRTH_PLACE', 'LEGAL_DOC_NAME', 'LEGAL_ID',
       'LEGAL_ISS_AUTH', 'LEGAL_ISS_DATE', 'LEGAL_EXP_DATE', 'NATIONALITY',
       'RESIDENCE', 'ADDRESS_TYPE', 'ZIP', 'ADDRESS', 'COUNTRY_CODE',
       'OCCUPATION', 'RELATED_PERSON_RELATION_CODE_ATB',
       'RELATED_PERSON_ROLE_CODE_ATB', 'ROLE_ENTITY', 'ROLE_ACCOUNT'],
      dtype='object')
  CUSTOMER_ID CUSTOMER_TYPE GENDER    FIRST_NAME LAST_NAME  \
0      104371           PPH      M        MONCEF   SELLAMI
1      567297           PPH      M  MOHAMED HEDI     ABBES
2      567297           PPH      M  MOHAMED HEDI     ABBES

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1938-05-27T00:00:00          TN            CIN  00455380             TN
1  1982-07-10T00:00:00          TN            CIN  08328854             TN
2  1982-07-10T00:00:00          TN            CIN  08328854             TN

   ... RESIDENCE ADDRESS_TYPE   ZIP  \
0  ...        TN            1  2036
1  ...        TN            1  1053
2  ...        TN            1  1053

                                             ADDRESS COUNTRY_CODE  \
0  TN - ARIANA - SOUKRA - RUE IBN JAZZAR LA SOUKR...           TN
1  TN - TUNIS - LA MARSA - IMMEUBLE BARCELONA APP...           TN
2  TN - TUNIS - LA MARSA - IMMEUBLE BARCELONA APP...           TN

                                        OCCUPATION  \
0       Dirigeants et gerants non classes ailleurs
1  Autres cadres de direction non classes ailleurs
2  Autres cadres de direction non classes ailleurs

  RELATED_PERSON_RELATION_CODE_ATB RELATED_PERSON_ROLE_CODE_ATB  \
0                              305                           40
1                              307                           10
2                              NaN                   SIGNATAIRE

                                  ROLE_ENTITY ROLE_ACCOUNT
0  CUSTOMER_ID : 104371 N.A - ROLE_CODE_goAML         MAND
1  CUSTOMER_ID : 567297 N.A - ROLE_CODE_goAML         MAND
2                                          RL          NaN

[3 rows x 23 columns]
********************************
BEFORE - df_pm_related_persons_details
(3, 23)
  CUSTOMER_ID CUSTOMER_TYPE GENDER    FIRST_NAME LAST_NAME  \
0      104371           PPH      M        MONCEF   SELLAMI
1      567297           PPH      M  MOHAMED HEDI     ABBES
2      567297           PPH      M  MOHAMED HEDI     ABBES

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1938-05-27T00:00:00          TN            CIN  00455380             TN
1  1982-07-10T00:00:00          TN            CIN  08328854             TN
2  1982-07-10T00:00:00          TN            CIN  08328854             TN

   ... RESIDENCE ADDRESS_TYPE   ZIP  \
0  ...        TN            1  2036
1  ...        TN            1  1053
2  ...        TN            1  1053

                                             ADDRESS COUNTRY_CODE  \
0  TN - ARIANA - SOUKRA - RUE IBN JAZZAR LA SOUKR...           TN
1  TN - TUNIS - LA MARSA - IMMEUBLE BARCELONA APP...           TN
2  TN - TUNIS - LA MARSA - IMMEUBLE BARCELONA APP...           TN

                                        OCCUPATION  \
0       Dirigeants et gerants non classes ailleurs
1  Autres cadres de direction non classes ailleurs
2  Autres cadres de direction non classes ailleurs

  RELATED_PERSON_RELATION_CODE_ATB RELATED_PERSON_ROLE_CODE_ATB  \
0                              305                           40
1                              307                           10
2                              NaN                   SIGNATAIRE

                                  ROLE_ENTITY ROLE_ACCOUNT
0  CUSTOMER_ID : 104371 N.A - ROLE_CODE_goAML         MAND
1  CUSTOMER_ID : 567297 N.A - ROLE_CODE_goAML         MAND
2                                          RL          NaN

[3 rows x 23 columns]
********************************
======= fct aggregate_legal_id_section ===========
  CUSTOMER_ID CUSTOMER_TYPE GENDER    FIRST_NAME LAST_NAME  \
0      104371           PPH      M        MONCEF   SELLAMI
1      567297           PPH      M  MOHAMED HEDI     ABBES
2      567297           PPH      M  MOHAMED HEDI     ABBES

             BIRTHDATE BIRTH_PLACE LEGAL_DOC_NAME  LEGAL_ID LEGAL_ISS_AUTH  \
0  1938-05-27T00:00:00          TN            CIN  00455380             TN
1  1982-07-10T00:00:00          TN            CIN  08328854             TN
2  1982-07-10T00:00:00          TN            CIN  08328854             TN

   ... RESIDENCE ADDRESS_TYPE   ZIP  \
0  ...        TN            1  2036
1  ...        TN            1  1053
2  ...        TN            1  1053

                                             ADDRESS COUNTRY_CODE  \
0  TN - ARIANA - SOUKRA - RUE IBN JAZZAR LA SOUKR...           TN
1  TN - TUNIS - LA MARSA - IMMEUBLE BARCELONA APP...           TN
2  TN - TUNIS - LA MARSA - IMMEUBLE BARCELONA APP...           TN

                                        OCCUPATION  \
0       Dirigeants et gerants non classes ailleurs
1  Autres cadres de direction non classes ailleurs
2  Autres cadres de direction non classes ailleurs

  RELATED_PERSON_RELATION_CODE_ATB RELATED_PERSON_ROLE_CODE_ATB  \
0                              305                           40
1                              307                           10
2                              NaN                   SIGNATAIRE

                                  ROLE_ENTITY ROLE_ACCOUNT
0  CUSTOMER_ID : 104371 N.A - ROLE_CODE_goAML         MAND
1  CUSTOMER_ID : 567297 N.A - ROLE_CODE_goAML         MAND
2                                          RL          NaN

[3 rows x 23 columns]
==================
********************************
AFTER - df_pm_related_persons_details
(3, 19)
  CUSTOMER_ID CUSTOMER_TYPE GENDER    FIRST_NAME LAST_NAME  \
0      104371           PPH      M        MONCEF   SELLAMI
1      567297           PPH      M  MOHAMED HEDI     ABBES
2      567297           PPH      M  MOHAMED HEDI     ABBES

             BIRTHDATE BIRTH_PLACE NATIONALITY RESIDENCE ADDRESS_TYPE   ZIP  \
0  1938-05-27T00:00:00          TN          TN        TN            1  2036
1  1982-07-10T00:00:00          TN          TN        TN            1  1053
2  1982-07-10T00:00:00          TN          TN        TN            1  1053

                                             ADDRESS COUNTRY_CODE  \
0  TN - ARIANA - SOUKRA - RUE IBN JAZZAR LA SOUKR...           TN
1  TN - TUNIS - LA MARSA - IMMEUBLE BARCELONA APP...           TN
2  TN - TUNIS - LA MARSA - IMMEUBLE BARCELONA APP...           TN

                                        OCCUPATION  \
0       Dirigeants et gerants non classes ailleurs
1  Autres cadres de direction non classes ailleurs
2  Autres cadres de direction non classes ailleurs

  RELATED_PERSON_RELATION_CODE_ATB RELATED_PERSON_ROLE_CODE_ATB  \
0                              305                           40
1                              307                           10
2                              N.A                   SIGNATAIRE

                                  ROLE_ENTITY ROLE_ACCOUNT  \
0  CUSTOMER_ID : 104371 N.A - ROLE_CODE_goAML         MAND
1  CUSTOMER_ID : 567297 N.A - ROLE_CODE_goAML         MAND
2                                          RL         MAND

                          IDENTIFICATIONS_ID_SECTION
0  <identification><type>B</type><number>00455380...
1  <identification><type>B</type><number>08328854...
2  <identification><type>B</type><number>08328854...
********************************
+++++++++++++++

In [13]:
account = {
    'account_number': account_number,
    'account_correspondences': account_correspondences,
    'account_detail': account_details,
    'customer_id': customer_id,
    'account_type': account_type,
    'account_rp': account_rp
}

In [4]:
from src.controller.transaction_router import TransactionRouter

In [5]:
transaction_router = TransactionRouter(TREANSACTION_CODE, DB_CONFIG)

2025-04-14 10:22:27,498 - INFO - Transaction codes loaded successfully.
2025-04-14 10:22:27,506 - INFO - EQAccountant initialized with logging enabled: True

Index(['APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB', 'TRANSACTION_DESC_ATB',
       'APP_SOURCE', 'OP_TYPE', 'Categorie_de_transaction',
       'TRANSACTION_CODE_GOAML', 'TRANSACTION_DESC_GOAML', 'FUND_CODE_1',
       'FUND_CODE_2', '_merge'],
      dtype='object')

In [14]:
year = '2024'
transaction_router.clear_cash()
transaction_router.get_transactions(account, year)

2025-04-14 10:23:37,750 - INFO - Starting to retrieve accountant's transactions for account: 5820136815521, year: 2024

Connection established successfully.

2025-04-14 10:24:02,877 - INFO - Successfully executed query:
            SELECT
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5820136815521'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2024'

2025-04-14 10:26:44,632 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5820136815521'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2024'

2025-04-14 10:26:44,636 - INFO - Query executed successfully. Accountant's transactions retrieved for the account.
2025-04-14 10:26:44,637 - INFO - Closing database connection.
2025-04-14 10:26:44,674 - INFO - Returning cleaned DataFrame.
2025-04-14 10:26:44,698 - INFO - Starting transfert's transactions retrieval for account: 5820136815521, year: 2024
2025-04-14 10:26:44,704 - INFO - Executing query with max_attempts: 3

Connection closed.
============*********==============
Index(['T24_ACCOUNT', 'EQ_ACCOUNT', 'ORACLE_ACCOUNT', 'TRANSACTION_REF',
       'TRANSACTION_SEQ', 'TRANSACTION_DATE', 'TRANSACTION_DATE_TS',
       'TRANSACTION_CURRENCY', 'TRANSACTION_AMOUNT', 'TRANSACTION_CODE_ATB',
       'TRANSACTION_DESC_ATB_ACC', 'APP_SOURCE_CODE', 'TRANSACTION_DESC_ATB_F',
       'APP_SOURCE', 'OP_TYPE', 'Categorie_de_transaction',
       'TRANSACTION_DESC_GOAML', 'TRANSACTION_CODE_GOAML', 'FUND_CODE_1',
       'FUND_CODE_2'],
      dtype='object')
Connection established successfully.

2025-04-14 10:26:45,513 - INFO - Successfully executed query:
            -- Transfert - Emis/Recus
            -- Transfert - Emis
            SELECT
                'Y' AS PART_1_IS_MY_CLIENT,
                'I' AS PART_1_ROLE,
                BRN_ACC AS PART_1_BR,
                ACCOUNT_ID AS PART_1_BN,
                SFX_ACC AS PART_1_SFX,
                BRN_ACC + ACCOUNT_ID + SFX_ACC AS EQ_ACCOUNT,
                TRANSACTION_NUMBER AS TRANSACTION_REF,
                TRANSACTION_DATE,

                'A' AS FUND_CODE_1,
                F_CCY_CODE AS CURRENCY_CODE_1,
                'TN' AS COUNTRY_1,
                FOREIGN_AMNT_CCY AS FOREIGN_AMOUNT_1,

                'N' AS PART_2_IS_MY_CLIENT,
                '' AS PART_2_TYPE,
                'B' AS PART_2_ROLE,
                '' AS PART_2_ACCOUNT,
                '<IB_account>' +
                    '<institution_name>' +
                    CASE
                        WHEN TRIM(ISNULL(R_SWIFT_ID, '')) = '' THEN 'NA'
                        ELSE R_SWIFT_ID
                    END +
                    '</institution_name>' +
                    '<swift>' +
                    CASE
                        WHEN TRIM(ISNULL(BENF_SWIFT_BANk_ID, '')) = '' THEN 'NA'
                        WHEN LEN(BENF_SWIFT_BANk_ID) > 11 THEN 'NA'
                        ELSE BENF_SWIFT_BANk_ID
                    END +
                    '</swift>' +
                    '<institution_country>' +
                    CASE
                        WHEN TRIM(ISNULL(R_SWIFT_COUNTRY_CoDE, '')) = '' THEN 'NA'
                        ELSE R_SWIFT_COUNTRY_CoDE
                    END +
                    '</institution_country>' +
                    '<account>' +
                    CASE
                        WHEN TRIM(ISNULL(ORDERING_CUST_ACC, '')) = '' THEN 'NA' -- RIB
                        ELSE ORDERING_CUST_ACC
                    END +
                    '</account>' +
                '</IB_account>' AS PART_2_DETAILS,

                'A' AS FUND_CODE_2,
                L_CCY_CODE AS CURRENCY_CODE_2,
                CASE
                    WHEN TRIM(ISNULL(R_SWIFT_COUNTRY_CoDE, '')) = '' THEN 'NA'
                    ELSE R_SWIFT_COUNTRY_CoDE
                END AS COUNTRY_2,
                LOCAL_AMNT_CCY AS FOREIGN_AMOUNT_2,


                'TN' AS TRANSACTION_LOCATION,
                CASE
                    WHEN TRANSACTION_DATE = 0 OR TRY_CONVERT(INT, TRANSACTION_DATE) IS NULL THEN
                        '30/0000/00 00 0000'  -- Default value for invalid or zero TRANSACTION_DATE
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)) = 1 THEN
                        '30/' + TRANSACTION_NUMBER + '/' +
                        RIGHT('0' + CONVERT(VARCHAR(2), DAY(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23))), 2) + ' ' +
                        RIGHT('0' + CONVERT(VARCHAR(2), MONTH(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23))), 2) + ' ' +
                        CONVERT(VARCHAR(4), YEAR(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23)))
                    ELSE
                        NULL  -- or any other default value/message you want to return
                END AS TRANSACTION_NUMBER,
                CASE
                    WHEN TRANSACTION_DATE = 0 THEN '0000-00-00T00:00:00'
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)) = 1 THEN
                        CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23) + 'T00:00:00'
                    ELSE NULL  -- or any other default value/message you want to return
                END AS DATE_TRANSACTION,
                TRANS_CODE_DESC AS TRANS_CODE_DESC_ATB,
                TRANS_CODE AS TRANSMODE_CODE_ATB,
                'B397' AS TRANSACTION_CODE_GOAML,
                FOREIGN_AMNT_CCY AS AMOUNT_LOCAL,
                CASE
                    WHEN TRANSACTION_STATUS = 'A' THEN 'C'
                    ELSE '-'
                END AS TRANSACTION_STATUS_CODE,

                'TRF_EMIS' AS SOURCE

            FROM
                [MISDW].[GO_AML].[EQA_CP_TRF_EMIS]
            -- Filter by year, handling zero or invalid TRANSACTION_DATE values
            WHERE
                CASE
                    WHEN TRANSACTION_DATE = 0 OR TRY_CONVERT(INT, TRANSACTION_DATE) IS NULL THEN
                        0  -- or any placeholder value to indicate an invalid date
                    ELSE
                        YEAR(CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)))
                END = '2024' AND
                BRN_ACC = '5820' AND
                ACCOUNT_ID = '136815' AND
                SFX_ACC = '521'



            UNION


            -- Transfert - Recus
            SELECT
                'Y' AS PART_1_IS_MY_CLIENT,
                'B' AS PART_1_ROLE,
                BRN_ACC AS PART_1_BR,
                ACCOUNT_ID AS PART_1_BN,
                SFX_ACC AS PART_1_SFX,
                BRN_ACC + ACCOUNT_ID + SFX_ACC AS EQ_ACCOUNT,
                TRANSACTION_NUMBER AS TRANSACTION_REF,
                TRANSACTION_DATE,

                'A' AS FUND_CODE_1,
                F_CCY_CODE AS CURRENCY_CODE_1,
                'TN' AS COUNTRY_1,
                FOREIGN_AMNT_CCY AS FOREIGN_AMOUNT_1,

                'N' AS PART_2_IS_MY_CLIENT,
                '' AS PART_2_TYPE,
                'I' AS PART_2_ROLE,
                '' AS PART_2_ACCOUNT,
                '<IB_account>' +
                    '<institution_name>' +
                    CASE
                        WHEN TRIM(ISNULL(R_SWIFT_ID, '')) = '' THEN 'NA'
                        ELSE R_SWIFT_ID
                    END +
                    '</institution_name>' +
                    '<swift>' +
                    CASE
                        WHEN TRIM(ISNULL(BENF_SWIFT_BANk_ID, '')) = '' THEN 'NA'
                        WHEN LEN(BENF_SWIFT_BANk_ID) > 11 THEN 'NA'
                        ELSE BENF_SWIFT_BANk_ID
                    END +
                    '</swift>' +
                    '<institution_country>' +
                    CASE
                        WHEN TRIM(ISNULL(R_SWIFT_COUNTRY_CoDE, '')) = '' THEN 'NA'
                        ELSE R_SWIFT_COUNTRY_CoDE
                    END +
                    '</institution_country>' +
                    '<account>' +
                    CASE
                        WHEN TRIM(ISNULL(ORDERING_CUST_ACC, '')) = '' THEN 'NA' -- RIB
                        ELSE ORDERING_CUST_ACC
                    END +
                    '</account>' +
                '</IB_account>' AS PART_2_DETAILS,

                'A' AS FUND_CODE_2,
                L_CCY_CODE AS CURRENCY_CODE_2,
                CASE
                    WHEN TRIM(ISNULL(R_SWIFT_COUNTRY_CoDE, '')) = '' THEN 'NA'
                    ELSE R_SWIFT_COUNTRY_CoDE
                END AS COUNTRY_2,
                LOCAL_AMNT_CCY AS FOREIGN_AMOUNT_2,


                'TN' AS TRANSACTION_LOCATION,
                CASE
                    WHEN TRANSACTION_DATE = 0 OR TRY_CONVERT(INT, TRANSACTION_DATE) IS NULL THEN
                        '30/0000/00 00 0000'  -- Default value for invalid or zero TRANSACTION_DATE
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)) = 1 THEN
                        '30/' + TRANSACTION_NUMBER + '/' +
                        RIGHT('0' + CONVERT(VARCHAR(2), DAY(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23))), 2) + ' ' +
                        RIGHT('0' + CONVERT(VARCHAR(2), MONTH(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23))), 2) + ' ' +
                        CONVERT(VARCHAR(4), YEAR(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23)))
                    ELSE
                        NULL  -- or any other default value/message you want to return
                END AS TRANSACTION_NUMBER,
                CASE
                    WHEN TRANSACTION_DATE = 0 THEN '0000-00-00T00:00:00'
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)) = 1 THEN
                        CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23) + 'T00:00:00'
                    ELSE NULL  -- or any other default value/message you want to return
                END AS DATE_TRANSACTION,
                TRANS_CODE_DESC AS TRANS_CODE_DESC_ATB,
                TRANS_CODE AS TRANSMODE_CODE_ATB,
                'B397' AS TRANSACTION_CODE_GOAML,
                FOREIGN_AMNT_CCY AS AMOUNT_LOCAL,
                CASE
                    WHEN TRANSACTION_STATUS = 'A' THEN 'C'
                    ELSE '-'
                END AS TRANSACTION_STATUS_CODE,

                'TRF_RECUS' AS SOURCE

            FROM
                [MISDW].[GO_AML].[EQA_CP_TRF_RECUS]
            -- Filter by year, handling zero or invalid TRANSACTION_DATE values
            WHERE
                CASE
                    WHEN TRANSACTION_DATE = 0 OR TRY_CONVERT(INT, TRANSACTION_DATE) IS NULL THEN
                        0  -- or any placeholder value to indicate an invalid date
                    ELSE
                        YEAR(CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)))
                END = '2024' AND
                BRN_ACC = '5820' AND
                ACCOUNT_ID = '136815' AND
                SFX_ACC = '521'

2025-04-14 10:26:45,567 - INFO - Successfully converted query result to DataFrame for query:
            -- Transfert - Emis/Recus
            -- Transfert - Emis
            SELECT
                'Y' AS PART_1_IS_MY_CLIENT,
                'I' AS PART_1_ROLE,
                BRN_ACC AS PART_1_BR,
                ACCOUNT_ID AS PART_1_BN,
                SFX_ACC AS PART_1_SFX,
                BRN_ACC + ACCOUNT_ID + SFX_ACC AS EQ_ACCOUNT,
                TRANSACTION_NUMBER AS TRANSACTION_REF,
                TRANSACTION_DATE,

                'A' AS FUND_CODE_1,
                F_CCY_CODE AS CURRENCY_CODE_1,
                'TN' AS COUNTRY_1,
                FOREIGN_AMNT_CCY AS FOREIGN_AMOUNT_1,

                'N' AS PART_2_IS_MY_CLIENT,
                '' AS PART_2_TYPE,
                'B' AS PART_2_ROLE,
                '' AS PART_2_ACCOUNT,
                '<IB_account>' +
                    '<institution_name>' +
                    CASE
                        WHEN TRIM(ISNULL(R_SWIFT_ID, '')) = '' THEN 'NA'
                        ELSE R_SWIFT_ID
                    END +
                    '</institution_name>' +
                    '<swift>' +
                    CASE
                        WHEN TRIM(ISNULL(BENF_SWIFT_BANk_ID, '')) = '' THEN 'NA'
                        WHEN LEN(BENF_SWIFT_BANk_ID) > 11 THEN 'NA'
                        ELSE BENF_SWIFT_BANk_ID
                    END +
                    '</swift>' +
                    '<institution_country>' +
                    CASE
                        WHEN TRIM(ISNULL(R_SWIFT_COUNTRY_CoDE, '')) = '' THEN 'NA'
                        ELSE R_SWIFT_COUNTRY_CoDE
                    END +
                    '</institution_country>' +
                    '<account>' +
                    CASE
                        WHEN TRIM(ISNULL(ORDERING_CUST_ACC, '')) = '' THEN 'NA' -- RIB
                        ELSE ORDERING_CUST_ACC
                    END +
                    '</account>' +
                '</IB_account>' AS PART_2_DETAILS,

                'A' AS FUND_CODE_2,
                L_CCY_CODE AS CURRENCY_CODE_2,
                CASE
                    WHEN TRIM(ISNULL(R_SWIFT_COUNTRY_CoDE, '')) = '' THEN 'NA'
                    ELSE R_SWIFT_COUNTRY_CoDE
                END AS COUNTRY_2,
                LOCAL_AMNT_CCY AS FOREIGN_AMOUNT_2,


                'TN' AS TRANSACTION_LOCATION,
                CASE
                    WHEN TRANSACTION_DATE = 0 OR TRY_CONVERT(INT, TRANSACTION_DATE) IS NULL THEN
                        '30/0000/00 00 0000'  -- Default value for invalid or zero TRANSACTION_DATE
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)) = 1 THEN
                        '30/' + TRANSACTION_NUMBER + '/' +
                        RIGHT('0' + CONVERT(VARCHAR(2), DAY(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23))), 2) + ' ' +
                        RIGHT('0' + CONVERT(VARCHAR(2), MONTH(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23))), 2) + ' ' +
                        CONVERT(VARCHAR(4), YEAR(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23)))
                    ELSE
                        NULL  -- or any other default value/message you want to return
                END AS TRANSACTION_NUMBER,
                CASE
                    WHEN TRANSACTION_DATE = 0 THEN '0000-00-00T00:00:00'
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)) = 1 THEN
                        CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23) + 'T00:00:00'
                    ELSE NULL  -- or any other default value/message you want to return
                END AS DATE_TRANSACTION,
                TRANS_CODE_DESC AS TRANS_CODE_DESC_ATB,
                TRANS_CODE AS TRANSMODE_CODE_ATB,
                'B397' AS TRANSACTION_CODE_GOAML,
                FOREIGN_AMNT_CCY AS AMOUNT_LOCAL,
                CASE
                    WHEN TRANSACTION_STATUS = 'A' THEN 'C'
                    ELSE '-'
                END AS TRANSACTION_STATUS_CODE,

                'TRF_EMIS' AS SOURCE

            FROM
                [MISDW].[GO_AML].[EQA_CP_TRF_EMIS]
            -- Filter by year, handling zero or invalid TRANSACTION_DATE values
            WHERE
                CASE
                    WHEN TRANSACTION_DATE = 0 OR TRY_CONVERT(INT, TRANSACTION_DATE) IS NULL THEN
                        0  -- or any placeholder value to indicate an invalid date
                    ELSE
                        YEAR(CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)))
                END = '2024' AND
                BRN_ACC = '5820' AND
                ACCOUNT_ID = '136815' AND
                SFX_ACC = '521'



            UNION


            -- Transfert - Recus
            SELECT
                'Y' AS PART_1_IS_MY_CLIENT,
                'B' AS PART_1_ROLE,
                BRN_ACC AS PART_1_BR,
                ACCOUNT_ID AS PART_1_BN,
                SFX_ACC AS PART_1_SFX,
                BRN_ACC + ACCOUNT_ID + SFX_ACC AS EQ_ACCOUNT,
                TRANSACTION_NUMBER AS TRANSACTION_REF,
                TRANSACTION_DATE,

                'A' AS FUND_CODE_1,
                F_CCY_CODE AS CURRENCY_CODE_1,
                'TN' AS COUNTRY_1,
                FOREIGN_AMNT_CCY AS FOREIGN_AMOUNT_1,

                'N' AS PART_2_IS_MY_CLIENT,
                '' AS PART_2_TYPE,
                'I' AS PART_2_ROLE,
                '' AS PART_2_ACCOUNT,
                '<IB_account>' +
                    '<institution_name>' +
                    CASE
                        WHEN TRIM(ISNULL(R_SWIFT_ID, '')) = '' THEN 'NA'
                        ELSE R_SWIFT_ID
                    END +
                    '</institution_name>' +
                    '<swift>' +
                    CASE
                        WHEN TRIM(ISNULL(BENF_SWIFT_BANk_ID, '')) = '' THEN 'NA'
                        WHEN LEN(BENF_SWIFT_BANk_ID) > 11 THEN 'NA'
                        ELSE BENF_SWIFT_BANk_ID
                    END +
                    '</swift>' +
                    '<institution_country>' +
                    CASE
                        WHEN TRIM(ISNULL(R_SWIFT_COUNTRY_CoDE, '')) = '' THEN 'NA'
                        ELSE R_SWIFT_COUNTRY_CoDE
                    END +
                    '</institution_country>' +
                    '<account>' +
                    CASE
                        WHEN TRIM(ISNULL(ORDERING_CUST_ACC, '')) = '' THEN 'NA' -- RIB
                        ELSE ORDERING_CUST_ACC
                    END +
                    '</account>' +
                '</IB_account>' AS PART_2_DETAILS,

                'A' AS FUND_CODE_2,
                L_CCY_CODE AS CURRENCY_CODE_2,
                CASE
                    WHEN TRIM(ISNULL(R_SWIFT_COUNTRY_CoDE, '')) = '' THEN 'NA'
                    ELSE R_SWIFT_COUNTRY_CoDE
                END AS COUNTRY_2,
                LOCAL_AMNT_CCY AS FOREIGN_AMOUNT_2,


                'TN' AS TRANSACTION_LOCATION,
                CASE
                    WHEN TRANSACTION_DATE = 0 OR TRY_CONVERT(INT, TRANSACTION_DATE) IS NULL THEN
                        '30/0000/00 00 0000'  -- Default value for invalid or zero TRANSACTION_DATE
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)) = 1 THEN
                        '30/' + TRANSACTION_NUMBER + '/' +
                        RIGHT('0' + CONVERT(VARCHAR(2), DAY(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23))), 2) + ' ' +
                        RIGHT('0' + CONVERT(VARCHAR(2), MONTH(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23))), 2) + ' ' +
                        CONVERT(VARCHAR(4), YEAR(CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23)))
                    ELSE
                        NULL  -- or any other default value/message you want to return
                END AS TRANSACTION_NUMBER,
                CASE
                    WHEN TRANSACTION_DATE = 0 THEN '0000-00-00T00:00:00'
                    WHEN ISDATE(CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)) = 1 THEN
                        CONVERT(VARCHAR, CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)), 23) + 'T00:00:00'
                    ELSE NULL  -- or any other default value/message you want to return
                END AS DATE_TRANSACTION,
                TRANS_CODE_DESC AS TRANS_CODE_DESC_ATB,
                TRANS_CODE AS TRANSMODE_CODE_ATB,
                'B397' AS TRANSACTION_CODE_GOAML,
                FOREIGN_AMNT_CCY AS AMOUNT_LOCAL,
                CASE
                    WHEN TRANSACTION_STATUS = 'A' THEN 'C'
                    ELSE '-'
                END AS TRANSACTION_STATUS_CODE,

                'TRF_RECUS' AS SOURCE

            FROM
                [MISDW].[GO_AML].[EQA_CP_TRF_RECUS]
            -- Filter by year, handling zero or invalid TRANSACTION_DATE values
            WHERE
                CASE
                    WHEN TRANSACTION_DATE = 0 OR TRY_CONVERT(INT, TRANSACTION_DATE) IS NULL THEN
                        0  -- or any placeholder value to indicate an invalid date
                    ELSE
                        YEAR(CONVERT(DATE, CONVERT(VARCHAR, TRY_CONVERT(INT, TRANSACTION_DATE) + 19000000)))
                END = '2024' AND
                BRN_ACC = '5820' AND
                ACCOUNT_ID = '136815' AND
                SFX_ACC = '521'

2025-04-14 10:26:45,575 - INFO - Query executed successfully; transfert's transactions data retrieved for the account.
2025-04-14 10:26:45,576 - INFO - Closing database connection.
2025-04-14 10:26:45,589 - INFO - Returning cleaned DataFrame.

Connection closed.
process_transactions

100%|██████████| 339/339 [00:00<00:00, 2930.52it/s]

--------- 1 ------------
---------------------
Index(['T24_ACCOUNT', 'EQ_ACCOUNT', 'ORACLE_ACCOUNT', 'OP_TYPE', 'APP_SOURCE',
       'APP_SOURCE_CODE', 'TRANSACTION_REF', 'TRANSACTION_SEQ',
       'TRANSACTION_DATE', 'TRANSACTION_CODE_ATB', 'TRANSACTION_DESC_ATB_ACC',
       'Categorie_de_transaction', 'TRANSACTION_AMOUNT', 'PART_1_IS_MY_CLIENT',
       'PART_1_ROLE', 'PART_1_BR', 'PART_1_BN', 'PART_1_SFX', 'FUND_CODE_1',
       'CURRENCY_CODE_1', 'COUNTRY_1', 'FOREIGN_AMOUNT_1',
       'PART_2_IS_MY_CLIENT', 'PART_2_TYPE', 'PART_2_ROLE', 'PART_2_ACCOUNT',
       'PART_2_DETAILS', 'FUND_CODE_2', 'CURRENCY_CODE_2', 'COUNTRY_2',
       'FOREIGN_AMOUNT_2', 'TRANSACTION_LOCATION', 'TRANSACTION_NUMBER',
       'DATE_TRANSACTION', 'TRANS_CODE_DESC_ATB', 'TRANSMODE_CODE_ATB',
       'TRANSACTION_CODE_GOAML', 'AMOUNT_LOCAL', 'TRANSACTION_STATUS_CODE',
       'SOURCE', '_merge'],
      dtype='object')
---------------------
---------------------
--------- 2 ------------
---------------------
RangeIndex(start=0, stop=0, step=1)
---------------------
---------------------

In [17]:
import pandas as pd

In [19]:
eq_accountant = transaction_router.eq_accountant.accountant_transactions.copy(deep=True)
eq_accountant.head(2)

,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE_CODE
123,2001369043,5820136815521,0201148049430,FIXTNSM30321386B,23,1240207,2024-02-07 21.17,EUR,-1.2100000000,219,INT retard IMP EFFET,@@CC
124,2001369043,5820136815521,0201148049430,FIXTNSM30321387B,27,1240207,2024-02-07 21.17,EUR,-0.4200000000,219,INT retard IMP EFFET,@@CC

In [21]:
transaction_code = transaction_router.transaction_code.copy(deep=True)
transaction_code.head(2)

,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,_merge
0,T24TL,297,Comm.OPPOS EFFET,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN,left_only
1,UAJL,920,Interets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [24]:
eq_accountant_w_trx_code = pd.merge(
    left=eq_accountant,
    right=transaction_code,
    left_on=['APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB'],
    right_on=['APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB'],
    how='left',
    suffixes=('_ACC', '_F') # accountant, param trx code file
).copy(deep=True)

In [28]:
eq_accountant_w_trx_code.T

,0,1,2,3,4,5,6,7,8,9,...,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173
T24_ACCOUNT,2001369043,2001369043,2001369043,2001369043,2001369043,2001369043,2001369043,2001369043,2001369043,2001369043,...,2001369043,2001369043,2001369043,2001369043,2001369043,2001369043,2001369043,2001369043,2001369043,2001369043
EQ_ACCOUNT,5820136815521,5820136815521,5820136815521,5820136815521,5820136815521,5820136815521,5820136815521,5820136815521,5820136815521,5820136815521,...,5820136815521,5820136815521,5820136815521,5820136815521,5820136815521,5820136815521,5820136815521,5820136815521,5820136815521,5820136815521
ORACLE_ACCOUNT,0201148049430,0201148049430,0201148049430,0201148049430,0201148049430,0201148049430,0201148049430,0201148049430,0201148049430,0201148049430,...,0201148049430,0201148049430,0201148049430,0201148049430,0201148049430,0201148049430,0201148049430,0201148049430,0201148049430,0201148049430
TRANSACTION_REF,FIXTNSM30321386B,FIXTNSM30321387B,FIXTNSM30321387B,FIXTNSM30321387B,FIXTNSM30321386C,FIXTNSM30321387C,FIXTNSM30321387C,FIXTNSM30321387C,FIXTNSM30321387C,FIXTNSM30321387C,...,221124,251224,TNSM40401H000446,TNSM40311H000169,TNSM40925H000315,TNSM41224H000353,VIREMENT DE,5820IML202300960,5820IML202300988,5820IML202301094
TRANSACTION_SEQ,23,27,29,13,5,9,11,1,5,9,...,1035,477,15,23,31,3,4,4,11,1
TRANSACTION_DATE,1240207,1240207,1240207,1240208,1240312,1240312,1240312,1240313,1240314,1240318,...,1241122,1241225,1240610,1240312,1240927,1241226,1241118,1240528,1240529,1240729
TRANSACTION_DATE_TS,2024-02-07 21.17,2024-02-07 21.17,2024-02-07 21.17,2024-02-08 20.02,2024-03-12 20.14,2024-03-12 20.14,2024-03-12 20.14,2024-03-13 20.23,2024-03-14 18.16,2024-03-18 20.25,...,None,None,2024-06-10 12.20,2024-03-12 14.39,None,None,None,2024-05-28 10.08,2024-05-29 12.22,None
TRANSACTION_CURRENCY,EUR,EUR,EUR,EUR,EUR,EUR,EUR,EUR,EUR,EUR,...,EUR,EUR,EUR,EUR,EUR,EUR,EUR,EUR,EUR,EUR
TRANSACTION_AMOUNT,-1.2100000000,-0.4200000000,-25.7900000000,-9.9800000000,-1.3800000000,-0.0700000000,-12.6800000000,-10.6100000000,-10.0700000000,-31.7300000000,...,-180000.0000000000,-70000.0000000000,-0.3000000000,-0.3000000000,-0.3000000000,-0.3000000000,169491.5200000000,-104348.8100000000,-87745.0000000000,-55341.4800000000
TRANSACTION_CODE_ATB,219,219,219,219,219,219,219,219,219,219,...,021,021,010,260,260,260,510,307,307,307
TRANSACTION_DESC_ATB_ACC,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,...,Virement Emis,Virement Emis,Debit,Commission,Commission,Commission,Credit,Paiement Lettre de Credit,Paiement Lettre de Credit,Paiement Lettre de Credit
APP_SOURCE_CODE,@@CC,@@CC,@@CC,@@CC,@@CC,@@CC,@@CC,@@CC,@@CC,@@CC,...,TLVIR,TLVIR,UDHD,UDHD,UDHD,UDHD,USRI,XM12,XM12,XM12
TRANSACTION_DESC_ATB_F,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,INT retard IMP EFFET,...,Virement Emis,Virement Emis,Debit,Commission,Commission,Commission,Credit,Paiement Lettre de Credit,Paiement Lettre de Credit,Paiement Lettre de Credit
APP_SOURCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,IBANK,IBANK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OP_TYPE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Virement,Virement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Categorie_de_transaction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TRANSACTION_CODE_GOAML,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B117,B117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TRANSACTION_DESC_GOAML,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Virement emis,Virement emis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FUND_CODE_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,A,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FUND_CODE_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,A,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
_merge,left_only,left_only,left_only,left_only,left_only,left_only,left_only,left_only,left_only,left_only,...,left_only,left_only,left_only,left_only,left_only,left_only,left_only,left_only,left_only,left_only

In [29]:
eq_accountant_w_trx_code.query("APP_SOURCE_CODE == '@@CP'")

,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_CODE_ATB,...,APP_SOURCE_CODE,TRANSACTION_DESC_ATB_F,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,_merge
161,2001369043,5820136815521,0201148049430,TNSM40110H000098,1131,1240110,2024-01-10 14.36,EUR,-198.9200000000,020,...,@@CP,Transfert Emis,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
162,2001369043,5820136815521,0201148049430,TNSM40117H000128,475,1240117,2024-01-17 13.09,EUR,-43774.7300000000,020,...,@@CP,Transfert Emis,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
163,2001369043,5820136815521,0201148049430,TNSM40131H000099,1516,1240131,2024-01-31 15.09,EUR,-31500.0000000000,020,...,@@CP,Transfert Emis,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
164,2001369043,5820136815521,0201148049430,TNSM40131H000101,1500,1240131,2024-01-31 15.09,EUR,-45357.7400000000,020,...,@@CP,Transfert Emis,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
165,2001369043,5820136815521,0201148049430,TNSM40212H000189,1432,1240212,2024-02-12 14.42,EUR,-41118.9900000000,020,...,@@CP,Transfert Emis,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,2001369043,5820136815521,0201148049430,TNSM41224H000353,3084,1241224,None,EUR,22901.8100000000,520,...,@@CP,Transfert - recu,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
898,2001369043,5820136815521,0201148049430,TNSM41225H000329,2524,1241225,None,EUR,5105.1200000000,520,...,@@CP,Transfert - recu,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
899,2001369043,5820136815521,0201148049430,TNSM41227H000281,1032,1241227,None,EUR,12618.0000000000,520,...,@@CP,Transfert - recu,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
900,2001369043,5820136815521,0201148049430,TNSM41231H000231,3434,1241231,None,EUR,6098.2400000000,520,...,@@CP,Transfert - recu,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
901,2001369043,5820136815521,0201148049430,TNSM41231H000232,3424,1241231,None,EUR,10748.0000000000,520,...,@@CP,Transfert - recu,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only

In [30]:
eq_accountant_w_trx_code.query("APP_SOURCE_CODE == '@@CP' and OP_TYPE == 'Transfert'")

,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_CODE_ATB,...,APP_SOURCE_CODE,TRANSACTION_DESC_ATB_F,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2,_merge
161,2001369043,5820136815521,0201148049430,TNSM40110H000098,1131,1240110,2024-01-10 14.36,EUR,-198.9200000000,020,...,@@CP,Transfert Emis,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
162,2001369043,5820136815521,0201148049430,TNSM40117H000128,475,1240117,2024-01-17 13.09,EUR,-43774.7300000000,020,...,@@CP,Transfert Emis,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
163,2001369043,5820136815521,0201148049430,TNSM40131H000099,1516,1240131,2024-01-31 15.09,EUR,-31500.0000000000,020,...,@@CP,Transfert Emis,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
164,2001369043,5820136815521,0201148049430,TNSM40131H000101,1500,1240131,2024-01-31 15.09,EUR,-45357.7400000000,020,...,@@CP,Transfert Emis,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
165,2001369043,5820136815521,0201148049430,TNSM40212H000189,1432,1240212,2024-02-12 14.42,EUR,-41118.9900000000,020,...,@@CP,Transfert Emis,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
897,2001369043,5820136815521,0201148049430,TNSM41224H000353,3084,1241224,None,EUR,22901.8100000000,520,...,@@CP,Transfert - recu,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
898,2001369043,5820136815521,0201148049430,TNSM41225H000329,2524,1241225,None,EUR,5105.1200000000,520,...,@@CP,Transfert - recu,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
899,2001369043,5820136815521,0201148049430,TNSM41227H000281,1032,1241227,None,EUR,12618.0000000000,520,...,@@CP,Transfert - recu,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
900,2001369043,5820136815521,0201148049430,TNSM41231H000231,3434,1241231,None,EUR,6098.2400000000,520,...,@@CP,Transfert - recu,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only
901,2001369043,5820136815521,0201148049430,TNSM41231H000232,3424,1241231,None,EUR,10748.0000000000,520,...,@@CP,Transfert - recu,Clean Payment,Transfert,code affectant directement le compte client (d...,NaN,NaN,NaN,NaN,left_only