In [1]:
import os

In [2]:
os.listdir('../param_file')

['accountant_trx - 2025-12-25.xlsx',
 'accountant_trx.xlsx',
 'accountant_trx_02_04_2025.xlsx',
 'accountant_trx_16_06_2025.xlsx',
 'accountant_trx_19_06_2025.xlsx',
 '~$accountant_trx.xlsx']

In [3]:
import pandas as pd

In [29]:
trx = pd.read_excel(io='../param_file/accountant_trx.xlsx', sheet_name='Sheet1')

In [30]:
trx = trx.dropna(
                subset=['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB']
            )

In [31]:
trx[
    ['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB']
].isna().sum()

ACCOUNTANT_SOURCE       0
APP_SOURCE_CODE         0
TRANSACTION_CODE_ATB    0
dtype: int64

In [6]:
trx.duplicated(
    subset=['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB']
).any()

False

In [7]:
assert (
    trx
    .groupby(['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB'])
    .size()
    .max() == 1
), "transaction_code is not unique on merge keys"

In [23]:
trx.groupby(['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB']).size().reset_index(name='cnt').query('cnt != 1')

Empty DataFrame
Columns: [ACCOUNTANT_SOURCE, APP_SOURCE_CODE, TRANSACTION_CODE_ATB, cnt]
Index: []

In [24]:
trx[
    ['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB']
].isna().sum()

ACCOUNTANT_SOURCE        0
APP_SOURCE_CODE         14
TRANSACTION_CODE_ATB     0
dtype: int64

In [26]:
keys = ['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB']

na_df = trx.loc[
    trx[keys].isna().any(axis=1)
].copy()

In [28]:
na_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14 entries, 474 to 2404
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ACCOUNTANT_SOURCE         14 non-null     object
 1   APP_SOURCE_CODE           0 non-null      object
 2   TRANSACTION_CODE_ATB      14 non-null     int64
 3   TRANSACTION_DESC_ATB      14 non-null     object
 4   APP_SOURCE                0 non-null      object
 5   OP_TYPE                   0 non-null      object
 6   Categorie_de_transaction  1 non-null      object
 7   TRANSACTION_CODE_GOAML    0 non-null      object
 8   TRANSACTION_DESC_GOAML    0 non-null      object
 9   FUND_CODE_1               0 non-null      object
 10  FUND_CODE_2               0 non-null      object
 11  IS_INTERFACE              0 non-null      object
 12  IS_MANUELLE               0 non-null      object
dtypes: int64(1), object(12)
memory usage: 1.5+ KB

In [16]:
trx.head().T

,0,1,2,3,4
ACCOUNTANT_SOURCE,EQ,EQ,EQ,EQ,EQ
APP_SOURCE_CODE,T24TL,UAJL,@@CC,TLVIR,@@FM
TRANSACTION_CODE_ATB,297,920,120,10,401
TRANSACTION_DESC_ATB,Comm.OPPOS EFFET,Interets,Remb avance placement,Debit,Exchange Delivery
APP_SOURCE,Teller,NaN,NaN,IBANK,NaN
OP_TYPE,Caisse,NaN,NaN,Virement,NaN
Categorie_de_transaction,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
TRANSACTION_CODE_GOAML,NaN,NaN,NaN,NaN,NaN
TRANSACTION_DESC_GOAML,NaN,NaN,NaN,NaN,NaN
FUND_CODE_1,NaN,NaN,NaN,NaN,NaN
FUND_CODE_2,NaN,NaN,NaN,NaN,NaN
IS_INTERFACE,Y,NaN,NaN,NaN,NaN
IS_MANUELLE,NaN,NaN,NaN,NaN,NaN

In [21]:
trx[trx.duplicated(subset=['APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB', 'APP_SOURCE', 'OP_TYPE'], keep=False)]

Empty DataFrame
Columns: [ACCOUNTANT_SOURCE, APP_SOURCE_CODE, TRANSACTION_CODE_ATB, TRANSACTION_DESC_ATB, APP_SOURCE, OP_TYPE, Categorie_de_transaction, TRANSACTION_CODE_GOAML, TRANSACTION_DESC_GOAML, FUND_CODE_1, FUND_CODE_2, IS_INTERFACE, IS_MANUELLE]
Index: []